lib/perl/Genome/Model/Tools/EpitopePrediction/NetmhcPipeline.pm
lib/perl/Genome/Model/Tools/EpitopePrediction/NewPipeline.pm
lib/perl/Genome/Model/Tools/EpitopePrediction/Pipeline.pm
lib/perl/Genome/Model/Tools/EpitopePrediction/RunNetmhc.pm
lib/perl/Genome/Model/Tools/EpitopePrediction/RunNetmhcpan.pm

Jasreet tried to run the epitope predicition command with epitope_length set to "8,9,10" expecting this to be an is_many property. Because the data type was set to Text she was able to successfully dispatch the workflow but it failed down the line because the underlying tool expects this to be a single integer. Setting the data type to Integer would throw an error if this parameter was set to something like the above.
Down the line we might want to consider making this an is_many property and running this workflow as a parallel by.

Epitope length needs to be of Integer data type instead of Text

---

lib/perl/Genome/Config/AnalysisProject/Command/ReplaceModel.pm
lib/perl/Genome/Config/AnalysisProject/Command/ReplaceModel.t
lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.pm
lib/perl/Genome/Config/Profile.pm
lib/perl/Genome/Config/Profile.t
lib/perl/Genome/Config/Profile/Item.pm
lib/perl/Genome/Config/Profile/Item.t

Extract the process model get/create from CQID into config profile so that both CQID and the replace model command can use it.

AnP Replace Model Uses Config Profile

---

lib/perl/Genome/Model/Build.pm
lib/perl/Genome/Model/Build/Command/ListVolumes.pm

Another attempt at a lister for allocations/volumes connected to a build
This one inherits from UR::Object::Command::List, but it's complicated by the fact that --filter applies to the builds you're interested in inspecting, it collects Allocation Set objects related to those builds, then --show applies to those Sets.

Build volume lister command

---

lib/perl/Genome/Model/SingleSampleGenotype/Command.pm

This should fix tab-completion and the commands showing up in `genome model --help`.

Add a base for the SSG command tree.

---

lib/perl/Genome/Model/ReferenceAlignment/Command/AlignReads.pm

This fixes a regression found by the `refalign-germline-short` model test.
ReferenceAlignment should produce a single BAM regardless of how many different samples the instrument data came from.

ReferenceAlignment makes one BAM regardless of mixed sample assignment.

---

lib/perl/Genome/Model/ReferenceAlignment/Command/BamQc.pm

This fixes a bug I introduced in #1270 (right [here](https://github.com/tmooney/genome/commit/26017071733a84e4f78094d7762f21c133558940#diff-d38dfe2f448c8bdee9ef7eb70b2eac68R73)).  That germline model test is coming in handy--the regular refalign test didn't catch these!

BamQC should only check instrument data for the result it will run on.

---

lib/perl/Genome/Model/Build/ReferenceSequence.pm
lib/perl/Genome/Model/Build/ReferenceSequence/Buckets.t
lib/perl/Genome/Model/Build/ReferenceSequence/Converter.pm
lib/perl/Genome/Model/ReferenceSequence/Command/CreateBuckets.t
lib/perl/Genome/Model/SingleSampleGenotype/Command/PrepareReferenceBuckets.t

A new reference sequence converter that relies on matching the md5 in each build sequence dictionary to map chromosome names.

New chr_md5 reference converter

---

lib/perl/Genome/Model/Tools/Analysis/LaneQc/CompareSnpsBuildLanes.pm
lib/perl/Genome/Model/Tools/Analysis/LaneQc/CopyNumber.pm
lib/perl/Genome/Model/Tools/Analysis/LaneQc/EntireBuild.pm
lib/perl/Genome/Model/Tools/Picard.pm
lib/perl/Genome/Model/Tools/Varscan/PullOneTwoBpIndels.pm
lib/perl/Genome/Utility/Email.pm
lib/perl/Genome/Utility/Email.t

Since we now have users spanning multiple domains with possibly inconsistent usernames, we can't assume the `username` plus the configured `email_domain` equals the desired address.

Get E-Mail Address from User Object

---

lib/perl/Genome/Config/AnalysisProject/Command/Create.pm
lib/perl/Genome/Model.pm
lib/perl/Genome/Model/Command/Admin/FailedModelTickets.pm
lib/perl/Genome/Model/Command/Services/ListBuildQueue.pm
lib/perl/Genome/Model/ReferenceAlignment.pm
lib/perl/Genome/Model/SomaticValidation.pm
lib/perl/Genome/Sys.pm
lib/perl/Genome/Sys.t

Now there's a `Genome::Sys::User::Role` named `production` when deciding to act.
* The default user for new `production` projects has been changed to `prod-builder`.
* `apipe-builder` remains the user with the power to manipulate others' builds.
* The old heuristic for LIMS to find non-project-based data (in `Genome::InstrumentData::Solexa`) is explicitly not being updated.

Production No Longer Hardcoded to "apipe-builder".

---

lib/perl/Genome/Model/Tools/Somatic/FilterFalsePositives.pm

The FilterFalsePositives module is run as a part of the LOH pipeline. Currently
if the variant file that is passed to this module is empty,
the workflow crashes with an error message (bam-readcount is invoked
with an empty file which causes it to die). Instead I think
we'd like this module to spit out a warning and not attempt to
filter if the input is empty.

Make FilterFalsePositives not die on empty input.

---

lib/perl/Genome/Model/ClinSeq/Command/CreateMutationSpectrum.pm

Currently clinseq attempts to run mutation spectrum sequence
context on an empty input which causes the downstream R module
to die unpredictably. We'd like to skip running this analysis
when the tier1 variant file is empty instead.

Skip mutation spectrum on empty input

---

lib/perl/Genome/InstrumentData/Composite/Workflow.t
lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/AlignAndMerge.pm

There were previous assumptions baked into this implementation that meant only one AlignAndMerge could appear within a run of the dispatcher.  The step would also not work properly if meant to only run on a subset of the data.  This PR addresses both of these shortcomings.

Support Multiple Merge Groups for AlignAndMerge in the AlignmentDispatcher

---

lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/Merge.pm

They have always been optional to the merge step itself; this informs the master workflow they're not required.

Duplication Handling in the Alignment Dispatcher Is Optional.

---

lib/perl/Genome/Model/Tools/DetectVariants2/Filter/NovoRealign.pm

Use whitespace to denote end of string rather than word-boundary.  Non-word characters are excluded from the end of the library string such as double quotation marks.  
The change is triggered by SpeedSeq passing the LIMS BAM header rather than recreating the header from sample meta-data.  I'm not sure why the LIMS BAM header has doube quotes around the library name, but that is the source of this issue.

SV realignment compatibility with SpeedSeq BAM headers

---

lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json
lib/perl/Genome/WorkflowBuilder/Command.pm

This cannot pass tests until genome-snapshot-deps has been updated via this PR: https://github.com/genome/genome-snapshot-deps/pull/67
This will put data from the Job services on the PTero execution's data
field saving us from querying the Job service.

Use new 'service_data_to_save' feature of PTero

---

etc/genome/spec/lsf_job_group.yaml
lib/perl/Genome/Ptero/ToJSON.t
lib/perl/Genome/Ptero/ToJSONForProcess.t
lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json
lib/perl/Genome/Sys/LSF/ResourceParser.pm
lib/perl/Genome/WorkflowBuilder/Command.pm

This will allow the group owner (read: `apipe-builder`) to manipulate LSF jobs for any running `PTero` workflows launched from `Genome`.

Specify a default job group for PTero-launched jobs.

---

lib/perl/Genome/Command/PteroWorkflowMixin.pm

This makes it easier to track down additional information about an execution (e.g. the LSF Job ID), which is otherwise not included in the output.

Add an ID column to the Ptero Workflow display.

---

lib/perl/Genome/File/Vcf/VepConsequenceParser.pm
lib/perl/Genome/VariantReporting/Report/FullReport.pm
lib/perl/Genome/VariantReporting/Report/SimpleReport.pm
lib/perl/Genome/VariantReporting/Report/SimpleReport.t
lib/perl/Genome/VariantReporting/Report/SimpleReport.t.d/expected/report.txt
lib/perl/Genome/VariantReporting/Report/SimpleReport.t.d/expected/report.txt.legend

c_position column from vep output need to be added to report. This PR also replaces the obsolete CGI with URI::Escape, which fixes a bug that unescapes + into space with CGI.

Add c_position to variant report

---

lib/perl/Genome/Model/Build/Command/DetermineError.pm

Otherwise we're really checking the same line a second time, which doesn't get us any additional information.
(This fixes reporting for code that uses the pattern `die $self->error_message`.  The newer `$self->fatal_message` is unaffected.)

DetermineError: Properly handle case where dies on next line of logs.

---

lib/perl/Genome/Process/Command/DiffBlessed.pm.YAML

All diff is caused by the newly added c_posiotion column in report. Now update blessed object. Need merge this asap to make model/process test pass.

Update blessed process object for Jenkins genome-process-test

---

etc/genome/spec/parent_workflow_log_directory.yaml
lib/perl/Genome/Config/Command/List.t

This fixes `genome config list`, which chokes on undefined values.

Set a default empty value for parent_workflow_log_directory.

---

bin/genome-env

This facilitates running `genome-env` from a snapshot directory.

Add option to not rebuild the meta DB.

---

lib/perl/Genome/Model/GenotypeMicroarray.pm
lib/perl/Genome/Model/GenotypeMicroarray.t

This was already `PTero`-compatible, but now it doesn't depend on `Workflow`.

GenotypeMicroarray uses WorkflowBuilder.

---

lib/perl/Genome/Command/PteroWorkflowMixin.pm

Now that PTero is configured to pass the job ID back to the execution (per PR #1325), we can get this info without an additional API call per job.  Instead it's in the info we're already pulling back!
I promise I updated the `else` cases this time!  (cf. PR #1329)

Add LSF ID to the Ptero workflow display.

---

lib/perl/Genome/Model/Build/ClinSeq/InputBuilds.pm
lib/perl/Genome/Model/ClinSeq.pm

This PR makes ClinSeq use WorkflowBuilder. It also includes some refactoring of the _resolve_workflow_for_build subroutine by split the various parts of the workflow into separate subroutines for clarity (hopefully).
I ran a ClinSeq test build in a custom checkout and the workflows look identical. @jasonwalker80, you mentioned that you were working on a ClinSeq model that would include all possible steps. It might be worthwhile to run a build of that model on this PR to make sure that all steps are still executed.
@acoffman, @gatoravi , @jasonwalker80 Feel free to push additional commits to this PR with any improvements that might be necessary while I'm on vacation.

Port ClinSeq to use WorkflowBuilder

---

lib/perl/Genome/Model/Tools/Bsmap/MethRatio.t
lib/perl/Genome/Model/Tools/Bsmap/MethylationRatio.t

`fasta_file` is the original import location of the file, not the current location.

Use correct accessor to get FASTA for bsmap tests.

---

lib/perl/Genome/Db/Ensembl/Command/Run/Base.pm

The `NO_LSF` variable is dependent on Workflow to succeed.  (This was the only place outside of a test where it was still being used.)

Use inline workflow backend instead of NO_LSF environment variable.

---

lib/perl/Genome/InstrumentData/Command/MergeAlignments.pm

Production jobs were ending up in the default queue, which is suboptimal.

MergeAlignments: Specify an LSF queue configuration.

---

lib/perl/Genome/Model/Build/Command/Abandon.pm
lib/perl/Genome/Model/Build/Command/Base.pm

This used to inspect to see which of its subclasses it was, which is not ideal.  I wanted to add support for "AbandonAndQueue", but it turned out this made the list match all known subclasses, so it's easier to remove the check.

Allow apipe-builder to use AbandonAndQueue.

---

etc/genome/spec/lsf_resource_somvar_reports.yaml
lib/perl/Genome/Model/SomaticVariation/Command/CreateReport.pm

We had this get `TERM_MEMLIMIT`ed recently.

Make LSF resource for SomaticVariation report step configurable.

---

lib/perl/Genome/Db/Ensembl/AnnotationStructures.pm
lib/perl/Genome/Transcript.pm
lib/perl/Genome/TranscriptStructure.pm

The annotator is being used less and less, but it's still relied upon by parts of the GMS.  This PR includes additional annotation biotypes and statuses for Ensembl 84 annotation.  Moving the creation of the biotype_class to a class method should help with troubleshooting future annotation builds.

Annotator updates for Ensembl 84

---

lib/perl/Genome/Model/ReferenceAlignment/Report/Summary.t

More accurately, it doesn't use the real lock location so multiple test runs don't collide.
I'd be swell to use `Genome::Config::set_env('site_lock_dir', Genome::Sys->create_temp_directory)` instead, but using `Genome` already takes us past the point where this value gets examined.

RefAlign Summary Test Doesn't Lock

---

lib/perl/Genome/Model/ClinSeq.pm

Currently if a clin-seq build only has a exome_model as an input,
the wgs version of create-mutation-spectrum is still added as a
step in the workflow. This pull-request hopes to fix that.

Add wgs/exome only if input builds exist

---

lib/perl/Genome/Sys/Lock/FileBackend.t

Deal with the warning message.  Make the debugging message to the standard output to use the diag.

deal with warning message

---

lib/perl/Genome/paths_case_insensitive.t

Although Jenkins hasn't noticed, this test has been failing under test-tracker since it doesn't load any Genome modules.  While it lasts, [here's an example](https://apipe-ci.gsc.wustl.edu/job/1-Genome-Perl-Tests/6403/PERL_VERSION=5.10/testReport/(root)/paths_case_insensitive_t/1___found_more_than_one_file/). 
Ideally this test would always run, since it tests every path in the repo, but I don't think making it duplicate the WebApp Core test by `use`ing the entire tree is worthwhile.

Use Genome so test-tracker succeeds.

---

lib/perl/Genome/Model/ClinSeq.pm

I missed @tmooney's last comment on #1364 before merging. This PR fixes the iteration over the base/mapping qualities so that we are not repeatedly using `$i-1`.

Slight refactor of qualities iterator to avoid $i-1

---

lib/perl/Genome/compile.t

Otherwise, the standard output will interfere with the
TAP output.

Redirect the standard output and error to the /dev/null.

---

lib/perl/Genome/Model/SingleSampleGenotype/Command/ListOutputFiles.t

This change calms Perl's fears about our ability to consistently spell.

Quiet variable use warning in SSG ListOutputFiles test.

---

lib/perl/Genome/Model/Build.pm
lib/perl/Genome/Model/Build/Command/SymlinkResults.pm
lib/perl/Genome/Model/Build/Command/SymlinkResults_SingleSampleGenotype.t
lib/perl/Genome/Model/Build/SingleSampleGenotype.pm

* New command `genome model build symlink-results` (like `genome process symlink-results`) to create a build-directory like structure of results for a build...currently only implemented for SSG.
* SSG uses one of these build-directory like checkouts to do its diff-ing, since the diff logic is primarily based on directories of results.
(This PR is offered as an alternative to #1288.)

SingleSampleGenotype Can Be Checked Out; Uses Said Checkout for Diffs

---

lib/perl/Genome/Ptero/ExecutionInfo.pm
lib/perl/Genome/Ptero/ExecutionInfo.t

This command seems to work given the IDs from #1316, but I wanted to make a PR a bit early to solicit feedback.
* Is there a better name for this than `genome ptero execution-info`?
* How should we _really_ get the execution URL?  (Another config variable? Another method in `Genome::Ptero::Utils`? Both?)
* Is there any other information that ought to be included? (Is the output too noisy to display by default?)
* Between this and #1312, would it be worthwhile to make a more official PerlSDK-ish proxy for Job entities?
* Does something already do most of this, and I'm wasting my time? :smile: 
TODO:

A Command to Get Information about a PTero Execution.

---

lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/ImportInstData.pm

Another step on the road to eliminating `Workflow`!

Use the new execute_inline for DAG instead of relying on Workflow.

---

lib/perl/Genome/WorkflowBuilder/Detail/Operation.pm
lib/perl/Genome/WorkflowBuilder/Test/XmlReferences.t
lib/perl/Genome/WorkflowBuilder/Test/XmlReferences.t.d/inner.xml
lib/perl/Genome/WorkflowBuilder/Test/XmlReferences.t.d/outer.xml

One smaller feature `Workflow` has is that the definition of an operation can be in a separate file.  This brings that feature to `WorkflowBuilder`.

WorkflowBuilder supports references to other XML files

---

lib/perl/Genome/Model/ClinSeq/Command/Converge/CufflinksDe.pm
lib/perl/Genome/Model/ClinSeq/Command/Converge/CufflinksDe.t

As part of cleanup of old data we've been removing directories for Abandoned builds.  This is one of a few tests that was using an Abandoned build for its data.  With this change it's not relying on production data at all!
This PR includes a small change to the tool: the hash keys are now sorted so that the output is consistent.

ClinSeq's Cufflinks Converge uses Test Data

---

lib/perl/Genome/Model/ClinSeq/Command/Converge/SummarizeSnvIndelReport.t

A similar story as in #1401... The production data backing this test is gone, so we need to use test data!

ClinSeq's SummarizeSnvIndel Converge Test Uses Test Data

---

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML

PR #1392 changed some file contents from 'Somatic Variation' to 'Somatic'
`vimdiff <(sort /gscmnt/gc9022/info/model_data/8a175224cae14b80ab36d749216efb2b/buildb11e803ca7c048e29ec8ba42cd364a06/AML109/input/summary/Stats.tsv) <(sort /gscmnt/gc9026/test/model_data/8a175224cae14b80ab36d749216efb2b/build0bc8c6ff5d4c4fc0ae645335f738a29d/AML109/input/summary/Stats.tsv)`

New ClinSeq blessed build

---

lib/perl/Genome/Model/ClinSeq/Command/SummarizeSvs.t

This test is currently failing on master because it relies on deleted production data. This PR fixes that.

ClinSeq SummarizeSvs uses test data for is test

---

lib/perl/Genome/Model/SmallRna/Command/SmallRnaWorkflow.xml

These extra connections have been in the workflow for a long time, but `WorkflowBuilder` is stricter about validating this.

SmallRNA: Remove inputs that are already supplied via other steps.

---

lib/perl/Genome/Model/Command/Define/ReferenceSequence.t
lib/perl/Genome/Model/SomaticValidation/Command/ValidateLargeIndels/CreateAssembledContigReference.pm
lib/perl/Genome/Model/SomaticValidation/Command/ValidateSvs/CreateAssembledContigReference.pm

The inline workflow_builder_backend takes care of most use cases.  A future PR will remove this feature from Build entirely.

Stop using "server_dispatch => 'inline'" feature.

---

lib/perl/Genome/FeatureList.pm

This is a proposed replacement for #1407.
Add option for stripping off the chr in processed_bed_file_content.  By default generate_converted_bed_file will never strip chr from the BED content.

Processed BED without chr substitution : Option #2

---

lib/perl/Genome/InstrumentData/AlignmentResult/WithIntermediateResults.pm

The addition of the `shortcut` label as this is used by the main AR was preventing its subsequent deletion.  This change broadens the inactivation of users.
(An alternative might be to inactivate all users and forcibly remove the result.  That would eliminate any means of claiming intermediate results, though.)

Better Intermediate Result Deletion

---

lib/perl/Genome/Model/Build/GenePrediction/Bacterial.pm
lib/perl/Genome/Model/Tools/Predictor/Ber.pm

These modules are slated for eventual removal... but the contents of the allocation on `/gscmnt/gc9002/` are slated for earlier removal than that.

Path for BER has moved.

---

lib/perl/Genome/Model/Build/Command/Start.t

After #1429, #1430, and #1431 this is the last reference to `NO_LSF` left in Genome.

Don't worry about the value of NO_LSF variable in Build Start test.

---

lib/perl/Genome/Model/SmallRna/Command/SmallRnaWorkflow.xml

As in #1399, our workflow engines complain about multiple links to the same input.

Remove more redundant workflow links from SmallRNAWorkflow.

---

etc/genome/spec/lsf_resource_annotate_variants.yaml
lib/perl/Genome/Model/ReferenceAlignment/Command/AnnotateVariants.pm
lib/perl/Genome/Model/SomaticValidation/Command/AnnotateVariants.pm

The default 4GB is normally sufficient here, but occasionally we have to increase it.

Add a config variable for the LSF resource for annotation.

---

lib/perl/Genome/Model/ReferenceSequence/Command/CreateAlignerIndex.pm

This was a hole found during the conversion to docker.

Specify an LSF queue for aligner index creation.

---

lib/perl/Genome/VariantReporting/Command/Wrappers/IgvSession.pm
lib/perl/Genome/VariantReporting/Command/Wrappers/ModelPairFactory.pm
lib/perl/Genome/VariantReporting/Command/Wrappers/ModelPairFactory.t
lib/perl/Genome/VariantReporting/Command/Wrappers/Trio.pm
lib/perl/Genome/VariantReporting/Process/Trio.pm
lib/perl/Genome/VariantReporting/plan_files/cle_somatic_docm_report_indels.yaml
lib/perl/Genome/VariantReporting/plan_files/cle_somatic_docm_report_snvs.yaml
lib/perl/Genome/VariantReporting/plan_files/cle_somatic_indels_report.yaml
lib/perl/Genome/VariantReporting/plan_files/cle_somatic_snvs_report.yaml

Currently trio wrapper works on three samples: normal, tumor and followup. But there are cases in cle that only have normal and tumor available. This PR is to tweak the trio command and its supporting modules to make trio work on cases without followup.

Make trio wrapper work on somatic cases

---

etc/genome/spec/lsf_resource_annotate_variants.yaml

Recently there are quite a few of cle somatic validation builds failed at annotation step due to out of memory. This PR doubles the default memory usage for variant annotation.

Increase annotation memory usage from 4g to 8g

---

lib/perl/Genome/Model/Tools/Vcf/Convert/Base.pm
lib/perl/Genome/Model/Tools/Vcf/Convert/Base.t

The [TCGA Data Portal](https://tcga-data.nci.nih.gov) has been down several days and contains a note directing users to the GDC Portal instead.  This updates our TCGA barcode query to retrieve the UUID from the GDC API.

Use GDC Portal instead of TCGA Portal

---

lib/perl/Genome/Model/ClinSeq.pm

@kkrysiak ran into the following error in production:
```
Could not start build 34774bf01c0d472480b8cd6ca3a86c7c, reason: Can't call method "has_snvs_annotated_variants_vcf_file" on an undefined value at /gsc/scripts/opt/genome/snapshots/genome-3714/lib/perl/Genome/Model/ClinSeq.pm line 784.
```
This should hopefully remedy that!

Only check for the annotated vcf if the build exists

---

lib/perl/Genome/FeatureList/Command/Import.pm

I'm not sure why there'd be blank lines here to begin with, but at least there's a straightforward thing to do with them. 😄

FeatureList Import: Skip blank lines instead of crashing.

---

lib/perl/Genome/Model/RnaSeq.t

The existing diff logic was dependent on configuration having certain values, which defeats the purpose of configuration!  (We recently changed away from the assumed values, exposing this flaw.)

Better Model/RnaSeq.t Diffs

---

etc/genome/spec/lsf_resource_dv2_speedseq_sv.yaml
lib/perl/Genome/Model/Tools/DetectVariants2/SpeedseqSv.pm
lib/perl/Genome/Model/Tools/DetectVariants2/SpeedseqSv.t

1. Skip the sort since the output is VCF.
2. Generate a symlink for the VCF (and index) so the DV2 Dispatcher will find the output file.
3. Increase RAM to 16GB

Speedseq SV remove sort and symlink VCF.

---

lib/perl/Genome/Model/SomaticValidation/Command/VerifyBam.pm
lib/perl/Genome/Model/Tools/DetectVariants2/Mutect.pm
lib/perl/Genome/Model/Tools/Mutect/ParallelWrapper.pm

The default queue is no longer guaranteed to work, which makes it easier to spot cases where the queue specification has been omitted.

Specify queues in Mutect and SomVal's VerifyBam.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Bsmap.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Rtg.pm
lib/perl/Genome/Model/Tools/Analysis/Coverage/AddReadcounts.pm
lib/perl/Genome/Model/Tools/Analysis/Coverage/BamReadcount.pm
lib/perl/Genome/Model/Tools/Analysis/Coverage/CoveragePlot.t
lib/perl/Genome/Model/Tools/Analysis/Coverage/MergeReadcounts.pm
lib/perl/Genome/Model/Tools/Analysis/Coverage/MergeReadcounts.t
lib/perl/Genome/Model/Tools/Analysis/Mendelian/RareHetRuleOutVcf.pm
lib/perl/Genome/Model/Tools/Analysis/Mendelian/SharedIbdVcf.pm
lib/perl/Genome/Model/Tools/Analysis/MutationRate.pm
lib/perl/Genome/Model/Tools/Annotate/RegulatoryFeatures.pm
lib/perl/Genome/Model/Tools/Bed/Convert/Snv/MutectToBed.t
lib/perl/Genome/Model/Tools/Mutect.pm
lib/perl/Genome/Model/Tools/Somatic/FilterMouseBases.pm
lib/perl/Genome/Model/Tools/Somatic/FilterPindel.pm
lib/perl/Genome/Model/Tools/Somatic/LaunchPindel.pm
lib/perl/Genome/Model/Tools/Somatic/LibrarySupportFilter.pm
lib/perl/Genome/Model/Tools/Sv/Pairoscope.pm
lib/perl/Genome/Model/Tools/Validation/ClonalityPlot.pm
lib/perl/Genome/Model/Tools/Validation/GetGeneTargets.pm
lib/perl/Genome/Model/Tools/Validation/LongIndelsParseRemapped.pm
lib/perl/Genome/Model/Tools/Vcf/Convert/Snv/Mutect.t
lib/perl/Genome/Model/Tools/Vcf/ConvertToBeagle.pm

Having a bunch of hard-coded paths around in the code is sub-optimal!  Most of these were in comments or examples, but a few remove defaults.
Subsequent PRs will address other affected modules for which I think more expansive changes are required.

Remove References to Volumes Being Retired

---

lib/perl/Genome/Model/GenePrediction/Command/Pap/BtabHmmtab.pm
lib/perl/Genome/Model/GenePrediction/Eukaryotic.pm

These didn't `use Workflow` or its derivatives but still referred to `Workflow::Model`.

Remove uses of Workflow::Model in GenePrediction.

---

lib/perl/Genome/Model/ClinSeq.pm

This was converted to WorkflowBuilder in #1326, but this comment was missed.  (This now returns a `Genome::WorkflowBuilder::DAG`, but I don't think a comment to that effect is necessary.)

ClinSeq: Remove false comment.

---

lib/perl/Genome/Sys.pm

It seems our systems are sometimes unreliable at returning a value here, causing some build failures.  In my testing, it will fail to return a value on the first attempt, but the second attempt will succeed.  Trying this five times is thus probably overkill(!), but hopefully is sufficient to make `Genome::Sys->username` reliable.
~~If things really go poorly, the user_id is often "good enough" as a unique per-user value... just one less friendly to the viewer.  However, it's insufficient to locate a `Genome::Sys::User` object, so anything depending on real user objects would still fail.~~

If we don't get a username back from `getpwuid`, try again!

---

lib/perl/Genome/Sys.pm

Per @brummett's suggestion, save the username if we succeed to save us from further travails if `getpwuid` is acting up.

Cache the username in Genome::Sys->username.

---

lib/perl/Genome/Model/SomaticValidation/Command/IdentifyDnp.pm
lib/perl/Genome/Model/SomaticValidation/Command/ProcessValidation.pm
lib/perl/Genome/Model/SomaticValidation/Command/ValidateSvs/CreateAssembledContigReference.pm
lib/perl/Genome/Model/SomaticValidation/Command/ValidateSvs/GenerateMergedAssemblies.pm
lib/perl/Genome/Model/Tools/Gatk/IndelRealigner.pm
lib/perl/Genome/Model/Tools/Validation/LongIndelsParseRemapped.pm
lib/perl/Genome/Model/Tools/Varscan/ProcessValidationIndels.pm
lib/perl/Genome/Model/Tools/Varscan/PullOneTwoBpIndels.pm
lib/perl/Genome/Model/Tools/Varscan/Validation.pm

I am surprised so many SomaticValidation build steps didn't already have a queue set; I'd thought this was required awhile ago.  At any rate, now `WorkflowBuilder` will specify a queue for any steps that don't have one set.

Specify a default queue in several SomVal steps.

---

lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder/Bam.downsample.t
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder/Bam.t
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder/Fastq.t
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder/Sra.t
lib/perl/Genome/Ptero/ToJSON.t
lib/perl/Genome/Ptero/ToJSONForProcess.t
lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json
lib/perl/Genome/VariantReporting/Framework/TestHelpers.pm
lib/perl/Genome/WorkflowBuilder/Command.pm

This was split off from #1487 after it led to a large number of test failures.  This version includes updates to applicable tests to ignore whatever queue might be specified.  (Since it's decided by config, we shouldn't rely on it having any particular value!)

Use Config to Select a Default LSF Queue if None Specified

---

lib/perl/Genome/Model/Tools/Germline/Filtering.pm

The hard-coded versions are on volumes slated for removal, and hardcoded paths are bad, anyway!
This tool appears to be in active use, so a CHANGELOG entry is included with this commit.

Replace hard-coded NHLBI and 1000 Genomes files with parameters.

---

lib/perl/Genome/Ptero/TestCommand/NullCommand.pm

Somehow this hardcoded queue in the Ptero tests snuck by us!

Use config to decide the LSF queue (Ptero NullCommand)

---

lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json
lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json
lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json
lib/perl/Genome/WorkflowBuilder/Command.pm

LSF doesn't automatically launch the pre- and post-exec commands within the chosen docker container, so we've got to call the docker_run.py script ourselves.
In the future I'd like to make some ptero-lsf docker images to accomplish the pre- and post-exec tasks rather than specifying these commands manually within the main container, but this gets these back to their main task of maintaining workflow status.

Fix ptero-lsf-{pre,post}-exec within docker

---

lib/perl/Genome/Model/ClinSeq.pm

In #1472 I made a suggestion that made this not work quite right, because it might make duplicate operations.  This should fix that issue!
(This is another PR that benefits from the `?w=1` option.)

Only create one annotate_snvs_vcf_op per type.

---

lib/perl/Genome/WorkflowBuilder/Command.pm

If Ptero's post-exec fails, these logs are never copied out of /tmp/ and into Ptero's DB, so they are lost  exactly when we'd be most interested in them!  This writes them to the Workflow's log directory, so in case of trouble they'll stick around for inspection.  Otherwise our post-exec should clean them up as usual.

Keep logs around when Ptero's post-exec fails.

---

etc/genome/spec/lsf_queue_alignment_prod.yaml

We haven't used this for anything in awhile.  (`lsf_queue_alignment_default` is instead configured as prod or not depending on the circumstances.)

Remove "lsf_queue_alignment_prod" config.

---

lib/perl/Genome/VariantReporting/Framework/Component/Report/MergedReport.pm
lib/perl/Genome/VariantReporting/Framework/MergeReports.t

Currently trio process will crash at merge report step if one of input bed file is empty (refer to https://jira.gsc.wustl.edu/browse/CI-167). This PR fixes this.

Make trio wrapper merge work if one of input reports is empty

---

lib/perl/Genome/Model/Tools/BioSamtools/RepeatContent.pm
lib/perl/Genome/Model/Tools/Capture/EvaluateExomeBreadth.pm

The repeat masker file was moved.  Instead of a default_value it's switched to an example_value.
For the capture tool, the default_value was simply removed.

Remove references to sata132/jwalker file paths.

---

lib/perl/Genome/Model/SomaticVariation.pm

The base class has long since accepted either a `Genome::WorkflowBuilder::DAG` or a `Workflow::Model`. This PR switches SomaticVariation from the latter to the former.

SomVar uses WorkflowBuilder

---

lib/perl/Genome/Model/Tools/Vcf/Convert/Base.pm
lib/perl/Genome/Model/Tools/Vcf/Convert/Base.t
lib/perl/Genome/Model/Tools/Vcf/Convert/Indel/Pindel.t
lib/perl/Genome/Model/Tools/Vcf/Convert/Snv/Strelka.t
lib/perl/Genome/Model/Tools/Vcf/Convert/Snv/VarscanSomatic.t
lib/perl/Genome/Model/Tools/Vcf/Convert/Snv/VarscanSomaticValidation.t

The GDC portal now requires newer SSL to perform the handshake, so disable the TCGA support for "older" systems.  (Running with an outdated OpenSSL is scary, and one probably shouldn't do it, anyway!)

Require a newer SSL implementation to perform the web queries.

---

lib/perl/Genome/Ptero/Wrapper.pm

Letting a few messages leak into the task's log files is far better than throwing out all of our work when there's an issue reopening the original log file!
(#1509 is a long-term solution to the present problem causing the errors reopening the log file, but we probably shouldn't fail in any event.)

Don't die just because we can't revert the logging.

---

lib/perl/Genome/InstrumentData/AlignmentResult.pm

This reduces the number of false-positives when the same data has been aligned to many references, saving us from collecting all their individual alignments when we know they won't match.
(This is a bit of a selfish improvement, since the most drastic impact will be on test data that gets aligned to many, many references 😄 )

AlignmentResult: Check the reference and annotation builds when seeking our Merged result(s)

---

lib/perl/Genome/Model/ReferenceAlignment/Command/BamQc.pm

This shouldn't use the same queue as its workers, lest they potentially deadlock.

Use lower queue for BamQc "server" process.

---

lib/perl/Genome/FeatureList.pm

Although imported feature-lists often are sorted, we don't guarantee that, so better sort here.

bedtools merge requires the file to be sorted.

---

lib/perl/Genome/Process/Command/DiffBlessed.pm.YAML

All diff is caused by the newly added n-callers and vaf-cutoff filters in snv plan files and annotation-category filter in indel plan file. Need merge this asap to make model/process test pass.

Update blessed process for Jenkins genome-process-test

---

lib/perl/Genome/WorkflowBuilder/Command.pm

This uses the new features in genome/ptero-lsf#124 and genome/ptero-perl-sdk#117 to ensure a unique filename is chosen for each job, even during a parallel-by.  As a bonus that filename's UUID will now be the Job ID making it easier to match to the job to which it belongs.
(This should not be merged until the aformentioned PRs are deployed.)

Defer to new Ptero feature to decide the log paths.

---

lib/perl/Genome/WorkflowBuilder/Command.pm

LSF will translate this for us to be the LSF Job ID.

Use %J (LSF's standard) instead of %%JOB_ID%%.

---

lib/perl/Genome/InstrumentData/Command/Import/Basic.pm
lib/perl/Genome/InstrumentData/Command/Import/Inputs.pm
lib/perl/Genome/InstrumentData/Command/Import/Inputs/Factory.pm
lib/perl/Genome/InstrumentData/Command/Import/Inputs/Factory.t
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/ImportInstData.pm

This will overcome the problem of not having enough local (tmp) disk space to process files for import.

InstData Import: allow the specification of working directory

---

lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.pm

If someone manually resets the status to `new` (for example, via `genome analysis-project reprocess`) they probably expect us to try their instrument data at least once in short order!  This is also a good clue that they may have corrected whatever issues were causing the previous failures.
If it still fails, its `fail_count` will be incremented as usual and it'll fall back to its previous spot in line.

CQID: Give all the "new" things a try first.

---

lib/perl/Genome/Model/Build/ReferenceSequence/Converter.pm

The sequences in our references don't seem to really match, but I'm told that these are interchangeable.

Convert chrM to MT.

---

lib/perl/Genome/Model/Build/ReferenceSequence.pm
lib/perl/Genome/Model/ImportedAnnotation.pm

This changes two things:
* The UCSC conservation directory must be manually linked to each annotation build that wants it.
* The UCSC tiering files for a reference should be linked into the reference build instead of using a hard-coded path.

UCSC annotation file changes for ReferenceSequence

---

lib/perl/Genome/Model/Build/ReferenceSequence/ConvertedBedResult.pm

I recently encountered a build with this error message in it, but 
```
Failed to convert from bed (...) with reference (Genome::Model::Build::ImportedReferenceSequence=HASH(0x70802e0)) to bed (...) with reference (Genome::Model::Build::ImportedReferenceSequence=HASH(0x70260c0)
```
is not the most informative!

RefSeq Converter: Use names of references instead of object hashes in error message.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Bwa.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Bwamem.pm
lib/perl/Genome/InstrumentData/AlignmentResult/BwamemStream.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Bwasw.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Merged/Speedseq.pm
lib/perl/Genome/Model/Build.pm

Since they're being very aggressively archived, we're frequently running into the situation where we want to run builds for instrument data that has already vanished.  This allows us to potentially re-use the existing alignments (if they're available) to avoid referring back to the original instrument data.
It may lead to some more inscrutable errors from tools if in fact we do need the instrument data BAMs, but hopefully a real tiered disk architecture will soon end the need for our concern about explicit archiving!
Closes #1521.

Allow Running Builds with Missing Instrument Data BAMs

---

lib/perl/Genome/WorkflowBuilder/Command.pm
lib/perl/Genome/WorkflowBuilder/Detail/Operation.pm

This doesn't affect the operation of the workflow, and users don't really care about the limitations of the environment compared to Perl hashes.

Stop warning about undefined environment variables.

---

lib/perl/Genome/Model/RnaSeq.pm
lib/perl/Genome/Model/RnaSeq.t
lib/perl/Genome/Model/RnaSeq.t.d/workflow.xml

`Genome::Model::Build->start` was already converting the resulting workflow to `WorkflowBuilder` when starting the build, but now it uses it the whole time.  Another step on the road to removing `Workflow`!

Convert RnaSeq Workflow Generation to WorkflowBuilder.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Merged/CoverageStats/View/Coverage/Xml.pm
lib/perl/Genome/xsl/html/coverage/genome_model.xsl

The individual result will now only display the V2 metrics, and the set page will now have the toggle default to the `new` setting.

Make AlignmentSummaryV2 the default in Coverage Reports

---

lib/perl/Genome/InstrumentData/Command/Import/Basic_bam.t
lib/perl/Genome/InstrumentData/Command/Import/Basic_bam_downsample.t
lib/perl/Genome/InstrumentData/Command/Import/Basic_bam_multi_groups.t
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/SanitizeAndSplitBam.pm
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/SanitizeAndSplitBam.t

The importer was attempting to revcomp sequences, but only after the bit flag had been altered. This led to sequences not being correctly written.
In response to https://rt.gsc.wustl.edu/Ticket/Display.html?id=111023

InstDAta Import: Fix RevComp Bug

---

lib/perl/Genome/Config/AnalysisProject/SubjectMapping.pm

Otherwise the delete will fail due to the FK constraint.

Delete the tag bridges in advance of deleting the subject mapping.

---

lib/perl/Genome/Model/ClinSeq.pm
lib/perl/Genome/Model/ClinSeq/Command/MicroarrayCnv.pm
lib/perl/Genome/Model/ClinSeq/Command/MicroarrayCnv.t

Now that this command is part of the ClinSeq build process (#1392), we can't assume that the model will have a last_succeeded_build to work with.  Instead, let's use our current build to do the work.

ClinSeq MicroarrayCnv takes a Build

---

lib/perl/Genome/View/Resource/Html/js/app/genome_model_coverage_tables.js
lib/perl/Genome/xsl/html/coverage/genome_model.xsl

By having a separate table for each version, each datatable independently paginates and the export SWF buttons grab the proper set of data.

Use a template to draw the alignment summary table.

---

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML

RepeatMasker support was removed in #1549, which altered the headers of the SV output.  No data except for the headers `diff`ed between the current and proposed blessed builds.

Update blessed somatic-variation-short build to account for #1549.

---

lib/perl/Genome/Model-build_requested.t
lib/perl/Genome/Model.pm
lib/perl/Genome/Model/Build-multiple-model-inputs.t
lib/perl/Genome/Model/Build.pm
lib/perl/Genome/Model/Build/Command/AbandonAndQueue.t
lib/perl/Genome/Model/Build/Command/Queue.t
lib/perl/Genome/Model/Build/DeNovoAssembly/Allpaths.t
lib/perl/Genome/Model/Build/DeNovoAssembly/Soap.t
lib/perl/Genome/Model/Build/ImportedReferenceSequence-derived_from.t
lib/perl/Genome/Model/Build/ReferenceAlignment.t
lib/perl/Genome/Model/ClinSeq.t
lib/perl/Genome/Model/Command/Services/ListBuildQueue.t
lib/perl/Genome/Model/ImportedVariationList/Command/ImportVariants.pm
lib/perl/Genome/ProcessingProfile-example1.t

The long-awaited requirement!  A Model must belong to an Analysis Project (and one that's not Disabled at that!) in order to be built or queued for building.

Require an Analysis Project to run Builds.

---

etc/genome/spec/dev_mode.yaml
genome-webserver/solr/scripts/gcsearch_load_from_mailman.pl
lib/perl/Genome.pm
lib/perl/Genome/Model/Command/Services/WebApp/Main.psgi
lib/perl/Genome/Search.pm
lib/perl/Genome/Search.t
lib/perl/Genome/Site/TGI.pm
lib/perl/Genome/Wiki/Document.pm

This was previously used to switch between hard-coded server values in the code, but we are (or should be!) using config to set those server values directly instead.

Remove "dev_mode" configuration.

---

lib/perl/Genome/Model/Build/ReferenceSequence/Converter.pm

LiftOver might scramble up the regions as they've moved between references, but we expect a sorted file to come out of the converter.

Refseq Converter: Sort after lifting over.

---

lib/perl/Genome/Model/Tools/DetectVariants2/GatkSomaticIndel.t
lib/perl/Genome/Model/Tools/Vcf/Convert/Indel/GatkSomaticIndel.pm
lib/perl/Genome/Model/Tools/Vcf/Convert/Indel/GatkSomaticIndel.t

GatkSomaticIndel sometimes swaps the normal and tumor columns in its own vcf output that this vcf converter is based on. Aka, column 9 is not always for tumor. This fix replaces the hardcoded normal/tumor column index with a better way to secure the normal/tumor columns.

Make normal/tumor sample field real

---

lib/perl/Genome/WorkOrder.pm

(This class is still pointing directly into a LIMS table.  It ought to really be converted to a `Genome::Site::TGI`-ish class or else removed entirely.)

The estimate_id column has been dropped from the Work Order table.

---

lib/perl/Genome/Model/Tools/CopyNumber/Cnmops.pm

`bedtools intersect` seems to not be stable with regard to self-intersection.  It's adding duplicate rows to the resulting file, which causes trouble for our R script.

Don't bother intersecting this file with itself. Return the one copy.

---

lib/perl/Genome/Model/Tools/DetectVariants2/PindelRegion.t
lib/perl/Genome/Model/Tools/Vcf/Convert/Indel/PindelRegion.pm

Adding PASS to FT format field for somatic variants can preserve this pass status through vcf filter and joinx vcf-merge later.

Add FT format field to pindelRegion vcf

---

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML

All diff is caused by newly fixed GatkSomaticIndel vcf format (https://github.com/genome/genome/pull/1561)and the diff is fine. This PR is to update the blessed builds so Jenkins Genome-Model-Tests can pass.

Update blessed builds

---

lib/perl/Genome/Model/Tools/Vcf/Convert/Indel/Bed.pm

Thanks to @chrisamiller for discovering this issue!

Use position we calculated instead of printing start position from BED.

---

lib/perl/Genome/Site/TGI/CleTest.pm.yaml
lib/perl/Genome/Site/TGI/CleTest.t
lib/perl/Genome/VariantReporting/Command/Wrappers/ModelPair.pm

The current homo polymer list has homo polymers of min_length 6, which filters out some real indel variants. The new list has homo polymers of min_length 7 with about 4 million length_6 polymers removed. The indel counts of trio report using the new list look fine. Refer to https://jira.gsc.wustl.edu/browse/CI-191  Diff is expected for regression test.

Update homo_polymer list with min_length 7

---

lib/perl/Genome/Model/Tools/Sam/Flagstat.pm

In reviewing our QC metrics, I noticed that the denominator for calculating `reads_mapped_in_interchromosomal_pairs_percentage` is incorrect. Properly paired reads were being used as the denominator, but given that properly paired reads would exclude interchromosomal pairs then this seems incorrect.
This pull request changes the denominator to be all reads mapping in pairs.

change denominator for interchromosomal rate calculation

---

lib/perl/Genome/File/Vcf/Entry.pm
lib/perl/Genome/File/Vcf/Entry.t
lib/perl/Genome/Model/Tools/Vcf/AnnotateWithReadcounts.t
lib/perl/Genome/VariantReporting/Suite/BamReadcount/Expert.t

This PR is to fix the bug. This is causing $entry->sample_field not returned correctly if add_format_field first.

Reset _format_key_to_idx hash properly and avoid check with autovivified hash

---

bin/genome-env
lib/perl/Genome/VariantReporting/Suite/Joinx/Homopolymer/Expert.t

Currently CLE regression test is failing because the new homo_polymer feature list is not in test DB. This PR adds it into testDB.

Update test database

---

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML

The diff is from missing TCGA sample fields in vcf header, which is caused by turnning off the outdated OpenSSL TCGA web queries and disabling the TCGA compliance support. The commit is 1933bbaeb0cbf7bbebf11315ccbb9d628a77c14e for Genome/Model/Tools/Vcf/Convert/Base.pm on 07/25/2016. The vcf header for non-TCGA sample is still fine.

Bless new build for apipe-test-somatic-variation

---

lib/perl/Genome/Model/Tools/Vcf/CreateCrossSampleVcf/CreateCrossSampleVcfBase/Result.pm

We won't have the Command around if we load this from the database, which prevents us from `commit()`ing in contexts where one of these results has been loaded.
(I ran across this while trying to archive some of these results.  They might similarly be resistant to purging presently.)

CCSVCF Result: "command" property should be optional.

---

lib/perl/Genome/Model/Build/Command/DetermineError.pm

"Genome/Ptero/Wrapper.pm" catches exceptions to clean up and then re-`die()`s, so we should keep looking for the original error location instead.

Add a blacklist for locations from which to not report errors.

---

etc/genome/spec/log_dir.yaml

I believe nothing uses this, and it would be beneficial to improving GMS dockerization to remove it.

Remove old, unused "log_dir" configuration variable.

---

lib/perl/Genome/Model/Tools/Varscan/PullOneTwoBpIndels.t

This test broke when the absolute path to the file changed.
(I also updated the local existing FOF to point to the current path to expedite fixing this test in master, but this is a better long-term solution.)

PullOneTwoBpIndels test: Generate the FOF to pass to the tool.

---

etc/genome/spec/email_pipeline_noisy.yaml
lib/perl/Genome/Model/Tools/Picard.pm

There was only one place left using this, and it already sends mail somewhere else in addition to this configured address.
[This is in support of our current e-mail cleanup efforts.]

Remove "email_pipeline_noisy" config.

---

etc/genome/spec/lsf_queue_build_workflow.yaml

Support for `Workflow` is gone as of #1559, so this variable is no longer used by anything.

Remove old build workflow configuration.

---

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML

The diff is caused by recent addition of detailed.pass.vcf to DV2 output.

Update blessed build

---

lib/perl/Genome/Model/Tools/CopyNumber/CnView-fast.t
lib/perl/Genome/Model/Tools/CopyNumber/CnView-slow.t

The files in the hardcoded paths were recently relocated.  Rather than update the hardcoded paths, this now looks up the proper paths using `Genome::Db`.

Use the annotation DB instead of a hardcoded path for targets file.

---

lib/perl/Genome/xsl/html/coverage/genome_model.xsl

We need the datatables buttons to be toggled when performing the algorithm swap, so that only the appropriate set is visible.

Coverage Report: Use a wrapping <div> for the hiding. Apply dataTables to the <table>.

---

lib/perl/Genome/SoftwareResult.pm

Newer Perls provide this warning:
> Use of each() on hash after insertion without resetting hash iterator results in undefined behavior

Avoid using `each()` in loop where we insert into the hash.

---

etc/genome/spec/java_heapspace_picard.yaml
etc/genome/spec/java_permgen_picard.yaml
lib/perl/Genome/Model/Tools/Picard.pm

Occasionally CollectWgsMetrics likes to exceed the default Java heap space.

Make Java heap and permgen configurable for calling Picard.

---

lib/perl/Test/Builder.pm

This module really shouldn't be in the repository to begin with... but as long as we're supporting old systems it shall remain.

Test::Builder: Don't return before evaluating the entire expression.

---

lib/perl/Genome/Sys/LSF/JobIterator.pm

Perl 5.22 warns of an unescaped `{`. Seems like it was a quantifier gone wrong.  The history of this module is obscured, though.

Remove spurious whitespace in regex.

---

lib/perl/Genome/Model/Tools/Bwa/RunMem.pm

Otherwise we get no output on fragment data!

BWA-MEM: Only pass parameter for paired FASTQs if "-p" flag used.

---

lib/perl/Genome/Site/TGI/CleTest.pm.yaml
lib/perl/Genome/Site/TGI/CleTest.t

Currently CLE regression test is still failing because PindelRegion region list is not loaded in test DB. This PR is to add it to CleTest to make regression test pass.

Add PindelRegion region file feature list to CleTest

---

lib/perl/Genome/Model/ClinSeq/Command/Converge/SnvIndelReport.pm

Allow for the lookup/shorcut of the AnnotatedSnvsVcf result instead of relying on it as an input. This command can now be run standalone as long as a previous build succeeded at generating the result.
Please take a look @tmooney and @susannasiebert

SnvIndelReport standalone support

---

lib/perl/Genome/InstrumentData/Command/List.pm
lib/perl/Genome/Model/ClinSeq/Command/TestGenomeCommands.t.d/genome-instrument-data-list2.out

When the LIMS was calculating these, they were quick lookups since they came as instrument data properties.  Now that they're not, there's only the hacky "default_alignment_results" to get them.  The question doesn't really make sense in a world where alignment can be done any number of ways.

Exclude alignment metrics from default Solexa lister.

---

lib/perl/Genome/Disk/Volume.pm

The `is_mounted` method is premised that each mount path is automounted.  If a mount_path is a symlink, instead assume that it is part of a larger mount that already is mounted--someone should check that larger mount's path directly if they care.
(I'm not sure this is the best solution to this problem, but it seems to solve the problem of making allocations under the new scheme.)

Trust that symlinks are mounted.

---

lib/perl/Genome/Sys/LockProxy.pm

This should make it easier to find out what we're waiting on when something else has the lock.  This replaces the earlier pre-backend message that would output the entire contents of the file lock.  (Unlike the previous message, this message gets included even if we do get the lock immediately.)

Debug message for the resource when locking.

---

lib/perl/Genome/Sys/LockProxy.t

While testing #1632 I was briefly confounded by this test not loading my changes.  This makes it so running the test locally really uses the local codebase :smile:

Use above for loading Genome in LockProxy.t

---

lib/perl/Genome/Config/AnalysisProject/Command/TakeOwnership.pm
lib/perl/Genome/Config/AnalysisProject/Command/TakeOwnership.t
lib/perl/Genome/Config/AnalysisProject/Command/Uncomplete.pm
lib/perl/Genome/Config/AnalysisProject/Command/Uncomplete.t

* Only take non-CLE projects.
* Only "uncomplete" projects that you've created or taken.

New AnP Commands to "Take Ownership" or "Uncomplete" AnPs.

---

lib/perl/Genome/Command/PteroWorkflowMixin.pm

We will now display the "execute" attempt if the "shortcut" attempt errors out.  (Previously, the errored shortcut would be displayed even if the execute is running smoothly.)

Treat "errored" PTero status as a failure condition.

---

lib/perl/Genome/Model/Command/Report/GetDataset.t

The test model was removed as part of the deprecation of this model-type, so skip running the bulk of this test.

Eliminate testcase that depends on MC16s build.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Bwa.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Bwamem.pm
lib/perl/Genome/InstrumentData/AlignmentResult/BwamemStream.pm

Tests started failing here due to a change in the host string being returned in production.  This is likely to cause real alignment failures as well...

Remove all trailing slashes from host-groups... not just one!

---

lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalsePositiveVcfBase.pm

A `/` came up in a sample name, which was causing trouble!

Escape Sample Name Used as Filename in bam-readcounts

---

lib/perl/Genome/Model/Build/ClinSeq/FileAccessors.t
lib/perl/Genome/Model/ClinSeq/Command/Converge/AllEvents.t
lib/perl/Genome/Model/ClinSeq/Command/Converge/CancerRelevanceScore.t
lib/perl/Genome/Model/ClinSeq/Command/Converge/SnvIndelReport.t
lib/perl/Genome/Model/ClinSeq/Command/Converge/Stats.t
lib/perl/Genome/Model/ClinSeq/Command/SummarizeTier1SnvSupport.t

A bunch of tests were using production data, which has been removed.  This updates one of them to use test data and disables the rest.

Fix/Disable ClinSeq tests using purged data

---

lib/perl/Genome/Config/AnalysisProject/Command/Create.pm
lib/perl/Genome/Config/AnalysisProject/Command/Create.t
lib/perl/Genome/Config/AnalysisProject/Command/Release.pm
lib/perl/Genome/Config/AnalysisProject/Command/Release.t

* Rename the "production" option in create to "prod-builder".
* Only allow an Analysis Project to be released if it has an environment configuration specified.
This PR doesn't enforce the contents of the environment configuration in any way.

Analysis Projects Require Environment Specifications

---

lib/perl/Genome/Model/SomaticValidation/Command/AlignmentStatsSummary.pm
lib/perl/Genome/Model/SomaticValidation/Command/AlignmentStatsSummary.t

This PR is to get error_rate from Genome::Qc::Result metrics if filt_error_rate_avg of instrument data is not available.

Try to get error_rate from Genome::Qc::Result metrics

---

lib/perl/Genome/Disk/Group.pm
lib/perl/Genome/Site/TGI/SiteLib/Genome/Disk/Group/Validate/GenomeDiskGroups.pm

There is currently a problem where loading a disk group reads all of the config, which triggers an error when that config is unset.  Unfortunately that config is read while trying to set a new config file.
Either of these changes would solve the problem: the first, by no longer requiring that a disk group "validates" before loading it; the second, by ignoring errors for unset configurations.

Stop Validating Disk Groups

---

lib/perl/Genome/Model/Tools/Base.pm
lib/perl/Genome/Model/Tools/Base.t
lib/perl/Genome/Model/Tools/Manta/Base.pm
lib/perl/Genome/Model/Tools/Manta/Run.pm
lib/perl/Genome/Model/Tools/Sambamba.pm
lib/perl/Genome/Model/Tools/Sambamba/Base.pm
lib/perl/Genome/Model/Tools/Sambamba/Sort.pm

Refactor Manta to use a base tool class and implement a new tool tree for Sambamba including a basic implementation of the sort command.

Base Tool Class and Sambamba sort

---

lib/perl/Genome/Sys/LSF/bsub.pm

Idea borrowed from `Genome::ConfigValidator::LSFQueue`.  That module cannot "use Genome;" so can't be changed to refer to this version instead.
Why change this?  The old version is causing segfaults sometimes.

Use simpler means of validating LSF queue.

---

lib/perl/Genome/Model/SomaticValidation/Command/AlignmentStatsSummary.pm
lib/perl/Genome/Model/SomaticValidation/Command/AlignmentStatsSummary.t

PF_MISMATCH_RATE from picard is the rate not percentage. read_1/2_pct_mismatch = PF_MISMATCH_RATE * 100.

Fix an error_rate bug

---

lib/perl/Genome/Model/Tools/Annotate/AddRsid.pm
lib/perl/Genome/Model/Tools/Validation/ProcessSomaticValidation.pm

Allows for the use of both older-style dbSNP VCFs that use the GMAF convention and newer ones with CAF convention. 
In both cases, we are now also ignoring indels. This code was never designed to annotate indels. 
The older versions also often provide the incorrect allele frequency because the minor allele is actually the reference allele and only 1 AF is provided in GMAF-style VCFs. It is definitely advisable to use the CAF versions. Just a warning in case anyone else ever sees this.

Fixing problems with rsID annotation code

---

lib/perl/Genome/Model/Build/ReferenceSequence.pm

Say, for example, someone sets this to `/dev/null` to turn off caching.  It'd be better if it didn't try to `mkdir /dev/null/foo`!

For the local cache to be usable, it must be a directory.

---

lib/perl/Genome/Model/Tools/Annotate/AddRsid.pm

The downstream steps expect GMAFs to be stored as `GMAF=$value` in the AddRsid bed file output.

Add "GMAF=" before value when parsing CAFs

---

lib/perl/Genome/Model/Tools/DetectVariants2/Breakdancer.t

The CTX test data was deleted.  Breakdancer still gets tested as part of model tests.

Skip breakdancer CTX unit test.

---

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML

The old samstat HTML for the tumor RnaSeq result is no longer available.  This updates the expected case to not include it.

Update blessed ClinSeq test build.

---

lib/perl/Genome/Disk/Detail/Allocation/Creator.pm
lib/perl/Genome/InstrumentData/AlignmentResult.pm
lib/perl/Genome/InstrumentData/IntermediateAlignmentResult.pm

The check for avaialble disk was finding volumes that were not available to be used for allocations.  To prevent this, use the same method that creating an allocation uses.

Use the same criteria for checking available disk as would to allocate.

---

lib/perl/Genome/Model/Build.pm
lib/perl/Genome/Model/Build/SingleSampleGenotype.pm
lib/perl/Genome/Model/SingleSampleGenotype/Command/SetTestName.pm
lib/perl/Genome/SoftwareResult/Command/SetTestName.pm

- a command to set test names on all SSG results (excluding aligner index, etc.)
- wait to abandon builds until we have a complete list and test names are set

Set SSG Test Names

---

lib/perl/Genome/Disk/Detail/Allocation/Mover.pm

When we moved the allocation into place from the shadow allocation, we adopted its group_subdirectory, so be sure to save it into ourself!

Update the group_subdirectory to match our new location.

---

bin/genome-env

This stops the `10:09:17 Can't locate Workflow.pm in @INC` messages in the test logs.

Remove "Workflow" from comments and output for version check.

---

lib/perl/Genome/Carp-mimic.t
lib/perl/Genome/Command/Crud.t
lib/perl/Genome/ConfigValidator/Numeric.t
lib/perl/Genome/FeatureList.t
lib/perl/Genome/InstrumentData/AlignmentResult/Bsmap.pm
lib/perl/Genome/InstrumentData/Imported/View/Solr/Xml.t
lib/perl/Genome/InstrumentData/Solexa/View/Solr/Xml.t
lib/perl/Genome/Library/View/Solr/Xml.t
lib/perl/Genome/Logger.t
lib/perl/Genome/Model/Build/View/Solr/Xml.t
lib/perl/Genome/Model/View/Solr/Xml.t
lib/perl/Genome/ModelGroup/View/Solr/Xml.t
lib/perl/Genome/Role/Logger.pm
lib/perl/Genome/Sample/View/Solr/Xml.t

* Handle newer versions of `Log::Dispatch`, `Carp`, and `Scalar::Util`.
* More consistent test results by using `above` and setting no commit.
* Looser matching of expected help text in test.

Compatibility fixes for running with newer versions of third-party modules.

---

lib/perl/Genome/InstrumentData/IntermediateAlignmentResult.pm

decrease intermediate alignmenet disk check from 20x to 2x.
This is a followup to #1682

Intermediate Alignment Disk Check

---

lib/perl/Genome/Model/Tools/DetectVariants2/PindelRegion.t
lib/perl/Genome/Model/Tools/Vcf/Convert/Indel/PindelRegion.pm

Currently pindel2vcf has default 0.2 for --het-cutoff (genotype 0/1), which is too stringent for pindel-region detection sensitivity. We decided that GT should be set to 0/1 if VAF >= 0.01 and var_read_cout >= 5. Refer to CI-217.

Fix genotype for pindelRegion vcf

---

lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalsePositiveVcf.t
lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalsePositiveVcfDenovo.t
lib/perl/Genome/Model/Tools/DetectVariants2/Filter/PolymuttDenovo.t

Here are another few tests where test data was recently purged.

Disable DV2 filter test cases dependent on purged test data.

---

lib/perl/Genome/Model.pm

The `Scope::Guard` was preventing the message from `Carp::confess` from making it to the user.

Stop swallowing errors in Model create.

---

lib/perl/Genome/Disk/Allocation.pm
lib/perl/Genome/Disk/Detail/Allocation/Archiver.pm
lib/perl/Genome/Disk/Detail/Allocation/Unarchiver.pm

Now that there's a default docker specification, we have to explicitly exclude it here.

Don't use docker for archive processes!

---

lib/perl/Genome/Model/Tools/DetectVariants2/Detector.pm
lib/perl/Genome/Model/Tools/DetectVariants2/Dispatcher.pm
lib/perl/Genome/Model/Tools/DetectVariants2/Utilities.pm
lib/perl/Genome/Ptero/Wrapper.pm
lib/perl/Genome/Site/TGI/Extension/Sys.pm
lib/perl/Genome/SoftwareResult.pm
lib/perl/Genome/Sys.pm

This is an attempt to keep `/vol/` paths out of our local database by un-resolving the `/gscmnt/` symlinks.

Site: Avoid using `/vol/` paths as canonical.

---

lib/perl/Genome/Model/Command/Admin/PurgeSoftwareResultsFromAnalysisProject.pm

The purge command was wasting a lot of time re-examining SRs it had already processed when it was used multiple times by the project.

Only process each SR once when purging an AnP.

---

lib/perl/Genome/Sys.pm

This is in a further effort to avoid `/vol/` paths using the feature introduced in #1700.

Use Genome::Sys->abs_path for DB and snapshot locations.

---

etc/genome/spec/lsf_resource_methratio.yaml
lib/perl/Genome/Model/Tools/Bsmap/MethRatio.pm

Running too many of these is implicated in performance problems in the cluster.

Specify a job group to limit concurrent MethRatio processes.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm

Nothing uses this...yet.  It creates feature-parity with the proposed filetype field for external merged results in #1719.

Support the notion of alternative filetypes for alignment files.

---

lib/perl/Genome/InstrumentData/AlignmentResult/PerLaneTophat.pm

Ideally this would be configurable. For now, increase to 64GB of RAM as read trimming will become more common with longer read RNA-seq data.

Increate PerLaneTophat LSF RAM to 64GB from 32GB

---

lib/perl/Genome/Model/Tools/Varscan/ProcessValidation.t

As best I can tell, this is copying a file and then diffing that file against its copy.  This PR skips that comparison.  Alternatively, we could generate a new proper file for comparison and then start diffing against that?

Remove strange file copy in process-validation test.

---

lib/perl/Genome/Disk/Detail/Allocation/Mover.pm

This error is reported before we would've updated the allocation object itself to the new location, so we can't rely on it to get the destination path.

Disk Allocation move: Report correct new path in error message.

---

lib/perl/Genome/Config/AnalysisProject/SubjectMapping/Command/Predict/SomaticValidation.pm

The error messages were failing because some `Set::Scalar` operations convert any object references inside of them into strings like `Genome::Sample(147899968)`.  Now the sets will hold the sample IDs and we can get back the objects as needed.
(This addresses CIS-61.)

Fix error messages in SomVal SubjectMapping prediction.

---

lib/perl/Genome/Model/CwlPipeline.pm
lib/perl/Genome/Model/CwlPipeline.t
lib/perl/Genome/Model/CwlPipeline/Command/Input.pm
lib/perl/Genome/Model/CwlPipeline/Command/Input/Add.pm
lib/perl/Genome/Model/CwlPipeline/Command/Input/Add.t
lib/perl/Genome/Model/CwlPipeline/Command/Input/List.pm
lib/perl/Genome/Model/CwlPipeline/Command/Input/Remove.pm
lib/perl/Genome/Model/CwlPipeline/Command/Input/Remove.t
lib/perl/Genome/Model/CwlPipeline/Command/Restart.pm
lib/perl/Genome/Model/CwlPipeline/Command/Restart.t
lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
lib/perl/Genome/ProcessingProfile/Command/Create/CwlPipeline.pm
lib/perl/Genome/ProcessingProfile/Command/Create/CwlPipeline.t
lib/perl/Genome/Sys/LSF/ResourceParser.pm
lib/perl/Genome/Test/Factory/Model/CwlPipeline.pm
lib/perl/Genome/Test/Factory/ProcessingProfile/CwlPipeline.pm

Here's what one version of a CWL model type could look like.  It needs a few more commands (convenient ways to define PPs and models) to be useful, and the YAML generation needs some fleshing out.  But this combined with relevant environment variables could theoretically be used to run a CWL pipeline tracked as a build within the GMS.

Draft CWL Pipeline type.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Command/BamToCram.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Command/ConvertBase.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Command/CramToBam.pm

Here are a couple commands for converting merged alignment results between BAM and CRAM format.  This still needs to be tested more before being widely used!
Potential Shortcomings:
* There's no automatic CRAM => BAM reconversion for converted things if the result is called in a situation that requires BAM.
* It might be nice to be more thorough with verifying the transformation.  This could incorporate a flagstat comparison at the cost of spinning up a second/third LSF job.

First version of BAM <=> CRAM conversion for Merged AlignmentResults

---

lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert.pm
lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/BamToCram.pm
lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/Base.pm
lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/CramToBam.pm

There are two similar command directories, but only one of them is included when running `genome`.

Move new BAM <=> CRAM conversion commands for command-line use.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Merged/Speedseq.pm
lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/BamToCram.pm
lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/Base.pm
lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/CramToBam.pm

Since Speedseq doesn't use the normal merged alignment class, these were failing to be found (and wouldn't have been able to store the format if they were).

Support "Speedseq" merged alignments in format converters.

---

lib/perl/Genome/Site/TGI/Synchronize/Classes/LimsBase.pm

The LIMS system has started storing empty strings in columns sometimes when they mean `NULL`, so treat them the same.

Treat empty strings like undef values in LIMS objects.

---

lib/perl/Genome/Site/TGI/Synchronize/Classes/IndexIllumina.pm

This cast plus the default sorting leads to a very slow query.

Don't cast analysis_id to text.

---

lib/perl/Genome/Site/TGI/Command/ImportDataForWorkOrder.pm

This uses the same backing classes as the existing synchronization cron.  It currently won't work right if the `source` is not an individual, and it trusts the user that the WO in question is ready for importation.
In a future version, the backing classes can be changed to use the API for access to the data instead of going directly through the database.

Command to manually trigger the import of WO data from the LIMS.

---

lib/perl/Genome/Site/TGI/Synchronize/Classes/InstrumentDataAnalysisProjectBridge.pm

This removes a bunch of casts of numbers to text and joins to each table individually instead of operating on the union.

Synch: SQL refactor for AnP bridge class

---

lib/perl/Genome/Site/TGI/Synchronize/Classes/InstrumentDataAnalysisProjectBridge.pm

This one really holds non-numeric data, so should not have changed it in b0a14a85.

Change columntype for AnP ID back to text.

---

lib/perl/Genome/Sys.pm

We've been encountering some failures where this connection was left open and then closed by the remote server.

Also disconnect the OLTP handle when disconnecting for long-running ops.

---

lib/perl/Genome/Site/TGI/Command/ImportDataForWorkOrder.pm
lib/perl/Genome/Site/TGI/Synchronize/Classes/Genotyping.pm

The first version of this command worked to import instrument data assuming the synchronization cron was otherwise running to bring across other associations.  This adds features to make the data import more complete independent of synching.

Import Genotype Data, AnP links, and Sample links for Work Order.

---

lib/perl/Genome/Site/TGI/Command/DiffLimsAndGenome.pm
lib/perl/Genome/Site/TGI/Command/SyncLimsAndGenome.pm
lib/perl/Genome/Site/TGI/Synchronize/Classes/Dictionary.pm

This PR includes a few changes to stop loading as much unnecessary data during synch.  Additionally, it stops synching `LimsProjectInstrumentData` for now, as this table cannot be examined in a reasonable timeframe for the operation.

More Efficient Synch; Temporarily Stop LimsProjectInstrumentData Synch

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

It's not worth the additional disk usage to use by default.

Stop using cwltoil's --stats option.

---

lib/perl/Genome/Model/Build/Command/View.pm
lib/perl/Genome/Model/CwlPipeline/Command/Restart.pm

* Handle multiple processes when viewing builds.
* Come up with a unique workflow name upon restart.

Fixes for restarting CwlPipeline builds

---

lib/perl/Genome/Model/Tools/DetectVariants2/Dispatcher.pm

This is an alternate to #1761.  It has more parallels to the `_create_bed_from_vcf` in the dispatcher. It also allows the final pass tool to remain unaware of the complexities of samples, since it is only passed a string.

Pass the corrected sample name to the FinalPassOnly tool.

---

lib/perl/Genome/Disk/Detail/Allocation/Creator.pm

This will hopefully make it easier to track down what went wrong in cases like CIS-148.

Use the ordinary "debug_message" so they appear in the normal logs.

---

lib/perl/Genome/Model/Build.pm
lib/perl/Genome/Model/Build/Command/Purge.pm

It grabs a similar list of results to the `genome model build move-allocations` command, but only removes found results if they have no other active users.

New command to purge allocations for a build.

---

lib/perl/Genome/Model/Tools/Pindel/ProcessPindelReads.pm

It's fairly common for chromosome names to have `|` in them, so we shouldn't blindly pass them along to shells!

Properly handle chromosome names with shell metacharacters in ProcessPindelReads

---

lib/perl/Genome/Model/Command/Report/Mail.pm
lib/perl/Genome/Model/Tools/ViromeScreening.pm
lib/perl/Genome/Report/Email.pm

The right answer in our environment changed recently, but these spots weren't properly using configuration.

Don't hardcode the SMTP server location.

---

lib/perl/Genome/Db/Ensembl/Gnomad.pm

This version doesn't include a command interface or accessors for the file, but it does successfully download the files and store them in an allocation.  (Current example is `/gscmnt/gc2560/core/model_data/genome-db-ensembl-gnomad/2dd4b53431674786b760adad60a29273`.)

First version of a gnomad file importer.

---

lib/perl/Genome/Model/Build.pm

If other builds in the AnP are still using the result, they'll still be in the active users.  This does mean a result used by two AnPs still cannot be purged via this mechanism.

Ignore our own AnP when deciding if a result is still in use.

---

lib/perl/Genome/Site/TGI/Command/ImportDataForWorkOrder.pm

The normal synch process loads PIDFAs to find the file paths, but those are not guaranteed to exist for these data.
An alternative approach might be to create a new synch class with a query that attempts to capture the relevant information.  For now, disabling genotype import fixes importing other data for work orders with genotype information.

Disable importing genotype data in `import-data-for-work-order`.

---

lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/Base.pm

The conversion process may not produce an identical file, so we can't trust the existing index to still be valid.
Closes #1773.

(Re)index the converted alignment file.

---

lib/perl/Genome/Config/AnalysisProject/Command/AddInstrumentData.pm
lib/perl/Genome/Site/TGI/Command/ImportDataForWorkOrder.pm

This is a shortcut to avoid looking up all the instrument data via project parts after import.

Option to Specify an AnP When Importing Work Order

---

lib/perl/Genome/Model/Tools/Dgidb/Base.pm

The old URL is returning 308 redirects, which this tool reports as errors.

Use new canonical DGIdb.org domain.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm

That way the ".bam" file is promoted before its accessory files.

Sort the files to be promoted.

---

lib/perl/Genome/InstrumentData/AlignedBamResult.pm

This is to handle that some subclasses can "convert" now and store the file in other formats.

AlignedBamResult: Try delegating to get the bam_path first.

---

lib/perl/Genome/Model/Build/RnaSeq.pm

This codepath is only used by processing profiles that perform Tophat 1 alignments.

Fill in `result_users` hash before getting/creating alignments

---

lib/perl/Genome/Model/Build/RnaSeq.pm

The param is called "users" not "result_users" in results themselves.

---

lib/perl/Genome/Model/Tools/DetectVariants2/Result/Combine/LqUnion.t

This would still be better without relying on real data!  This should hopefully be sufficient to get tests to pass again, though!

Hackily replace deleted test data with some that's still around.

---

lib/perl/Genome/Model/Build/ClinSeq.pm

This fixes `genome model build move-allocations` for ClinSeq builds.

Add ClinSeq's SR classes.

---

lib/perl/Genome/Model/Build/GenotypeMicroarray.pm

This fixes `genome model build move-allocations` for GenotypeMicroarray builds.

Add GenotypeMicroarray's SR classes.

---

lib/perl/Genome/InstrumentData/Command/Import/Basic_fastq.t
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder.pm
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder/Fastq.pm
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder/Fastq.xml
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.pm
lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.t
lib/perl/Genome/Sys.pm

Remove unarchive of FASTQ to avoid storing entire contents of the file in RMA.
Use the latest version of Picard for FastqToSam to ensure reading gzipped files works correctly. If I recall correctly older versions of Picard had issues with gzipped inputs. I'm sure this could be standardized for all Picard commands, but for now this seems to work.

FASTQ Importer with less RAM

---

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML

The old genotype data these tests used has been purged, and the corresponding model was old enough that we don't run them that way anymore.

Update RefAlign test builds for run without genotype data.

---

lib/perl/Genome/Model/Tools/Picard/ConcatenateMetricsFiles.t

If the test is run as, e.g., "./ConcatenateMetricFiles.t", the data directory would have the "./" but the files written out would not, thwarting the replace in the comparison.

Canonicalize the data path.

---

lib/perl/Genome/Disk/Detail/Allocation/Creator.pm

The current logging tells us how big the request was that failed, but often the state of the volumes has changed to where the request seems fulfillable.  This will hopefully help capture how much space pressure is being felt.

Add debug message with current stats when volume too full.

---

lib/perl/Genome/Model/Build/Command/MoveAllocations.pm

This command can't move them, which may be surprising to the user!

Warn about build data directories that lack allocations.

---

lib/perl/Genome/Config/AnalysisProject.pm
lib/perl/Genome/Model/Build/Command/MoveAllocations.pm
lib/perl/Genome/Model/Build/Command/Start.pm

This encapsulates the logic for running code in the environment of an Analysis Project.

Add `set_env` to Analysis Projects

---

lib/perl/Genome/Model/Build/Command/MoveAllocations.pm

Although one can create a null `Set::Scalar` which can have `delete()` called on it, the `difference()` method of `Set::Scalar` returns a special subclass, `Set::Scalar::Null`, that doesn't have `delete()` defined.  This avoids this issue by skipping the deletion if the set is already null.  (In that case, there's nothing to delete, anyway!)

Avoid calling delete() on a Set::Scalar::Null.

---

lib/perl/Genome/Model/Build.pm
lib/perl/Genome/Model/Build.t

We've been manually sweeping these later, but might as well take care of it right away!

Build `abandon()` purges the Build's Allocation(s)

---

lib/perl/Genome/Model.pm
lib/perl/Genome/Model/CwlPipeline.pm
lib/perl/Genome/Model/CwlPipeline.t
lib/perl/Genome/ProcessingProfile/Command/Create/CwlPipeline.pm

Since CwlPipeline encompasses many different workflows, it is more common to have multiple models per subject.  Having them named "cwl_pipeline-1" through "cwl_pipeline-6" is less than ideal, so this provides a way to distinguish them based on the workflows they run.

Better CwlPipeline model naming.

---

lib/perl/Genome/InstrumentData/Solexa/Command.pm

This always has an initial value so cannot be updated due to the `only_if_null` restriction on solexa updates.  The generic instrument-data updater can be used to modify this value.

Remove "ignored" from solexa update tree.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

This would reduce disk usage until we can get to a better solution for storing results of individual steps.

Remove intermediate output directories after CwlPipeline run.

---

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML

Files are being moved, so the paths in the IGV XML are changing.  (This seems likely to be a recurring issue for awhile as data is migrated.)

Update blessed clinseq-wer build.

---

lib/perl/Genome/Model/Build/RunsDV2.pm

These are currently getting left behind by `genome model build move-allocations`.

Add UnionCnv to list of DV2 results that should get moved.

---

lib/perl/Genome/Model/Build/Command/MoveAllocations.pm

Some builds never had data directories to begin with.

Only check for directory existence if we got a path back.

---

lib/perl/Genome/Model/Build/SomaticValidation.pm

These were getting skipped when doing disk moves.

Add IdentifyDnpResult as a SomaticValidation result class.

---

lib/perl/Genome/Model/CwlPipeline.pm

This was failing when given `0` as an input value.

Fixes for CwlPipeline Input Processing

---

lib/perl/Genome/Site/TGI/Synchronize/Classes/Dictionary.pm
lib/perl/Genome/Site/TGI/Synchronize/Classes/Dictionary.t

~It can still be imported as needed via the import-data-for-work-order command.~ It won't be able to be imported anymore without manual intervention.

Stop synching genotype data.

---

lib/perl/Genome/FeatureList/Command/DumpIntervalList.pm
lib/perl/Genome/FeatureList/Command/DumpIntervalList.t
lib/perl/Genome/FeatureList/IntervalList.pm

New pipelines tend to need interval lists, so this is intended as a mechanism for generating them for the target region sets for instrument data.

New SR and Command for getting IntervalLists from FeatureLists

---

lib/perl/Genome/Model/Build/Process.pm
lib/perl/Genome/Model/CwlPipeline/Command/Restart.pm
lib/perl/Genome/Model/CwlPipeline/Command/Restart.t

Inspired by #1826.
The one downside of this approach is old builds/processes won't be able to display their workflows anymore, since the name doesn't match. Alternatives might include storing the name in the database or adding some date logic to decide which name to generate... but those are a lot more complex solutions to the problem.

More build restart fixes

---

lib/perl/Genome/Site/TGI/Command/ImportDataForWorkOrder.pm

The `@data` passed in here is not the Genome object but the synch object, so we need to look up the Genome entitiy for the add command.

Fix for assigning new instrument data to specified AnP.

---

lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/BamToCram.pm
lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/Base.pm
lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/CramToBam.pm

This was reallocating while both the BAM and CRAM were present.  That's very conservative!  But also somewhat defeats the purpose of this converter :smile:

Unlink the old file before reallocating.

---

lib/perl/Genome/Model/Build.pm

A build could have multiple processes (and workflows) since it can be restarted.  For most purposes (like `genome model build stop`) the most recent process is the correct one to consider.

Look for the latest workflow or LSF job.

---

lib/perl/Genome/FeatureList/Command/DumpIntervalList.pm
lib/perl/Genome/FeatureList/IntervalList.pm
lib/perl/Genome/Model/Build/ReferenceSequence/ConvertedBedResult.pm

We've decided to include `ConvertedBedResult`s in the set of things that are "core".

BED-related results should use `disk_group_references`.

---

lib/perl/Genome/Model/CwlPipeline/Command.pm
lib/perl/Genome/Model/CwlPipeline/Command/PrepForTransfer.pm
lib/perl/Genome/Model/CwlPipeline/Command/Restart.pm

* Make `builds` a positional parameter when useful.
* Add the base of the command tree so tab-completion can find these commands and they appear in help.

`genome model cwl-pipeline` usability improvements

---

lib/perl/Genome/Model/Build/DifferentialExpression.pm

This build type didn't get SoftwareResults added.

Add empty _disk_usage_result_subclass_names for DifferentialExpression

---

lib/perl/Genome/Config/AnalysisProject/Command/ShowConfig.pm

Tags can be the sole factor that prevents a particular configuration from matching, so it'd be helpful to offer a bit more visibility.

Include the tag name in the default AnP config lister.

---

lib/perl/Genome/Site/TGI/Command/ImportBamFromLims.pm
lib/perl/Genome/Sys.pm

This command has only been tested under a `xenial`-based environment.  It almost certainly doesn't work with older systems, thanks to the fancy ACLs in place in the new archive system.

Command for importing LIMS BAMs from the new archive system.

---

lib/perl/Genome/Config/Profile.pm
lib/perl/Genome/Config/Profile_input_data.t
lib/perl/Genome/Model/CwlPipeline.pm

This allows configured model inputs to be dynamically determined.  Even if those inputs aren't used by the build process, this also facilitates subsetting models by particular instrument data properties.  (Read: "You can configure per-library models." :smile:)

Config: Support `input_data` within `instrument_data_properties`

---

lib/perl/Genome/Model/ClinSeq/Command/Converge/DgidbCounts.t
lib/perl/Genome/Model/ClinSeq/Command/Converge/DgidbGenes.t
lib/perl/Genome/Model/ClinSeq/Command/GenerateSciclonePlots.t
lib/perl/Genome/Model/Tools/DetectVariants2/Result/Combine/LqUnion.t
lib/perl/Genome/Sys.pm

PR #1849 broke a feature of `rsync_directory` used by `PerLaneTophat` results.  This fixes that oversight and disables some tests that depend on test build data that has been purged.

Fix `rsync_directory` and disable some broken tests.

---

lib/perl/Genome/Model/View/Solr/Xml.pm

In a recent meeting there was a comment that all CWL models were being lumped into `other`.  This splits them out into their own categories or at least highlights they are CWL models.

Surface different CWL pipeline types in Solr search.

---

lib/perl/Genome/Site/TGI/Synchronize/Classes/IndexIllumina.pm

Calculated + constant, so it only finds the value once and otherwise treats it like a UR object property as it was before.  This fixes tests (and possibly real code :) ) that expected it to be a property.
This should resolve the issues introduced by merging #1843.

Make "bam_path" a property again.

---

lib/perl/Genome/Site/TGI/Command/ImportBamFromLims.pm

The LIMS code falls into legacy copies of the code if they are left cluttering the environment.

Set envrionment variables to get a cleaner environment.

---

lib/perl/Genome/Site/TGI/Synchronize/Classes/IndexIllumina.pm

This fixes the errors recently seen in the synch cron.

Make sure $self gets passed to _resolve_bam_path.

---

.test-tracker.conf

In order to launch the test-tracker in a world where interactive LSF jobs can't be nested, this will need to instead rely upon one of the versions that uses the log directory.

Update lsf_log_dir for test-tracker configuration.

---

lib/perl/Genome/Db/Ensembl/Command/Run/Vep.t
lib/perl/Genome/Model/Tools/Gatk/IndelRealigner.t
lib/perl/Genome/Model/Tools/Validation/LongIndelsGenerateMergedAssemblies.t
lib/perl/Genome/Model/Tools/Varscan/PullOneTwoBpIndels.t

Most of these paths were changed long ago, but we recently disabled the symlinks.  The database has the updated value, so look at it!

Find the reference FASTA via a database lookup instead of hardcoding.

---

lib/perl/Genome/Model/ImportedReferenceSequence.t
lib/perl/Genome/Model/Tools/RefCov/ExomeCapture.t
lib/perl/Genome/Model/Tools/RefCov/WholeGenome.t

More bad paths left hanging out in tests!

Remove hardcoded references to `gc4096`.

---

lib/perl/Genome/Model/Build/CwlPipeline/InputProcessor.pm
lib/perl/Genome/Model/Build/CwlPipeline/InputProcessor.t

This eliminates a lot of the copy+pasting between processing scripts.  For basic inputs, it eliminates most of the code from the script in favor of a class declaration.  Here's an example `process_inputs.pl` when no extra processing is required:
```perl
#!/usr/bin/env genome-perl
use strict;
use warnings;
use above 'Genome';
use YAML::XS;
my $build_id = $ARGV[0]
or die 'no build id';
my $build = Genome::Model::Build->get($build_id)
or die 'no build for id';
{
package InputProcessor;
class InputProcessor {
is => 'Genome::Model::Build::CwlPipeline::InputProcessor',
has_simple_input => [
alpha => { input_type => 'Text' },
bravo => { input_type => 'Text' },
charlie => { input_type => 'Text' },
first => { input_type => 'Number' },
second => { input_type => 'Number' },
third => { input_type => …
```

Helper class for processing inputs in `process_inputs.pl`.

---

lib/perl/Genome/Model/Tools/Sam/Pileup.t
lib/perl/Genome/Model/Tools/Sam/Readcount.t

It's a little bit silly to even worry about a real path here at all... maybe these tests should use a dummy path under the test's control.

Don't match on the absolute path to the reference.

---

lib/perl/Genome/Model/Tools/LiftOver.pm

I could imagine expanding this system to support many other chain files we have, but for now this at least works right.  (I could also see removing the shortcuts and always requiring a chain file, too... how
often do we need to convert to hg18 these days?)

Look up the chain files instead of using hardcoded paths.

---

lib/perl/Genome/Model/Tools/Transcriptome/ErccMapUnaligned.pm

The previously listed defaults are no longer valid paths.  In the spirit of not hardcoding reference-based defaults, these are now merely examples.
Closes #1882.

Demote defaults to example values; update paths.

---

lib/perl/Genome/Model/CwlPipeline.pm

This change will be most visible in the name of the log file generated for the run step.

Now that multiple CWL Runners are implemented, give the workflow step a generic name.

---

lib/perl/Genome/Cromwell.pm
lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

This disables SSL certificate validation when connecting to the Cromwell server!  One alternative solution would be to add a CA next to the keystore file we're pointing Java to, but this is expedient and should be fine on a trusted network...

Some fixes for staging the final outputs from Cromwell.

---

lib/perl/Genome/Site/TGI/Command/ImportBamFromLims.pm

* Can now be used to copy BAMs from either active or archived LIMS locations.
* Can now be used to import BAMs that were never previously located by the system.
* Some enhancements to increase chances of success in various environments.

Make the `import-bam-from-lims` command apply to more situations

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

This was the advice provided in:
https://gatkforums.broadinstitute.org/gatk/discussion/12330/call-catching-cromwell-exhausts-all-connection-to-mysqld

Restrict the number of DB connections for a single Cromwell run.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

Slick will automatically limit connections based on the thread count but not vice versa.  Therefore to get sane numbers let's set the thread count instead.

Limit threads instead of connections.

---

lib/perl/Genome/Disk/Allocation-move.t
lib/perl/Genome/Disk/Allocation-resolve_allocation_path.t
lib/perl/Genome/Disk/Allocation.t
lib/perl/Genome/Disk/Allocation/t-lib/GenomeDiskAllocationCommon.pm
lib/perl/Genome/Disk/Allocation/t-lib/GenomeDiskAllocationTest.pm
lib/perl/Genome/Disk/Assignment.pm
lib/perl/Genome/Disk/Command/Allocation/Import.t
lib/perl/Genome/Disk/Command/Group/List.pm
lib/perl/Genome/Disk/Group.pm
lib/perl/Genome/Disk/Group/View/SearchResult/Xml.pm
lib/perl/Genome/Disk/Volume.pm
lib/perl/Genome/Disk/Volume/View/SearchResult/Xml.pm
lib/perl/Genome/Disk/Volume/View/Status/Xml.pm
lib/perl/Genome/Site/TGI/Synchronize/Classes/Dictionary.pm
lib/perl/Genome/Site/TGI/Synchronize/Classes/Dictionary.t
lib/perl/Genome/Site/TGI/Synchronize/Classes/DiskAssignment.pm
lib/perl/Genome/Site/TGI/Synchronize/Classes/DiskGroup.pm
lib/perl/Genome/Site/TGI/Synchronize/Classes/DiskVolume.pm
lib/perl/Genome/xsl/html/search-result/genome_disk_volume.xsl

In preparation for the LIMS changing how they manage disk space, use our own copies of the tables so we can manage this independently. The DB already had tables created long ago, but we had never populated them until now.

Use Local `disk.` Tables

---

lib/perl/Genome/Sys/Command/Search/Index.pm

Adds items from the queue up to the specified maximum.  (Contrast with the "queued" option that processes everything.)
There are issues with using the daemon in our current setup, so this allows a processing batch to be scheduled regularly instead.

Add batch mode to search indexer.

---

lib/perl/Genome/Config/Profile.pm

When using tags to distinguish between otherwise matching configurations to limit to certain subject mappings, this will occasionally return no result for a given config.  For now, let's optimsitically assume that we should always get at least one match for a model type, even though it's possible even this assumption is not valid either.

Allow individual configs for a model type to mismatch.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

When moving symlinks, their targets may or may not exist depending if
what they point to already got moved. We need to faithfully relocate
them in either circumstance, so verifying readability is bad.

Use lower-level `move` for staging results.

---

etc/genome/spec/lsf_resource_cwl_runner.yaml
lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

We've encountered some workflows where Cromwell needs more than the default amount to survive pre-processing, but it's probably better to only request more memory if we really need it.  (This lets us configure it on a per-project basis.)

Make LSF Resource for CWL Runner job configurable.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
lib/perl/Genome/Model/CwlPipeline/Command/Run.t

We've encountered some workflows that like to have arrays of arrays of files as outputs.  Rather than coerce everything into a single level of arrays, let's just recurse until we find the individual entries we're
after.
(`?w=1` makes this PR diff a lot easier to follow!)

Better handling of arbitrary array structures when extracting files.

---

lib/perl/Genome/Model/Tools/Sambamba/Base.pm

Eliminate hard-coded sambamba path by looking up allocation.

---

lib/perl/Genome/Disk/Volume.pm

New disk volumes are coming through LIMS Synchronization with this value undefined.  A better solution would probably be to make a sqitch migration to drop this column and then not worry about it.  This is an expedient solution instead.

Set a default for disk volume hostname.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

This will be our mechanism for submitting files to third-party locations and the like, since those types of operations must be run on completed workflows.

Allow for an optional process_outputs.pl script.

---

lib/perl/Genome/Config/AnalysisProject/Command/Create.pm
lib/perl/Genome/Config/Profile.pm
lib/perl/Genome/Model/Build/CwlPipeline/InputProcessor.pm
lib/perl/Genome/Model/CwlPipeline.pm
lib/perl/Genome/ProcessingProfile/Command/View.pm

This quiets the warnings from newer Perls like:
```when is experimental at lib/perl/Genome/Model/CwlPipeline.pm line 197.```

We know that `when` is experimental, and we're okay with that.

---

lib/perl/Genome/FeatureList/Command/DumpIntervalList.pm
lib/perl/Genome/FeatureList/Command/DumpIntervalList.t
lib/perl/Genome/FeatureList/Command/DumpMergedList.pm
lib/perl/Genome/FeatureList/IntervalList.pm

This will come in handy for the per-target metric reporting!

Add option to preserve region names to the IntervalList dumper.

---

lib/perl/Genome/Config/Profile.pm
lib/perl/Genome/Config/Profile_input_data.t

The trick here is to carefully duplicate the model instance hash for each matching subject mapping.
(Though not required, these changes might make more intuitive sense with `?w=1` applied.)

 Add support for multiple matching subject mappings for a sample.

---

lib/perl/Genome/Process.pm
lib/perl/Genome/Sys/LSF/bsub.pm
lib/perl/Genome/Sys/LSF/bsub.t

Everything old is new again! The `simple` backend `bsub`s a single job that then runs the entire workflow inline.  (For CWL pipelines "the entire workflow" is a single job that runs `toil` or `cromwell` for the *real* workflow :smile:)

New WorkflowBuilder Backend: `simple`

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

This is the companion to genome/analysis-workflows#589.  It sets a default for any CWL steps that don't have a defined memory request.

Set default memory request of 4096MB.

---

lib/perl/Genome/Model/Build.pm

We'd already turned these off for production users as they're noisy.

Stop e-mailing build reports.

---

lib/perl/Genome/Process.pm

There's logic to prepend any notes with a sudo message when running as another user, but that's not helpful here. (Really, storing this as a note is not great--it should just be a column on the table.)

Ensure only the LSF Job ID gets into the process note.

---

lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.pm
lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.t
lib/perl/Genome/Site/TGI/Extension/ConfigureQueuedInstrumentData.pm
lib/perl/Genome/Site/TGI/Observers.pm

This will cause CQID failures when the data could not be imported.  But that's probably fine, since the builds would themselves fail later!
There is an additional complication in that this would need to be run as a user with access to import the data.

Site Feature: Import instrument data from LIMS in CQID.

---

lib/perl/Genome/Site/TGI/Command/ImportDataFromLims.pm

The allocation system will handle that!  Also... sometimes the config specifies a specific volume instead of a group (#1866), in which case this extra code would crash.

Don't bother loading up the disk group.

---

lib/perl/Genome/Site/TGI/Command/ImportDataFromLims.pm

Otherwise we're in the default environment, which never has a configured disk group.

Make sure we're in the AnP environment when looking up the disk group.

---

lib/perl/Genome/Model/Build/Command/AbandonPriorBuildsWithStatus.pm
lib/perl/Genome/Model/Build/Command/AbandonPriorBuildsWithStatus.t

If a model has many builds, sometimes we only want to keep the recent ones.  This facilitates abandoning the others for a large project.
(This tool's creation was motivated by BGAS-657, wherein a project of 900 models had run out of disk space but had many prior successes and failures.)

Tool to abandon prior builds for a model.

---

lib/perl/Genome/Disk/Detail/Allocation/CreationParameters.pm

This should help make more plain errors if a volume belongs to multiple disk groups (or...none, if such a thing ever were to happen!).

Check that we got exactly one disk group and explicitly die if not.

---

lib/perl/Genome/Site/TGI/Extension/ConfigureQueuedInstrumentData.pm

The command wants to commit() for each instrument data, which causes some bad side-effects to CQID.  We'd still like this to commit immediately--importing can take a long time, and CQID
timeouts might otherwise prevent it from making progress is certain situations.
This should eliminate one source of unintentional starts of multiple builds for a model.

Use a subprocess to import LIMS instrument data.

---

lib/perl/Genome/Model/Build/Command/AbandonPriorBuildsWithStatus.pm

Running `genome model build abandon` with no builds specified generates an error in commit, even though there's nothing to commit.

Skip running the abandon command when no builds match.

---

etc/genome/spec/disk_group_scratch.yaml
lib/perl/Genome/Model/Build.pm
lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
lib/perl/Genome/Model/CwlPipeline/Command/Run.t

This way we can have a pool of scratch space and final project disk groups can be sized to only hold the final data products.
If this is deployed, a value for `disk_group_scratch` will need to be defined in configuration for builds to not fail!

Create a separate allocation for scratch space for CWL builds.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
lib/perl/Genome/Model/CwlPipeline/Command/Run.t

Perl's `File::Copy::move` doesn't work to move symlinks between mounts.  `File::Copy::Recursive` handles this, but makes a copy even when moving on the same mount, so isn't ideal for regular files.  Thus we'll use one for symlinks and one for everything else.
Additionally, fix symlink support in our prefix adding.  (Absolute symlinks will get broken, but those don't make much sense in the context of a Cromwell workflow... so hopefully none exist!)  This shortcoming was uncovered when adding a test for symlinks :smile:

Better symlink handling in CWL output staging.

---

lib/perl/Genome/Model/Build/Command/CleanupScratchAllocation.pm

Some users have requested a way to clean up the scratch space without abandoning a build.  (In this case, so they could continue to use the build logs while otherwise reclaiming the disk space.)
This command could also possibly be automated to reclaim space after a certain amount of time without necessarily removing a Failed build from someone's radar.

Command to clean up Scratch Directory for a Build

---

lib/perl/Genome/Config/Profile.pm
lib/perl/Genome/Config/Profile_input_data.t

This does require each step in the chain to only return a single object, so no crazy multiplicative effects!
(Like the listers and the rules, putting "delete" in would be amusing, so don't do that either!)

Allow chains in instrument data properties for model inputs.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
lib/perl/Genome/Process.pm
lib/perl/Genome/WorkflowBuilder/Command.pm

For systems that require a job group for all job submissions, this might come in handy!

Use job group for Cromwell workers.

---

lib/perl/Genome/Model/Build.pm

Thanks to scratch dirs, builds sometimes have multiple allocations.
* Use the plural accessor.
* Avoid triggering UR's "multiple results in scalar context" error.

Handle builds with multiple allocations.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

We've been testing this configuration change in real pipeline runs for a few weeks now.  Seems to be fine :smile:

Increase connection timeout in Cromwell config to 30s.

---

lib/perl/Genome/InstrumentData/AlignmentResult.pm

* Setting a test name is what I'd do anyway if a ticket came in.
* There isn't anything called "apipe-support" any more.

Offer a self-service option in error, remove old queue reference.

---

lib/perl/Genome/Library.pm
lib/perl/Genome/Library.t

For analyzing feature barcoded single cell samples you need 2 libraries. first is the feature barcoded library, second is the feature barcoded gene expression library.
Previous analysis configuration files used `is_10x_gex -> 0` to get the feature barcoded gene expression instrument data and the feature barcoded instrument data in a single genome model. This was possible because the protocol for the feature barcoded gene expression instrument data added `FeatureBarcoded` to the end of the normal `10x_SC-5'GEX` or 3' gene expression protocol name.
The new 10x_gex regexes are now matching the feature barcoding gene expression instrument data. This is fine for the gene expression only analysis but causing issues for the feature barcoding analysis. The feature barcoding models are created …

Adding is_10x_barcoded

---

etc/genome/spec/docker_volumes.yaml
lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
lib/perl/Genome/Sys/LSF/bsub.pm

* Cromwell can run WDLs, so if someone tries to give us one, try to run it.
* In the "string" version of pipelines, we don't localize references and instead assume they're mounted in a standard location.  Now there's a config variable to help mount that standard location.  (This isn't strictly required for the File version of workflows to work, but we like avoiding copies!)

CWLPipeline: Accept WDL and custom mount paths

---

lib/perl/Genome/Model/Build/Command/Export.pm

the rest of gms uses a "build" prefix, this should too, for consistency (especially during storage1 migration)

preserve "build" prefix on build directory name

---

lib/perl/Genome/Model/CwlPipeline/Command/Input/Add.pm
lib/perl/Genome/Model/CwlPipeline/Command/Input/Add.t
lib/perl/Genome/Model/CwlPipeline/Command/Input/Remove.pm
lib/perl/Genome/Model/CwlPipeline/Command/Input/Remove.t

Sometimes someone might want to add a custom object input that isn't automatically resolved by the class.  Now there's a way to do so (as long as the object exists, anyway!)

Support supplying input classes directly in CwlPipeline commands

---

lib/perl/Genome/Model/Build/Command/Export.pm

Globus eats symlinks, so tarballs seem like a reasonable, if somewhat I/O inefficient way to transfer build directories.  It also simplifies verifying the transfer, since we can compare file sizes or md5s of the tarballs. (Globus does this internally as well, but "trust and verify"...)

adding tarball option to build export

---

lib/perl/Genome/Disk/Allocation.pm

This usually doesn't matter at all, but if someone is trying to test different perl versions they'll be glad it's here :)

Use the current interpreter rather than assuming genome-perl.

---

lib/perl/Genome/Cromwell.pm
lib/perl/Genome/Model/Build/Command/View.pm
lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

* Instead of using a MySQL database, can specify to use a local disk-backed database:
* `hsqldb:tmp`: to use a database in the build's scratch directory that will be cleaned up.
* `hsqldb:build`: to use a database retained in the build's data directory.
* `hsqldb:file:/path/`: to use a database in a specified location.
* The timing report from Cromwell will now be saved after a workflow completes.  This is stored as `timing.html` in the build data directory.
* When using the local disk-backed database, the workflow view is often unavailable.  (It might be possible to write our own viewer that opens the database read-only, but Cromwell itself can't deal with a read-only database.)
* `Genome::Cromwell` now tries performing Cromwell API queries up to five times.  In practice I've never seen …

Support using file-based database for Cromwell workflows

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
lib/perl/Genome/Process.pm
lib/perl/Genome/Site/TGI/Command/ImportDataFromLims.pm
lib/perl/Genome/Sys/LSF/ResourceParser.pm
lib/perl/Genome/Sys/LSF/ResourceParser.t
lib/perl/Genome/Sys/LSF/bsub.pm
lib/perl/Genome/Sys/LSF/bsub.t

* The new compute cluster we're using requires this.  (Since this PR requires setting a value: for the old cluster a group such as `research-hpc/` will suffice.)
* In the new cluster, the correct value should be added to the AnP config (e.g., `lsf_user_group: compute-awesome`).  This is the compute group that will be charged when builds are run.  For the old cluster an appropriate default will be set in the production configuration.

Support setting an LSF user_group.

---

lib/perl/Genome/Disk/Allocation.pm
lib/perl/Genome/Model/Build.pm
lib/perl/Genome/Model/Command/Admin/FixOrphanedAllocationsForDv2Results.pm

There were a few places in the code base that made strong assumptions about how many `/`s appear in an allocation `mount_path`.  That's gotten us by in the past, but isn't really ideal.  Now that more volumes are going to violate this assumption, let's patch up the code to handle the variety of possibilities!
This patch disclaims responsibility for the choice of using `$a` as a variable in the orphaned allocation finder. :smile:

Don't assume mount_path structure.

---

lib/perl/Genome/Site/edu/wustl/ris.pm

Maybe at some point we'll split these up since they represent two different clusters.  It might even be a good opportunity to pull things from TGI that really belong in the main classes!  But for now, the two clusters are similar enough...
(See also, the existing `Genome::Site::edu::wustl::gsc` module.)

Have ris.wustl.edu domains use the "TGI" site, too.

---

lib/perl/Genome/WorkflowBuilder/Block.pm

Someone is running `ReferenceAlignment` builds even though we shut down PTero.  The inline `WorkflowBuilder` logic almost worked, but the final step failed because the preceding block operation didn't pass along some required information.  This fills in the implementation of blocks to pass along their inputs.

Pass the inputs along to the outputs in Block operation.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
lib/perl/Genome/Sys/LSF/bsub.pm

The environment will have been set up with necessary mounts to get things started (e.g., via `gsub` or the BQM cron).  We'll need to keep those along in addition to whatever project-specific mounts someone chooses to add.

Make `docker_volumes` config additive to the existing environment.

---

lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.pm

A previous import might have been purged, in which case new analysis would require reimporting the data. (Users can then also use `genome analysis-project reprocess` if they need to pull back the data to build again later.)

Only consider active allocations when deciding whether to import.

---

lib/perl/Genome/Disk/Assignment.pm
lib/perl/Genome/Disk/Group.pm

We've heretofore been importing them from an external canonical source that determines their IDs, but now we need to be able to make them directly.

Use UUID generator for creating disk groups.

---

lib/perl/Genome/Model/Tools/CopyCat/Somatic.t

Sometimes they pass.  Sometimes they fail.  But the code hasn't changed in a long time, so it's clear these tests are not particularly useful.

Skip non-deterministic tests.

---

lib/perl/Genome/Disk/Command/Volume/List.pm
lib/perl/Genome/Disk/Volume.pm

For volumes that are mounted via a cache layer, df doesn't work properly (among other non-compliant aspects of the filesystem).  In our case we could possibly use SMB to connect to the remote server and find out the canonical used and total KB, but for now let's trust our database to be accurate.
Some notes: 
* The `hostname` should be properly filled out for these remote volumes--right now we're only checking for the hostname to have a `.` in it to decide it's from a remote server.
* For volumes that point to directories within remote volumes, the physical path must be set to the actual volume. (e.g., for a `mount_path` of `/storage/fs/foobar/VOLUME/subpath/for/genome` the `physical_path` is still `/storage/fs/foobar/VOLUME`)
* This does mean that a user can set a separate soft quota for …

For now, don't try to `df` remote volumes.

---

lib/perl/Genome/Model/CwlPipeline/Command/ListDockerImages.t

`skip` returns `undef`, so we'll add our own true value!
(This will pass the PR tests (as it did before), because they don't use `--track` mode.  The real proof will only come after it's merged.)

`test-tracker` in `--track` mode requires tests to return a true value in order to pass.

---

lib/perl/Genome/InstrumentData/Imported.pm

We heretofore have expected `all_sequences.bam` to be the name for all imported BAMs.  The new `trusted-data` importer makes it easier to not follow this convention.  As long as there's only one BAM in the directory, we should be fine to move along using it.
(Plus a bonus bugfix in an existing error message!)

Allow imported BAMs with arbitrary filenames

---

lib/perl/Genome/Sys.pm

On the new cluster this directory is locked down so we lack permissions to change it.

Remove modifications of pre-provided LSF temp directory.

---

lib/perl/Genome/Disk/Detail/Allocation/Creator.pm

In 461d694dae993e839e8fee2dd77c7eb6a3b2533a we removed instrumentation, which left the outer call here as a mostly pointless wrapper.  So now let's just consolidate them.

Remove extra layer of method calls.

---

etc/genome/spec/cromwell_call_caching.yaml
lib/perl/Genome/Model/Build/Command/View.pm
lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

Add an option to enable call caching and take some steps to make the `restart` command work with Cromwell-based CwlPipeline builds.
There are some potential issues with display of and/or output retrieval under this scheme explained in the commit text for 009bddcc18c296f10f8aba75123644b3fffe6079.

Cromwell Call Caching support

---

lib/perl/Genome/Disk/Allocation.pm
lib/perl/Genome/Disk/Command/Allocation/Transfer.pm
lib/perl/Genome/Disk/Command/Allocation/Transfer.t

This is a command for transferring data to a remote volume.  Having an appropriate endpoint for the transfer is left as an exercise for the user.  (Thankfully there are existing docs for that :smile:)
This command has not been tested prior to the PR creation(!) We should identify some potential tests cases before merging.

New command `genome disk allocation transfer`.

---

lib/perl/Genome/Db/Tgi/Command/ImportFromDgidbByCategory.t
lib/perl/Genome/Model/ClinSeq/Command/AnnotateGenesByDgidb.t
lib/perl/Genome/Model/Tools/Dgidb/Base.pm
lib/perl/Genome/Model/Tools/Dgidb/QueryGene.t

The new release of dgidb requires SSL. The plain HTTP version redirects and this code can't handle the 301 response.  This is likely a good candidate for outright removal, but these changes make the tests pass again (albeit mostly in a lame way).

Use HTTPS to connect to dgidb.

---

lib/perl/Genome/Site/TGI/Command/ImportDataFromLims.pm

This should facilitate transfers with slightly fewer manual steps and without intermediate staging on a local volume.

Support importing LIMS data into the system directly onto a remote volume.

---

lib/perl/Genome/Project/Command/Update/Models.pm
lib/perl/Genome/Project/Command/Update/Models.t

We've locally been using a different production user for many years, so it'd be nice if this worked again!

Stop hardcoding "apipe-builder" when determining applicable models

---

lib/perl/Genome/Config/AnalysisProject/Command/PossibleVolumes.pm
lib/perl/Genome/Config/AnalysisProject/Command/PossibleVolumes.t

This command lists the possible volumes configured for an AnP.  This could be used for a safe list of volumes to mount when launching a container to work with the AnP.
After this and #1988 we'll have the building blocks to possibly support BQM launching remote builds.

New command to help identify which volumes to mount.

---

lib/perl/Genome/Disk/Allocation.pm

UR classes don't necessarily have defined perl module files, and we don't support auto-updating any non-UR classes, so this should be good enough!

Use more UR-centric approach to test for owner class existence.

---

etc/genome/spec/builder_run_as_user.yaml
lib/perl/Genome/Config/AnalysisProject/Command/Create.pm

Now that we're operating on multiple clusters we've run into a situation where it'd be nice to distinguish between then with different "run_as" indications.  This will let us change it when run on the new cluster while leaving it the same on the old.  (Or someone enterprising could set the appropriate environment variable to setup for the "other" cluster for the one they're on!)

Make the "prod-builder" run_as configurable.

---

lib/perl/Genome/Disk/Command/Group/Create.pm
lib/perl/Genome/Disk/Command/Group/Create.t
lib/perl/Genome/Disk/Command/Volume/Create.pm
lib/perl/Genome/Disk/Command/Volume/Create.t

Now that we're mostly managing volumes manually, here are two new commands: `genome disk group create` and `genome disk volume create`.  This should help make the process easier!

Create commands for disk groups and volumes

---

lib/perl/Genome/Model/CwlPipeline.pm
lib/perl/Genome/Model/CwlPipeline/Command/Requeue.pm
lib/perl/Genome/Model/CwlPipeline/Command/Requeue.t
lib/perl/Genome/Model/CwlPipeline/Command/Restart.pm
lib/perl/Genome/Model/CwlPipeline/Command/Restart.t

This functions like `genome model build queue` but for restarting builds rather than creating new ones.  Since we're moving away from supporting the queue for arbitrary users, this is set up to only allowing the queue of failed "production" builds.
To lend functionality to this, there'll need to be a task that runs to process the queue, such as via
```bash
ur list objects --subject Genome::Model::Build::CwlPipeline --filter rebuild_requested=1 --show id
```

Add ability to queue rebuilds for CwlPipeline builds.

---

lib/perl/Genome/Sys.pm

With the fancy fancy cache layer we're using these days, the actual size of files that haven't been pulled into the cache is not detemrined correctly by `du`.  But the apparent size is good enough!

Use the apparent size for allocations.

---

lib/perl/Genome/Sys.pm

Less performant, sure, but actually works with a lovely non-posix-compliant filesystem, too!
See also: https://perldoc.perl.org/filetest

Enable ACL support for filetests.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

Before we were letting jobs fail and manually running `script.submit` for replacement jobs in the event of LSF failure due to the high cost of starting a workflow from the beginning over such a trivial failure. With call-caching that cost is reduced, so it's better to have quicker notification of issues.
(Ten minutes is an arbitrary choice on my part; I don't have any particular justification for it if someone has suggestions for alternate intervals.)

When call-caching is enabled, check the health of jobs.

---

lib/perl/Genome/Site/TGI/UsageLog.pm

It makes me sad this string is hardcoded here, but I guess updating it once every several years isn't so bad 🙂

Update connection string for usage log.

---

.test-tracker.conf

Once again not a useful file for the world at large, but helpful for us!

Include certs in test-tracker server config.

---

lib/perl/Genome/Model/Command/Admin/RemoveDiskAllocationsFromTestdb.pm

Thankfully when the connection can't be made this tool errors out instead of assuming all allocations are ripe for deletion :smile:

Check for certificates for the production database connection.

---

lib/perl/Genome/Config/AnalysisProject/Command/AddEnvironmentFile.pm
lib/perl/Genome/Config/Profile/Item.pm

Minimal changes to support adding environmental and model config files to AnPs. Instead of copying new files to the appropriate local directory, as compute1 permissions prevent this when run by regular users, the file is instead copied to a GCP bucket. Jenkins then periodically checks the bucket for new files, pushes them to the appropriate github repo, and uses git to sync storage0 and storage1.

Basic config file changes

---

lib/perl/Genome/Config/Profile/Item.pm

Add in a forgotten `.` to the constructed file name and make sure that it does not contain the original file name's suffix, following the naming convention expected by a downstream jenkins script used for syncing.

Fix uploaded file name

---

lib/perl/Genome/Config/AnalysisProject/Command/AddEnvironmentFile.pm
lib/perl/Genome/Config/Profile/Item.pm
lib/perl/Genome/Disk/Allocation.pm
lib/perl/Genome/Disk/Detail/Allocation/Creator.pm

These changes retain the ability to write directly to the filesystem, for use in testing or by the service account running CQID, while otherwise skipping allocation path creation for new environment and config files. The paths are created by the jenkins task that syncs the new files.

Skip allocation path creation for config files

---

lib/perl/Genome/Disk/Detail/Allocation/Creator.pm
lib/perl/Genome/Disk/Volume.pm

Following #2007, direct disk writes to create allocation paths are now skipped in most cases (when unprivileged users are running commands) in favor of queuing them for creation by a Jenkins task running as a service user with the proper permissions. However, disk queries to ensure that the volume has space still occur, which causes an error due to the way the core gms volume is mounted on compute1. This patch removes some of the direct disk queries, while still preserving checks that query the database to determine if there should be free space. Since the database is updated when allocations are created, even when the paths are not, this should be safe.

Skip disk querying

---

lib/perl/Genome/Config/Profile/Item.pm

This will still fail if the config was ever used for models (which prevents crazy cascading deletes!), but an unused config that happened to have a tag can now be cleaned up.

Support deleting a config profile item with linked tags.

---

lib/perl/Genome/Model/Command/Define/ImportedReferenceSequence.pm
lib/perl/Genome/Model/SomaticValidation/Command/ValidateSvs/CreateAssembledContigReference.t
lib/perl/Genome/Test/Factory/AnalysisProject.pm

This should make defining references within someone's non-core AnP go a little more smoothly!

Use AnP config for build creation/running in refseqs.

---

lib/perl/Genome/Site/TGI/Command/ImportDataFromLims.pm

The remote volume support regressed the tolerance added in #1866 in this particular case.  It could still be avoided by using the right type of data being requested, though!

Tolerate the user specifying an explicit volume instead of a group.

---

lib/perl/Genome/Site/TGI/Command/ImportDataFromLims.pm

This purports to look it up in config, but the config is a lie.  The latest version of the config is itself stored inside the docker image, so it's not possible to look it up from the outside.  Rather than rely on an old version of the config, just put in the current latest value.

Use a hardcoded lims docker image.

---

lib/perl/Genome/InstrumentData/Command/Import/TrustedData.pm
lib/perl/Genome/InstrumentData/Command/Import/TrustedData.t
lib/perl/Genome/Sys.pm

To avoid duplicate copies of data when importing from local disk, some users have requested the ability to have the importer not retain the original files.  This uses the `rsync` option that removes files on transfer.  It won't remove directories--only the files inside of them.

Add option to trusted-data importer to delete the source files.

---

lib/perl/Genome/Model/CwlPipeline/Command/Requeue.t
lib/perl/Genome/Model/Metric.pm

When deleting metrics (to replace them), UR was complaining about the column names not matching the database.  The capitalized names were held over from before we switched to PostgreSQL, so let's just lowercase them now.

Address errors with metric ghost class [to fix CWL requeueing].

---

lib/perl/Genome/Role/Logger.pm

I think we should switch users of this to use the UR logging methods instead, but this is a quick fix for now.

Monkeypatch to get around longstanding bug in Logger.

---

lib/perl/Genome/Config/AnalysisProject.pm
lib/perl/Genome/Config/AnalysisProject/Command/PossibleVolumes.pm
lib/perl/Genome/Config/AnalysisProject/Command/PossibleVolumes.t
lib/perl/Genome/Model/Command/Admin/CleanupSucceeded.pm
lib/perl/Genome/Model/Command/Admin/PurgeDiskAllocationsForAbandonedBuilds.pm
lib/perl/Genome/Sys/LSF/bsub.pm

This creates an option to submit sub-jobs for the abandon process to give a chance to mount the requisite volumes for the abandonment process.
This also includes a cleanup command to look for allocations for abandoned builds (because sometimes disk is unreliable...).

Handle not having automatic mounts in Cleanup Succeeded

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

It only matters if you have certain other settings enabled that we weren't using before.  But now it does matter 😄

I believe this should be kill-docker like it's submit-docker.

---

lib/perl/Genome/Model/Command/Admin/CleanupSucceeded.pm
lib/perl/Genome/Model/Command/Admin/PurgeDiskAllocationsForAbandonedBuilds.pm
lib/perl/Genome/Model/Command/Submittable.pm
lib/perl/Genome/Model/CwlPipeline.pm
lib/perl/Genome/Model/CwlPipeline/Command/ProcessActionQueue.pm
lib/perl/Genome/Model/CwlPipeline/Command/ProcessActionQueue.t
lib/perl/Genome/Model/CwlPipeline/Command/Requeue.pm
lib/perl/Genome/Model/CwlPipeline/Command/Requeue.t
lib/perl/Genome/Model/CwlPipeline/Command/Restart.pm
lib/perl/Genome/Model/CwlPipeline/Command/Restart.t

For CwlPipeline builds, now they can be requested to be stopped or abandoned in addition to being restarted.  Since stop and abandon are destructive, only the AnP owner (or an admin) can make these requests.

A queue for requesting stop/abandon for production builds.

---

lib/perl/Genome/Model/Command/Services/ListBuildQueue.pm

I'm inclined to say we shouldn't be using it anywhere--UR has built-in logging already that meets our needs.  This makes progress towards that goal!

Stop using Genome::Logger in list-build-queue.

---

etc/genome/spec/cromwell_gcp_bucket.yaml
etc/genome/spec/cromwell_workflow_options.yaml
etc/genome/spec/workflow_deps_zip.yaml
lib/perl/Genome/Cromwell.pm
lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

Enable GCP workflows by setting `cwl_runner` to `cromwell_gcp`
Additional settings required are:
- `workflow_deps_zip`, path to a .zip file containing WDL dependencies, likely pointing at analysis-wdls repository
- `cromwell_workflow_options`, path to a .json file for Cromwell settings, different for each lab at minimum
- `cromwell_gcp_bucket` which bucket to place Cromwell generated files like outputs and logs
gcloud uses user permissions, so the user must `gcloud auth login` before sending off jobs

Enable GCP workflows via environment configuration options

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
lib/perl/Genome/Model/CwlPipeline/Runner/Toil.pm

Any container used in the workflow must be capable of running python3 with glibc version of at least 2.16 so that toil's wrapper can run.  (This is similar to how Cromwell requires every image to have a bash shell so its wrapper can run.)  Python doesn't actually need to be installed--we have a copy we mount in the container so long as the shared libraries are compatible.

Updates to support per-job containers when running with toil.

---

etc/genome/spec/lsf_queue_interactive.yaml
lib/perl/Genome/Model/Command/Submittable.pm
lib/perl/Genome/Process.pm

We were relying on the fact that the default queue is interactive, which is not ideal!

Add config for specifying the queue for interactive jobs.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

During my tests with this, the `--project` setting in gcloud commands called by gms/start.sh was implicitly pulling the setting from the environment, set by `gcloud config set project PROJECT` instead of using the value set in genome config. 
This commit fixes this by propagating the value into gms/start.sh which has been updated to accept that argument and use it in the creation of the cromwell VM. 
[cloud-workflows/gms/start.sh updates here](https://github.com/griffithlab/cloud-workflows/commit/49b62f602febaf76459af46ece717fa49bd364e3)

Propagate cromwell_gcp_project setting to gms/start.sh script

---

lib/perl/Genome/Sys.pm

For some reason, some servers we're using create a doubly-nested LSF
tmpdir structure, and the inner one is r/w only by root.  In this case
they're already giving us the first level as $ENV{TMPDIR} so we can just
trust it anyway.  This code is still useful on our older cluster,
though, so not just removing it outright yet.
Is this the first instance of using perl 5.10 filetest stacking in our codebase? It might be :smile:

Only modify tmp basedir if new location is writable.

---

.test-tracker.conf

Some hosts don't have a friendly search path configured, so this is a little more certain to work as expected.  This should help with some intermittent failures.

Use fully qualified domain name for database server.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Bwa.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Bwamem.pm
lib/perl/Genome/InstrumentData/AlignmentResult/BwamemStream.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Bwasw.pm
lib/perl/Genome/InstrumentData/Command/AlignReads.pm
lib/perl/Genome/InstrumentData/Command/AlignReads/PerLaneTophat.pm

We don't care if they're "blades". In fact, we only care that the
command tries to return any results at all, so check for the header row!
When there aren't any hosts, it'll return this instead:
`Not enough host(s) currently eligible`
So looking for the line to start with `HOST` is good enough.

Revise check for matching hosts.

---

lib/perl/Genome/Model/Tools/Annotate/TranscriptVariants/Version1/VariantAnnotator.t
lib/perl/Genome/Model/Tools/Annotate/TranscriptVariants/Version2/BedToAnnotation.t
lib/perl/Genome/Model/Tools/Annotate/TranscriptVariants/Version2/VariantAnnotator.t
lib/perl/Genome/Model/Tools/Annotate/TranscriptVariants/Version3/BedToAnnotation.t
lib/perl/Genome/Model/Tools/Annotate/TranscriptVariants/Version3/VariantAnnotator.t
lib/perl/Genome/Model/Tools/Annotate/TranscriptVariants/Version4/BedToAnnotation.t
lib/perl/Genome/Model/Tools/Annotate/TranscriptVariants/Version4/VariantAnnotator.t
lib/perl/Genome/Model/Tools/BioSamtools/AlignmentSummaryV2.pm

To handle non-POSIX permissions we need to not rely on the default behavior of -r.

Consistently use Genome::Sys to test readability of files.

---

lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.pm

There is no `/gapp` on the new cluster, so use our config instead since we already have that mechanism for controlling where to look!

Use the Genome::Sys method to get the java executable path.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Merged.t
lib/perl/Genome/InstrumentData/AlignmentResult/Speedseq.t
lib/perl/Genome/InstrumentData/AlignmentResult_regenerate.t
lib/perl/Genome/InstrumentData/Command/AlignAndMerge.t

The tests try to allocate space when revivifying the per-lane BAMs. When the bam size is unknown, the default size request is 100,000,000KB. When temp on the host running the test has less than this amount of space free, the test can fail.
(If temp has less than 1024KB free, we're probably going to have other trouble, anyway!)

Claim that .t test per-lane BAMs are all 1024KB.

---

lib/perl/Genome/Model/Tools/DetectVariants2/MethRatio.t
lib/perl/Genome/Model/Tools/Fastq/Split.pm

* Disable DV2 MethRatio test (by popular consensus that it isn't being used).
* FASTQ splitter properly checks it can write to the output directory it will use.

Some straggling test fixes

---

lib/perl/Genome/Model/Build-multiple-model-inputs.t

If perchance both items have identical timestamps, use ID as a tiebreaker so the ordering is still consistent between them.
This test has been failing intermittently so hopefully this helps with that!

Add a tiebreaker in the sorting algorithm.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.t

Currently CWL scratch directories reserve 50GB, but the test uses local temp and doesn't require nigh that much space anyway!
This is another intermittent failure that came from landing on a blade with <50GB `/tmp` space.

Don't worry about if we have space for allocations in this test.

---

lib/perl/Genome/Model/Build/Command/AbandonPriorBuildsWithStatus.t

It is true that some of our commands will fail if multiple builds were
created within the same second.  There's locking in place that prevents
that from happening in practice, so this test was failing for an edge
condition we don't normall encounter.  (If we truly have multiple
simultaneous builds in the same status, picking one arbitrarily to
execute is the "right" behavior here, anyway.)

For test stability, have each build created at a different time.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

If a build fails after the Cromwell workflow has succeeded, then a
build `restart` may create a new workflow in which case there may
be multiple succeeded workflows.  Instead of crashing, we'll trust
that the most recent one is the one we care about.

If there are multiple Cromwell workflows, use the most recent.

---

lib/perl/Genome/Model/Build/Command/AbandonPriorBuildsWithStatus.t

Our command uses the creation date to determine which build is most recent for purposes of abandoning prior attempts.  However if an older build completed after a later build, then our test would be grabbing the wrong one for being "saved".  (Instead let's keep tabs on the last one we made, since it should be the most-recently-created and thus the one to be saved.
(This is a followup to #2051 which made the test builds actually distinguishable by the command to begin with.)

Don't use "last_complete_build" in this test.

---

lib/perl/Genome/Config/AnalysisProject/Command/Create.pm
lib/perl/Genome/Config/AnalysisProject/Command/Create.t

Since "prod-builder" isn't really descriptive and is also the name of the default runner user, it was suggested we use a neutral term instead, especially for those circumstances where a different runner is being used.

Rename "prod-builder" env option to "automated".

---

lib/perl/Genome/Model/CwlPipeline/Command/Requeue.pm

They're actually defined on the model class and not the derived build class.  Also, a little explanation for "0" seems helpful!

Fix enumeration of valid values for --action parameter.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

We're moving cloudize-workflows image from my personal dockerhub to the mgibio dockerhub. The contents are still the same repo here: https://github.com/griffithlab/cloud-workflows/

Use mgibio image for cloudize-workflows in cromwell_gcp workflows

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

Removing deep option, as it no longer exists in the pull output script

fixing pull_outputs command for cloud workflows

---

lib/perl/Genome/ProcessingProfile/Command/Create/CwlPipeline.pm

Add the `-m` flag to run the upload in parallel and reduce upload time, and add the `-q` flag to prevent listing every uploaded file (currently over 250).

Add multithreading and suppress output

---

lib/perl/Genome/Memcache.t

It's also not really safe for concurrent test runs!
Realistically we're more likely to remove this than to fix it, since memcache was used for the perl-generated webviews but we have moved on to genome/spectacle now.

Skip Memcache.t that depends on production memcache.

---

lib/perl/Genome/Memcache.t

Also seen in #1980.  (As with that one, the individual PR test will work either way so it only affects the merged tests.)

Add done_testing so that test-tracker handles skip properly.

---

lib/perl/Genome/InstrumentData/AlignmentResult/Bwa.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Bwamem.pm
lib/perl/Genome/InstrumentData/AlignmentResult/BwamemStream.pm
lib/perl/Genome/InstrumentData/AlignmentResult/Bwasw.pm
lib/perl/Genome/Sys.pm

There were a few competing implementations around for this; better that we have one that we can fix up when/if issues arise.
(A lot of this seems like a good candidate for outright deprecation and removal at this point... but this PR is a quick change to get tests to pass again for now.)

Centralize checking for the existence of eligible LSF hosts.

---

lib/perl/Genome/InstrumentData/Command/Import/Inputs/Factory.pm

Also, report the error when the `tie` fails instead of mysteriously failing to parse the header later.
(The test files are mounted read-only now, so the tests that covered this would fail on the `tie` with a `Read-only file system` message.  Users should be able to import instrument data with a read-only input TSV anyway.)

Only tie read-only since we don't need to write this file.

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

The historic default for units in LSF `bsub`s are confusing (and depending on cluster configuration may be differently inconsistent). Now it's possible to specify a unit suffix, so let's set it to the same precision as CWL affords.
[Marking this as a draft PR because we can't merge it so long as we need to support older clusters.  But it's a change we likely want to patch in on new enough versions.]

Use explicit units for memory reservations (LSF10 feature).

---

lib/perl/Genome/Site/TGI/Project/View/Status/Html.t
lib/perl/Genome/Site/TGI/Project/View/Status/Xml.t
lib/perl/Genome/Sys.pm
lib/perl/Genome/WorkOrder.t

This fixes up `Sys.pm` to be more judicious about which database sources it tries to disconnect to avoid inadvertently processing connection info to a datasource that wasn't connected.
This also disables tests that depend on an OLTP connection.  Still holding off on outright removing modules that depend on it in case we need to refer back to the database dump later.

Avoid attempting to connect to OLTP database

---

lib/perl/Genome/Model/CwlPipeline/Command/Run.pm

This will let certain jobs be dispatched to different queues.

Define a "queue" runtime attribute for WDL tasks.

---

lib/perl/Genome/Model/SomaticVariation/Command/TestHelpers.pm

The test data is about 50MB so a 100MB allocation provides plenty of room.  This prevents failures when running tests on a blade with <32GB of free temp space, since we definitely don't need that much!
(Probably should've done this years ago 🙂)

Use a smaller allocation size for testing.
