genome/genome

- lib/perl/Genome/Model/Build/ClinSeq/FileAccessors.pm
- lib/perl/Genome/Model/Build/ClinSeq/FileAccessors.t
- lib/perl/Genome/Model/ClinSeq.pm
- lib/perl/Genome/Model/ClinSeq/Command/Converge/Base.pm
- lib/perl/Genome/Model/ClinSeq/Command/Converge/DocmReport.t
- lib/perl/Genome/Model/ClinSeq/Command/Converge/MutationSpectrum.pm
- lib/perl/Genome/Model/ClinSeq/Command/Converge/SnvIndelReport.pm
- lib/perl/Genome/Model/ClinSeq/Command/Converge/SnvIndelReport.t
- lib/perl/Genome/Model/ClinSeq/Command/Converge/Stats.pm
- lib/perl/Genome/Model/ClinSeq/Command/Converge/Stats.t
Add a new file to the converge stats command, this is the Stats.tsv from summarizing SNVIndelReports. To help accomplish this make base quality and mapping quality a parameter of Base.pm under Converge.
> clinseq-converge-stats update

- lib/perl/Genome/Model/RnaSeq.pm
- lib/perl/Genome/Model/RnaSeq.t
- lib/perl/Genome/Model/Tools/Htseq/Count-many.t
- lib/perl/Genome/Model/Tools/Htseq/Count.pm
- lib/perl/Genome/Model/Tools/Htseq/Count.t
- lib/perl/Genome/Model/Tools/Htseq/Count/Result.pm
Between this and #373 no classes will be left using `Genome::Command::WithSavedResult` so it can be removed.
> Convert GMT::Htseq::Count to a G:C::DelegatesToResult

- lib/perl/Genome/InstrumentData/Command/Import/Basic.pm
- lib/perl/Genome/InstrumentData/Command/Import/Basic_archive.t
- lib/perl/Genome/InstrumentData/Command/Import/Basic_fastq.t
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.pm
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.t
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/SraToBam.pm
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/SraToBam.t
> InstData Import: use names instead of library object for steps interacting

- lib/perl/Genome/Config/AnalysisProject/Command/AddConfigFile.pm
- lib/perl/Genome/Config/AnalysisProject/Command/AddConfigFile.t
Allow tags to be stapled in here for convenience.
> Add tag parameter to AddConfigFile for AUE-383

- lib/perl/Genome/InstrumentData/AlignmentResult/Command/RecreatePerLaneBam.pm
- lib/perl/Genome/InstrumentData/AlignmentResult/Command/RecreatePerLaneBam.t
Make bam_header an optional parameter.
> Add bam_header and comparison_flagstat as required parameters

- lib/perl/Genome/Model/Tools/Analysis/DumpIgvXmlMulti.pm
- lib/perl/Genome/VariantReporting/Command/Wrappers/IgvSession.pm
See https://jira.gsc.wustl.edu/browse/AT-374.
> Handle bam path urls in igv sessions correctly

- lib/perl/Genome/Model/Tools/BamWindow.pm
In trying to troubleshoot [RT#103374][1] I notived a couple of minor
improvements I could make.
/cc @chrisamiller, @tabbott, @jweible
[1]: https://rt.gsc.wustl.edu/Ticket/Display.html?id=103374
> Minor Improvements to BamWindow Wrapper

- lib/perl/Genome/InstrumentData/AlignmentResult/BwamemStream.pm
- lib/perl/Genome/Model/Tools/Bwa/RunMem.pm
This is #420 with a few additional changes.
> create /tmp path if NE for bwa mem and pass along the AR's scratch directory

- lib/perl/Genome/Model/Tools/Bwa/RunMem.pm
because some tools just really insist on a prefix existing :p
> create /tmp path if NE for bwa mem

- lib/perl/Genome/InstrumentData/Command/Import/Basic_archive.t
- lib/perl/Genome/InstrumentData/Command/Import/Basic_fastq.t
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.pm
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.t
> InstData Import: unzip fastqs before running picard sam to fastq; up picard

- lib/perl/Genome/Model/Tools/Htseq/Count/Result.pm
- lib/perl/Genome/Model/Tools/Htseq/Count/Result.t
Hot on the heels of #419 here are a few more fixes to the parallelization logic in this result.  Rather than hope it works, this time I added a test case to cover holes in the Htseq::Count test. :smile:
> A few more fixes and a test for GMT::Htseq::Count::Result

- lib/perl/Genome/compile.t
Using '@{u}' assumes 1) that you're on a branch and 2) that that branch has an
upstream branch.  So if one was on a detached head (checking out a PR, etc.)
then this test would error and fail.
This changes compile.t to fallback on compile checking everything if it can't
guess a way to only check what has changed.
> fix compile.t to not error on detached heads

- lib/perl/Genome/Process.pm
- lib/perl/Genome/VariantReporting/Command/Wrappers/ModelReport.pm
This is to address this issue:
https://rt.gsc.wustl.edu/Ticket/Display.html?id=103685&results=f1b30c0bddfef8d86d72d11875811a52
> Model report fixes

- lib/perl/Genome/Model/Tools/Analysis/DumpIgvXml.pm
- lib/perl/Genome/Model/Tools/Analysis/DumpIgvXmlBasic.pm
- lib/perl/Genome/Model/Tools/Analysis/DumpIgvXmlMulti.pm
- lib/perl/Genome/Model/Tools/Analysis/ResolveIgvReferenceName.pm
- lib/perl/Genome/VariantReporting/Command/Wrappers/CreateIgvSession.t.d/expected.xml
- lib/perl/Genome/VariantReporting/Command/Wrappers/IgvSession.pm
- lib/perl/Genome/VariantReporting/Command/Wrappers/ModelPair.pm
- lib/perl/Genome/VariantReporting/Command/Wrappers/SingleModel.pm
- lib/perl/Genome/VariantReporting/Framework/Component/Report/MergedReport.pm
This PR addresses the following issues:
https://jira.gsc.wustl.edu/browse/AT-717
https://jira.gsc.wustl.edu/browse/AT-718
https://jira.gsc.wustl.edu/browse/AT-719
> Various Variant reporting IGV improvements

- lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
Our "Model Summary" command has been failing. genome/UR#56 addresses a severe
performance problem that occurs when there is "invalid data for save".  This PR
is trying to minimize the collateral damage that occurs under the same
scenario.
> add per-model transactions in "Model Summary"

- lib/perl/Genome/FeatureList/Command/Merge.pm
- lib/perl/Genome/FeatureList/Command/Merge_reference_selection.t
- lib/perl/Genome/Model/Build/ReferenceSequence.pm
Generally solving the problem of deciding what references are combinable would probably be better handled with a graph database of some sort, but this adds a few of the cases we're more likely to encounter (including one for which there is an open ticket presently).
Also in this PR... adding the same sponsor and requestor as discussed in [this thread](https://github.com/genome/genome/pull/429/files#r23570637).
> Add Common Reference Combination Cases in FeatureList Merge

- lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
If _find_first_nondone_step_impl crashes it can leave the related
Workflow::Models in a corrupt state that ends up having "invalid data for
save".  The (side-effect) changes are probably a bug and not relevant to
the task at hand so it's safest just to rollback if
_find_first_nondone_step_impl crashes.
The "invalid data for save" was already being rolled back later when the
transaction fails to commit but by pre-emptively doing it here we can save
a ton of time due to the slow performance of the "invalid data for save"
code.
> protect against corrupted Workflow::Models

- lib/perl/Genome/Sys/Lock/NessyBackend.pm
for test Model/Command/Define/ImportedVariationList.t
> missing newline is messing up TAP output

- bin/genome-env-next
- bin/genome-test-env-next
This pulls in code that was in the apipe-ci repo, adds more control to the
constructed env through the use of options, and adds support for using a test
database.
> genome-env rewrite/refactor

- lib/perl/Genome/Model/Tools/BamWindow.t
new expected output due to bam-window update
> new expected output due to bam-window update

- lib/perl/Genome/Sys-shellcmd.t
- lib/perl/Genome/Sys.pm
This supercedes e4ae511.  The previous commit would have caused our
web server to wig out.  See the message in commit 0d56bbc for why.
> Another try at fixing STDOUT and STDERR redirection

- bin/genome-env-next
Some fixes and improvements for `genome-env-next`.
> genome-env-next iteration

- lib/perl/Genome/VariantReporting/Framework/Component/Report/MergedReport.pm
- lib/perl/Genome/VariantReporting/Framework/MergeReports.pm
- lib/perl/Genome/VariantReporting/Framework/MergeReports.t
- lib/perl/Genome/VariantReporting/Framework/MergeReports.t.d/expected_split.header
This functionality is not needed anymore. See https://jira.gsc.wustl.edu/browse/AT-677
> Remove column splitting capabilities from MergedReport

- lib/perl/Genome/Sample/Command/Import/Base.pm
The PR mostly addresses the elimination of the passing around of entity attributes. Also removed is the updating of attributes of existing samples. WIP - We are still passing the library extension around, but that will be it's own PR.
> Sample Importer Attribute Cleanup

- lib/perl/Genome/Db/Ensembl/Command/Run/Base.pm
A couple tweaks that fix problems I encountered while trying to run a Trio process.
> Make vep wrapper more robust

- lib/perl/Genome/Sample/Command/Import.t
- lib/perl/Genome/Sample/Command/Import/Base.pm
- lib/perl/Genome/Sample/Command/Import/Base.t
WIP. Update the library handling in the sample importer including making the library extension a command property.
> Sample Import: Library Handling Update

- bin/genome-env-next
- genome-env-tests/README.md
- genome-env-tests/basic.bats
- genome-env-tests/submodule.bats
- genome-env-tests/test_helper.bash
- genome-env-tests/testexec/D.sh
- genome-env-tests/testexec/U.sh
- genome-env-tests/testexec/W.sh
There is more to be done but this is first pass at adding some sort of testing
for `genome-env-next`.
> add some test coverage for `genome-env-next`

- lib/perl/Genome/Sample/Command/Import/Base.pm
The last bit of clean up before removing the nomenclature commands and moving the command to the library name space.
> Sample Import

- bin/genome-env-next
- genome-env-tests/basic.bats
- genome-env-tests/test_helper.bash
- genome-env-tests/testexec/M.sh
Update the default DB snapshot to a snapshot that should be able to run the
model tests.
> update default DB snapshot

- genome-webserver/solr/scripts/gcsearch_load_from_mailman.pl
I'll need to deploy this with `gsc-scripts` once merged.
> convert to scoped lock

- bin/genome-env
This includes the missing ClinSeq test build
> Update test db snapshot version

- lib/perl/Genome/Model/Build/DeNovoAssembly/Abyss.t
> temporarily disable test

- lib/perl/Genome/Model/Build/RunsDV2.pm
- lib/perl/Genome/Model/ClinSeq/Command/AnnotateGenesByDgidb.t
- lib/perl/Genome/Model/Event.t
- lib/perl/Genome/Model/Tools/DetectVariants2/Combine/UnionSv.t
- lib/perl/Genome/Model/Tools/DetectVariants2/Samtools.t
- lib/perl/Genome/Model/Tools/Fastq/TrimBwaStyle.t
- lib/perl/Genome/Model/Tools/Fastq/Trimq2/Fragment.t
- lib/perl/Genome/Model/Tools/Fastq/Trimq2/PairEnd.t
- lib/perl/Genome/Model/Tools/Fastq/Trimq2/Simple.t
- lib/perl/Genome/Model/Tools/Sam/ExtractReadGroup.t
- lib/perl/Genome/Model/Tools/Sv/SvAnnot.t
- lib/perl/Genome/Model/Tools/Vcf/Convert/Base.pm
- lib/perl/Genome/VariantReporting/Command/ShowDocs.t
- lib/perl/Genome/VariantReporting/Framework/Component/Expert.pm
- lib/perl/Genome/VariantReporting/Framework/Dag.pm
- lib/perl/Genome/VariantReporting/Framework/Test/Interpreter.t
- lib/perl/Genome/VariantReporting/Generic/FTInterpreter.t
- lib/perl/Genome/VariantReporting/Generic/IndelSizeInterpreter.t
- lib/perl/Genome/VariantReporting/Suite/BamReadcount/Expert.pm
- lib/perl/Genome/VariantReporting/Suite/Vep/VepInterpreter.pm
(Perl 5.14+ doesn't like a bare qw().)
> Use parens around list

- lib/perl/Genome/Model/ClinSeq.t
The Full Perl tests are now failing because this test depends on the current blessed ClinSeq build, which is not included in the new testing database.  Update this test to not having a moving target of database dependency.
> Use the test build to test the ClinSeq file accessors.

- bin/genome-env
I'm not sure if this is a good idea or not, but it seemed useful to us, for example for debugging model tests
> New genome-env option

- lib/perl/Genome/Site/SGMS.pm
- lib/perl/Genome/Site/SGMS.t
this addresses the issue in #527
> add site config for SGMS

- genome-env-tests/test_helper.bash
We've previously seen errors like this:
(from function `cache_repo' in file test_helper.bash, line 34,
from function `init_workspace' in file test_helper.bash, line 44,
from function `setup' in test file submodule.bats, line 6)
`init_workspace' failed with status 128
At the time Tom said he nuked the directories to fix it.  The Git repos are
being corrupted and I suspect it's because `tmpreaper` is trying to clean up.
> possible fix for apipe-ci/bats test failures

- lib/perl/Genome/Model/Build/Command/DetermineError.pm
Capturing this new date format seems more desirable than changing how
the logs are created for two reasons:
1) changing how the logs are created would require re-packaging and
re-deploying Flow
2) updating the recognizer to allow this date format allows us to
automatically determine historical errors
> Recognize new date format

- lib/perl/Genome/Model/DifferentialExpression.pm
Make cummerbund an optional part of the DE model workflow.
> DE - cummeRbund optional

- lib/perl/Genome/InstrumentData/AlignmentResult.pm
- lib/perl/Genome/InstrumentData/AlignmentResult.t
- lib/perl/Genome/InstrumentData/AlignmentResult_regenerate.t
We need this for the QC framework so that they have a common interface with MergedAlignmentResult.
> Make AlignmentResult an AlignedBamResult

- lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm
The rollback will have rolled back our creation.
> Don't call error_message on a deleted object.

- lib/perl/Genome/InstrumentData/Composite/Workflow.pm
They stopped having any functionality after #566.
> Remove disused properties.

- lib/perl/Genome/Model/ReferenceAlignment/Command/AdspExomeQcSummary.pm
- lib/perl/Genome/Model/ReferenceAlignment/Command/AdspQcSummary.pm
There's a lot of duplication between them... but with this change at least they should work!
> Call Correct Accessor in ADSP QC tools

- lib/perl/Genome/Site/SGMS.pm
Trying to create a lock on "/" causes a step to fail in https://github.com/genome/gms/issues/181
> update parent-dir for locks

- lib/perl/Genome/Command/DelegatesToResult.pm
- lib/perl/Genome/InstrumentData/Command/AlignReads.pm
- lib/perl/Genome/InstrumentData/Composite/Decorator.pm
- lib/perl/Genome/InstrumentData/Composite/Decorator.t
- lib/perl/Genome/InstrumentData/Composite/Decorator/Base.pm
- lib/perl/Genome/InstrumentData/Composite/Decorator/Qc.pm
- lib/perl/Genome/InstrumentData/Composite/Decorator/Qc.t
- lib/perl/Genome/InstrumentData/Composite/Strategy.pm
- lib/perl/Genome/InstrumentData/Composite/Strategy.t
- lib/perl/Genome/InstrumentData/Composite/Workflow.t
- lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/Align.pm
This is the means of hooking the QC Framework in #556 into the pipelines.
> Add decorators and a "QC" decorator to the Alignment Dispatcher

- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/ResolveInstDataPropertiesFromCgHub.pm
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/RetrieveSourcePathFromCgHub.pm
- lib/perl/Genome/Model/Tools/CgHub/Metadata.pm
- lib/perl/Genome/Model/Tools/CgHub/Metadata.t
GMT CG Hub: metadata can be created from XML and file.
> GMT CG Hub: metadata can be created from XML and file

- lib/perl/Genome/Model/Tools/BedTools.pm
- lib/perl/Genome/Model/Tools/Bwa/RunMem.pm
- lib/perl/Genome/Model/Tools/CopyNumber/Cnmops.pm
This PR modifies the way this GMT figures out the bedtools path.
> Figure out bedtools path better

- lib/perl/Genome/Model/Tools/Graph/MutationDiagram/MutationDiagram.pm
@apregier - can you look at this? Seems to do the right thing if I remove it, but I'm a little nervous it was in here for a reason that I'm not observing at the moment.
> remove skipping of transcripts with no domains.

- lib/perl/Genome/Sys/Lock/FileBackend.pm
Partial fix for [RT#105060](https://rt.gsc.wustl.edu/Ticket/Display.html?id=105060).
> fix lock directory being created with incorrect permissions

- lib/perl/Genome/InstrumentData/AlignmentResult.pm
This is an alternate solution to rt 105030 (instead of #645 )
> Limit merged results to ones that match all params

- lib/perl/Genome/Model/Tools/Analysis/Coverage/CoveragePlot.R
- lib/perl/Genome/Model/Tools/Analysis/Coverage/CoveragePlot.pm
- lib/perl/Genome/Model/Tools/Analysis/Coverage/CoveragePlot.t
I have updated the whole source codes according to Chris's comments. Module dependency is solved by re-writing subroutines for external module replacement.
> New Genome::Model::Tools::Analysis::Coverage::CoveragePlot added

- lib/perl/Genome/Config/AnalysisProject/Command/AddConfigBase.pm
- lib/perl/Genome/Config/AnalysisProject/Command/AddConfigFile.pm
- lib/perl/Genome/Config/AnalysisProject/Command/AddMenuItem.pm
- lib/perl/Genome/Config/AnalysisProject/Command/AddModel.t
- lib/perl/Genome/Config/AnalysisProject/Command/Base.pm
The new base class should help keep the docs and functionality in synch going forward!
> Create common base class and update docs for AnP config-adding commands

- lib/perl/Genome/Model/Tools/Vcf/EvaluateVcf.pm
- lib/perl/Genome/Model/Tools/Vcf/EvaluateVcf.t
- lib/perl/Genome/Model/Tools/Vcf/EvaluateVcfs.pm
- lib/perl/Genome/Model/Tools/Vcf/EvaluateVcfs.t
This is part 2 of a roll out to integrate the [VCF Evaluation scripts][1] within the genome codebase. The aim of this pull request is to get [evaluate_vcfs.pl][2] setup as a GMT. 
[1]: https://github.com/genome/vcf-evaluation
[2]: https://github.com/genome/vcf-evaluation/blob/master/evaluate_vcfs.pl
> GMT Integration of VCF Evaluation (part 2)

- lib/perl/Genome/Model/ClinSeq/Command/IdentifyLoh.pm
- lib/perl/Genome/Model/ClinSeq/Command/IdentifyLoh.t
This implements my last comment in #628.
The test data is updated to expect the files to be removed as well :smile:
> Delete the output files, not whatever is in the current directory.

- lib/perl/Genome/InstrumentData/AlignmentResult.pm
According to Nathan's suggestion, Scope::Guard is used to make sure unlocking when it goes out of scope upon return or exception.
> Use Scope::Guard to ensure unlocking

- lib/perl/Genome/Model/Tools/RefCov/Bam.pm
This was skipped in commit b7872dd8f95f3d3fc6f339954fec687a06b73cdb (prior to the redaction).
> Remove Long-Skipped RefCov Code

- lib/perl/Genome/InstrumentData/AlignmentResult.pm
- lib/perl/Genome/Sys/LockMigrationProxy.pm
- lib/perl/Genome/Sys/LockProxy.pm
It doesn't really save a lot of code but it still seems like an improvement.
> add Genome::Sys::LockProxy::unlock_guard()

- lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML
This build adds the TDG clinical trial to the DGIdb sources used in ClinSeq.
Ref - https://github.com/genome/dgi-db/commit/d5c1d813bc84febc37dfffd5a807b9f17bb8b3ca
> update clinseq blessed build

- lib/perl/Genome/InstrumentData/AlignmentResult.pm
The command "samtools view -H <bam>" runs very fast (about several seconds).
> Set keep_dbh_connection_open => 1

- genome-env-tests/test_helper.bash
Clone from the existing genome repo instead of getting an origin/master.
> clone from existing genome repo

- lib/perl/Genome/Model/ClinSeq/Util.pm
A small bug fix to find the exome somatic-variation build.
> use existing variable

- lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalsePositiveVcfBase.pm
This should help reassure that progress is being made, both for manual inspection and the heartbeat check.
Is every 100,000 lines a reasonable interval at which to report?  One build I looked at had 3.6 million lines, so this would be 36 updates for that one.
> Periodically report progress through the input VCF.

- lib/perl/Genome/Model/Build/Command/Start.pm
@tmooney pointed out that if something else were updating the model between
when we created the build and turned off `build_requested` then we would turn
off `build_requested` prematurely.  This changes it so we disable
`build_requested` (within a transaction) prior to even creating the build so
that the `build_requested` locking prevents this race.
> acquire build_requested lock before creating builds to start

- lib/perl/Genome/Model/Tools/Analysis/Coverage/CoveragePlot.R
I fixed a minor runtime bug in R source code.
> Minor bug fixation in R

- lib/perl/Genome/Disk/Allocation-permissions.t
Test was broken due to 'sys_umask' configuration value changing from
'0002' to '0007'.  Test is updated to test that write permissions are removed
not to test specific mode.
> update broken test

- lib/perl/Genome/WorkflowBuilder/Command.pm
- lib/perl/Genome/WorkflowBuilder/Detail/Operation.pm
- lib/perl/Genome/WorkflowBuilder/Detail/TypeMap.pm
- lib/perl/Genome/WorkflowBuilder/Event.pm
- lib/perl/Genome/WorkflowBuilder/Test/Command.t
- lib/perl/Genome/WorkflowBuilder/Test/Event.t
This should help the reference-alignment model-tests to pass.
> Workflowbuilder fixes

- lib/perl/Genome/Model/Tools/Bedpe/EvaluateBedpe.pm
- lib/perl/Genome/Model/Tools/Bedpe/EvaluateBedpe.t
How embarrassing - I was looking at the results of my script and realized it didn't make sense at all - because I labeled the statistic wrong.
> Fix wrongly labeled statistic

- lib/perl/Genome/Site/TGI/use-gscapp-before-works.t
This test is consistently failing in Jenkins, but I can't reproduce it myself.
> Print out diag info when the test fails

- lib/perl/Genome/Ptero/Wrapper.pm
If `_setup_logging()` is called and succeeds, then the `_teardown_logging()` function must be called or the wrapper will perpetually hang while waiting for annotate-log processes to spontaneously end (they never will).
> _teardown_logging when re-throwing exceptions

- lib/perl/Genome/Model/Command/Admin/FailedModelTickets.pm
Unstartable builds no longer generate Unstartable events, so this tool has been missing them entirely from its reports.
(Status is stored directly on builds these days, too, so there's no need to use the events as an intermediary.)
> Get failed/unstartable builds directly.

- lib/perl/Genome/Model/Build.pm
- lib/perl/Genome/Model/Build/Command/View.pm
Since this includes a code change in Genome::Model::Build, expect almost all of the tests to be run in the quick-tests phase.
> Ptero build view

- lib/perl/Genome/Model/Tools/Sv/AssemblyValidation.pm
Once again, chromosome names with `|`s were causing trouble.
> Assembly validation uses new shellcmd

- lib/perl/Genome/InstrumentData/Command.pm
remove the only_if_null to allow values to be updated and expand the exclude list
of things that should not be easily modifiable.
> InstData Update Command

- lib/perl/Genome/InstrumentData/AlignmentResult/Star.pm
- lib/perl/Genome/Model/Tools/Bowtie.pm
Do we still support/use the `Star` alignment module?
> Typofix: aliger => aligner

- lib/perl/Genome/InstrumentData/AlignmentResult.pm
- lib/perl/Genome/InstrumentData/AlignmentResult/Bwa.t
- lib/perl/Genome/InstrumentData/BamUtil/ClipOverlapResult.pm
- lib/perl/Genome/InstrumentData/Command/AlignReads.pm
Mostly removing old `FIXME`s.  Also something that never did anything.
> Cleanup in Genome/InstrumentData

- lib/perl/Genome/Config/AnalysisProject.pm
> Add "Deprecated" as a non-current status

- lib/perl/Genome/Ptero/workflow_tests/converge/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/converge/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json
This was causing quick tests to fail.
> Update test-data for Ptero sdk version 0.1.6

- lib/perl/Genome/Model/GenotypeMicroarray.pm
This line hadn't been updated since before the redaction!
> Fix Microarray dependent model check

- lib/perl/Genome/Model/Event/Build/ReferenceAlignment/BamQc.pm
- lib/perl/Genome/Model/Event/Build/ReferenceAlignment/BamQc.t
- lib/perl/Genome/Model/Tools/BioSamtools/ErrorRate.pm
I finally pulled it out of my homedir! :cat: :ribbon: :snake:
Depends on https://github.com/genome/genome-snapshot-deps/pull/43.
> Update BamQC to use packaged bam-errorrate

- lib/perl/Genome/Model/ReferenceAlignment/Command/GenotypeMicroarrayConcordance.pm
- lib/perl/Genome/Model/ReferenceAlignment/Command/GenotypeMicroarrayConcordance.t
- lib/perl/Genome/Model/Tools/BedTools.pm
add available versions for picard
add latest and available versions to bedtools
add available versions for bedtools
add default value for bedtools version
use bedtools version
> GM Concordance

- lib/perl/Genome/Model/Tools/Analysis/Concordance.pm
- lib/perl/Genome/Model/Tools/Analysis/Concordance.t
and cleaning up extraneous comments
> adding example file, changing 'reference-genome' param to 'reference-fasta',

- lib/perl/Genome/Config/AnalysisProject/Command/InactivateConfigFile.pm
- lib/perl/Genome/Config/AnalysisProject/Command/InactivateConfigFile.t
Initial revision of a command to inactivate config files.
> Inactivate AnP Config Files

- lib/perl/Genome/Model/SomaticValidation/Command/CoverageStats.pm
These are controlled by PP params in SomaticValidation.
> Remove unused variables and the logic to set them.

- lib/perl/Genome/Model/Tools/Analysis/MutationSpectrumSequenceContext.pm
This is an attempt to fix a sporadic diff in the test-builds when running this tool. Instead of writing to an existing file, we now write to a temporary file and copy that over at the end.
> Attempt to fix MutationSpectrumSequenceContext 

- lib/perl/Genome/Model/ClinSeq/Command/CreateMutationSpectrum.pm
> Add lsf param to CreateMutationSpectrum

- lib/perl/Genome/Db/Ensembl/Command/Import/Run.pm
I guess we haven't tried to run this since they became required!
> Add required users to Ensembl import runner.

- lib/perl/Genome/Db/Ensembl/AnnotationStructures.pm
Type information can be found here:
<http://www.gencodegenes.org/gencode_biotypes.html>
> Add scaRNA as a non-coding RNA biotype.

- lib/perl/Genome/Db/Ensembl/Command/Import/CreateAnnotationStructures.pm
Same idea as #943, but a different command!
> Add required-users for annotation structure importer.

- lib/perl/Genome/Interfaces/Comparable/Command/Diff.pm
- lib/perl/Genome/Model/SomaticValidation/Command/AlignmentStatsSummary.pm
- lib/perl/Genome/Model/SomaticValidation/Command/CoverageStatsSummary.pm
- lib/perl/Genome/Process/Command/DiffBlessed.pm.YAML
- lib/perl/Genome/VariantReporting/Command/Wrappers/GoldEvaluation.pm
- lib/perl/Genome/VariantReporting/Command/Wrappers/GoldEvaluation.t
- lib/perl/Genome/VariantReporting/Command/Wrappers/ModelPairFactory.pm
- lib/perl/Genome/VariantReporting/Command/Wrappers/ModelReport.pm
- lib/perl/Genome/VariantReporting/Command/Wrappers/ModelReport.t
- lib/perl/Genome/VariantReporting/Command/Wrappers/TestHelpers.pm
- lib/perl/Genome/VariantReporting/Command/Wrappers/Utils.pm
These changes are needed to get consistent process outputs from the cle regression test process.
> Trio process fixes

- lib/perl/Genome/Db/Ensembl/AnnotationStructures.pm
Add translated_unprocessed_pseudogene to the list of coding_pseudogene biotype classes
> translated_unprocessed_pseudogene added to AnnotationStructures

- lib/perl/Genome/Db/Ensembl/AnnotationStructures.pm
> Revert "translated_unprocessed_pseudogene added to AnnotationStructures"

- lib/perl/Genome/Db/Ensembl/AnnotationStructures.pm
Several new gene biotypes added to the AnnotationStructures biotype class map.
> More annotation structure updates to biotype map.

- lib/perl/Genome/Config/AnalysisProject/Command/AddModel.t
- lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.t
- lib/perl/Genome/Model.pm
- lib/perl/Genome/Model/Build.pm
- lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
- lib/perl/Genome/Model/GenotypeMicroarray.pm
- lib/perl/Genome/Model/ReferenceAlignment.pm
If these models are truly not wanted, running new builds for them is merely a waste of resources!
> Disabled configs imply disabled models

- lib/perl/Genome/Model/ClinSeq/Command/IdentifyLoh.pm
Reverts genome/genome#969
We can't use a local temporary directory as the output location for a workflow.  The LSF jobs that are spawned almost always won't be able to read that directory.  (Since this causes jobs to fail in pre-exec in Flow, they sit in PENDing state forever.)
> Revert "ClinSeq::LOH - Write results to temp dir first."

- lib/perl/Genome/Site/TGI/CleTest.t
The blessed process was updated in #965.
> Update CLE test to match updated blessed process.

- lib/perl/Genome/Model/Tools/FastTier/MakeTierBitmasks.pm
Like #945, this adds user data to the SR construction.  It also makes the `build` parameter non-optional, since it is used to get this user data.
> Add required-users for fast-tier bitmask generation.

- lib/perl/Genome/Model/Command/Admin/CleanupSucceeded.pm
This was missing opportunities to abandon failures and potentially too eagerly abandoning Unstartable builds.
> CleanupSucceeded considers the status of the newest non-abandoned build.

- lib/perl/Genome/Db/Ensembl/AnnotationStructures.pm
@obigriffith  is working on an import of mouse 79_38.  This PR is to add new annotation structures found in the mouse 79_38 GTF.
> Add new annotation structures found in mouse 79_38 import.

- lib/perl/Genome/Model/ImportedAnnotation.pm
> Pass build to tiering command so user info is available.

- lib/perl/Genome/Model/Command/Admin/FixOrphanedAllocationsForDv2Results.pm
> Make FixOrphanedAllocationsForDv2Results run on multiple builds

- lib/perl/Genome/Model/Tools/FastTier/MakeTierBitmasks.pm
Additional users hash to complement #991
> Add another users hash to the annotation result get_or_create

- lib/perl/Genome/VariantReporting/plan_files/gold_germline_report_indels.yaml
- lib/perl/Genome/VariantReporting/plan_files/gold_germline_report_snvs.yaml
- lib/perl/Genome/VariantReporting/plan_files/gold_somatic_report_indels.yaml
- lib/perl/Genome/VariantReporting/plan_files/gold_somatic_report_snvs.yaml
This brings in additional changes from the ad-hoc space needed to get useful gold reports. @indraniel - Can you review and ensure I have brought over all the necessary changes?
> Gold report

- lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
* Now with matching parentheses!
* Don't bother printing out zeroes.
> Tweaks to output of number of builds abandoned by ModelSummary

- lib/perl/Genome/Model/Tools/Ensembl/TranscriptInfo.pm
Iterate over all slices and use the toplevel coord system rather than chromosome and supercontig slices.
@apregier please take a look if you have the time.
> transcript-info use toplevel Ensembl coord system

- lib/perl/Genome/Model/ImportedAnnotation.pm
- lib/perl/Genome/Model/Tools/FastTier/MakeTierBitmasks.pm
- lib/perl/Genome/Model/Tools/FastTier/TierBitmasks.pm
Subroutines in bitmask tier creation from @ernfrid.
Make the ucsc directory for tiering optional.
Default behavior is all coding tier1 and the rest in tier3.  tier2 and tier4 are empty.
This PR will have to be manually merged with #991 and #992.
> GRCh38 make tier bed/bitmask files

- lib/perl/Genome/Model/Tools/Vcf/EvaluateVcf.pm
A couple of items to make the evaluate-vcf command more flexible outside of its original context.
> Evaluate vcf

- lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm
Instrument data id and merged result id are added into error message.
> Show more info on error message to help troubleshooting

- lib/perl/Genome/Timeline/Event/AnalysisProject.pm
Add valid_value for Deprecated AnP status.
> Deprecated AnP status Timeline event.

- lib/perl/Genome/Search/Queue.t
This test uses a nonsensical pattern:
* create a software transaction
* commit the lowest-level Context (inside the dedup functionality)
* roll back the software transaction
Since the guts of Genome::Search::Queue::dedup() make a low-level commit,
the whole test needs to operate on that level.
An impending UR PR will make the old behavior throw an exception
> Fix the Search Queue test

- lib/perl/Genome/Site/TGI/Extension/Sys.pm
Better solutions than this one have been proposed, but this is quick and should ameliorate the problem!
> Wait 10s before checking status of LSF jobs again.

- lib/perl/Genome/Model/Tools/Vcf/Convert/Indel/Bed.pm
The header doesn't have and entry for the INFO field TYPE
> Create a valid vcf

- lib/perl/Genome/Model/ClinSeq.pm
After this PR, all files in the dgidb folders are ignored by diff.
> Add a dgidb file to files ignored by diff.

- lib/perl/Genome/InstrumentData/Composite/Workflow.t
- lib/perl/Genome/Test/Factory/InstrumentData/AlignmentResult/Merged/Speedseq.pm
I'll be adding another test in a subsequent PR that also uses this Factory.  (Splitting this out to reduce the size of that PR.)
> Create a Test Factory for speedseq results.

- etc/genome/spec/ptero_lsf_service_url.yaml
- lib/perl/Genome/Model/Tools/Relationship/BackfillPolymuttVcf.pm
- lib/perl/Genome/Model/Tools/Relationship/HeterozygousDominant.pm
- lib/perl/Genome/Model/Tools/Relationship/HomozygousRecessive.pm
- lib/perl/Genome/Model/Tools/Relationship/MergeAndFixVcfs.pm
- lib/perl/Genome/Model/Tools/Relationship/RunPolymutt.pm
- lib/perl/Genome/Ptero/TestCommand/ParamAppender.pm
- lib/perl/Genome/Ptero/ToJSON.t
- lib/perl/Genome/Ptero/ToJSONForProcess.t
- lib/perl/Genome/Ptero/workflow_tests/converge/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json
- lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json
- lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json
- lib/perl/Genome/Sys/LSF/ResourceParser.pm
- lib/perl/Genome/Sys/LSF/ResourceParser.t
- lib/perl/Genome/Utility/LSFResourceParser.pm
- lib/perl/Genome/Utility/LSFResourceParser.t
- lib/perl/Genome/WorkflowBuilder/Command.pm
These tests will not pass until the perlSDK package is updated, they pass when PERL5LIB points at local perl-sdk deployment.  I'll have 'ci test this' when the perlSDK package has been updated.
> Genome ptero lsf integration

- lib/perl/Genome/Model/Build/ReferenceSequence.pm
(This is similar to how it is done in `Genome::Disk::Volume`.)
> Use Filesys::Df to get available KB

- lib/perl/Genome/Model/Build.pm
This allows using `WorkflowBuilder` to construct the workflow for a `Build`.
> Changes to handle either a Workflow::Model or a G::WorkflowBuilder::DAG.

- lib/perl/Genome/Model/Tools/Vcf/EvaluateVcf.pm
If the evaluation has already been run and we just want to
get the stats, we don't need to re-run everything, which takes
a while.  Detect this situation if the compare.txt file exists with
size.
The disadvantage here is that if you actually do want to rerun (e.g.
something has changed), it may not do what you expect (it does print
a debug message that results are just being parsed).
Previously, it would crash when trying to create a symlink that
already existed.
> Allow evaluation to be re-parsed

- lib/perl/Genome/InstrumentData/AlignmentResult.pm
- lib/perl/Genome/InstrumentData/Solexa.pm
There's a [support request](https://rt.gsc.wustl.edu/Ticket/Display.html?id=108692) where the filehandle creation fails.  Hopefully including `$!` will help elucidate the problem.
> Alignment print error opening groups file

- lib/perl/Genome/Qc/Tool/Picard/CalculateHsMetrics.pm
This updates the `CalculateHsMetrics` Qc tool to support merged alignment results.
> CalculateHsMetrics Supports Merged Results.

- lib/perl/Genome/InstrumentData/AlignmentResult/Star.pm
Add software result users for STAR aligner.
> Add software result users for STAR aligner.

- lib/perl/Genome/Model/Build/ReferenceSequence/Converter.pm
- lib/perl/Genome/Model/Build/ReferenceSequence/Converter.t
Missed a few additional places where this data should have been tested using defined rather than truth.
> missed some defines

- lib/perl/Genome/Test/Command/RunModelTest.pm
This command runs a model test but does not:
- alter your environment in (i.e. setting a software result test name)
- determine what version of perl to run
- email anybody
> Added 'genome test run-model-test' command

- lib/perl/Genome/Model/Tools/Picard.pm
This temporary data collection was added in #573.
> Remove _collect_call_info from GMT Picard.

- lib/perl/Genome/Model/SingleSampleGenotype/Command/HaplotypeCaller.pm
This is an `is_many` property, so be ready for multiple values!
> Fix list evaluation in scalar context.

- lib/perl/Genome/Model/SingleSampleGenotype.pm
CQID needs these to work with input objects.
> Add adders to SingleSampleGenotype Model.

- lib/perl/Genome/Disk/Allocation.pm
- lib/perl/Genome/Disk/Command/Allocation/Export.pm
- lib/perl/Genome/Disk/Detail/Allocation/Copier.pm
- lib/perl/Genome/Disk/Detail/Allocation/Unarchiver.pm
- lib/perl/Genome/Timeline/Event/AllocationEventType.pm
Initial revision of copy/export commands for allocations.
> Export/Copy Allocations to 'ad hoc' disk

- lib/perl/Genome/Sys/LSF/bsub.pm
- lib/perl/Genome/Sys/LSF/bsub.t
Then I can track down the sources and move them to different queues
> Notify me when apipe-builder uses the apipe queue

- lib/perl/Genome/Model/Tools/Tcga/Sdrf.pm
This is bugfix for https://github.com/genome/genome/pull/1144
> TCGA Priorities: Put lookup hash by bam base name in cache

- lib/perl/Genome/Model/Tools/Tcga/CreateSubmissionArchive.pm
- lib/perl/Genome/Model/Tools/Tcga/Sdrf.pm
Refer to https://jira.gsc.wustl.edu/browse/APIPE-3339. There is need to create sdrf file without time consuming vcf dump. This needs early merge.
> TCGA Priorities: Add dump_vcfs option to create sdrf file only

- lib/perl/Genome/Site/TGI/CleTest.pm.yaml
- lib/perl/Genome/Site/TGI/CleTest.t
This is an update to the CLE Test and must be approved by the Medical Director of the CLE
> Update CLE Test

- lib/perl/Genome/Config/AnalysisProject/Command/Reprocess.pm
- lib/perl/Genome/Config/AnalysisProject/Command/Reprocess.t
Allow the reprocessing of select instrument data for an AnP.
> AnP Reprocess

- lib/perl/Genome/Config/AnalysisProject/Command/Complete.pm
- lib/perl/Genome/Config/AnalysisProject/Command/Complete.t
- lib/perl/Genome/Config/AnalysisProject/Command/Deprecate.pm
> Analysis Project Command : Complete

- lib/perl/Genome/Model/Tools/DetectVariants2/Breakdancer.pm
A future next step might be to add the call to `MergeFiles` into the workflow itself.
> Breakdancer uses WorkflowBuilder for parallel-by-chromosome

- lib/perl/Genome/Model/Tools/DetectVariants2/MethRatio.pm
- lib/perl/Genome/Model/Tools/DetectVariants2/Pindel.pm
- lib/perl/Genome/Model/Tools/DetectVariants2/PindelSingleGenome.pm
- lib/perl/Genome/Model/Tools/DetectVariants2/WorkflowDetectorBase.pm
This converts both `Pindel` and `MethRatio`.
> DV2 "Workflow Detectors" use WorkflowBuilder

- lib/perl/Genome/Model/Tools/Varscan/SomaticFilterWorkflow.pm
This is run as part of `ClinSeq`'s `IdentifyLoh` step.
> Update the Varscan SomaticFilterWorkflow to use WorkflowBuilder.

- lib/perl/Genome/Model/Tools/BamQc/Run.pm
This was already converting to WorkflowBuilder to run the workflow; now it builds that way, too!
> BamQc builds its workflow with WorkflowBuilder.

- lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalsePositiveVcfBase.pm
(This follows on the heels of #1193.)
> Convert FalsePositiveVcf filter to WorkflowBuilder.

- lib/perl/Genome/Disk/Detail/Allocation/Unarchiver.pm
This PR adds a single character, and it's whitespace.
> Separate the command and the word "via" with a space.

- lib/perl/Genome/Model/Tools/Vcf/Convert/Indel/Pindel.pm
I don't know why this converter contains a workflow at all for its single step, although it has been present since the original version of the converter.
> Pindel VCF Converter uses WorkflowBuilder.

- lib/perl/Genome/Model.pm
- lib/perl/Genome/Model/Build/ExecuteBuildWrapper.pm
No ProcessingProfiles still implement this method.
> Remove ProcessingProfile-based _execute_build support

- lib/perl/Genome/Model/Build.pm
This was added "temporarily" in 2010.
> Remove disused method for subclassing by sequencing_platform.

- lib/perl/Genome/Model/Build/Command/Export.pm
Hot on the heels of #1219 comes these several additional changes to build export.  One real-world use of this command completes for the first time on this latest version.
> Further Refinements to Build Export

- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.pm
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.t
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Helpers.pm
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Role/WithWorkingDirectory.pm
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Role/WithWorkingDirectory.t
Unzip fastqs
Check fastq line counts 
Verify no reads lost
Remove input fastqs in working dir
> Import Fastq Updates

- lib/perl/Genome/Model/Build.pm
This will ensure that calling results returns a unique list.
> Change G::M::B results to use result_associations instead of result_users

- lib/perl/Genome/Model/Event/Build/ReferenceAlignment/RunReports.pm
This completes the review task suggested on 18 Nov 2009.
> ReferenceAlignment: Remove references to ReferenceCoverage report

- lib/perl/Genome/Model/Tools/Text.pm
The files under this were removed in 1bc1810154d2bebd11321dd2b833dd54cff62df8.
> Remove head of "Text" GMT tree.

- lib/perl/Genome/InstrumentData/AlignmentResult.pm
(The alternative here would be to remove the `AlignmentSummary` GMT tree.)
> AlignmentResult uses the AlignmentSummary GMT.

- lib/perl/Genome/Model/SomaticValidation.pm
This was inspired by resolving a long standing JIRA issue, APIPE-2849.  However, @acoffman  and @susannasiebert  this is a very similar problem to how ClinSeq interfaces with somatic model types.
> Common somatic interface to the tumor/normal samples.

- lib/perl/Genome/Model/Build.pm
It's very hard to start new builds without being able to Schedule them!
> Add Scheduled as valid build status.

- lib/perl/Genome/InstrumentData/Command/Import/Basic_bam_multi_groups.t
- lib/perl/Genome/InstrumentData/Command/Import/Basic_sra.t
- lib/perl/Genome/InstrumentData/Command/Import/Launch.t
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/SplitBamByReadGroup.pm
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/SplitBamByReadGroup.t
Mixed singleton read 1/2s in a bam together causes problems in genome. Import them separately.
> InstData Import: Split by read into paireds, read1s and read2s

- lib/perl/Genome/Model/SomaticVariation/Command/CreateReport.pm
Allow for zero size variant files in the Create Report step of Somatic Variation models.
> Zero size variants in CreateReport

- lib/perl/Genome/Model/Build/ReferenceSequence.pm
Add a UCSC tiering directory for GRCh38 reference sequence build.
> Tiering for GRCh38

- lib/perl/Genome/Model/ClinSeq/Command/DumpIgvXml.pm
- lib/perl/Genome/Model/ClinSeq/Command/GetBamReadCounts.pm
- lib/perl/Genome/Model/ClinSeq/Command/SummarizeCnvs.pm
- lib/perl/Genome/Model/SomaticVariation/Command/DumpIgvXml.pm
- lib/perl/Genome/Model/Tools/Analysis/ResolveIgvReferenceName.pm
- lib/perl/Genome/Model/Tools/CopyNumber/CnView.pm
- lib/perl/Genome/Model/Tools/Varscan/SomaticFilterWorkflow.pm
Contains fixes for clin-seq to be able to work on hg38. Incorporates suggestions from #1292 which can be closed now.
> clinseq fixes for hg38

- lib/perl/Genome/Model/Build.pm
This is normal for newly started jobs, so report it and move along.
> Don't die in HeartbeatCheck if no PIDs Found.

- lib/perl/Genome/Command/PteroWorkflowMixin.pm
This corrects an omission for the new column addition in #1316.
> PteroWorkflowMixin: Pass correct number of parameters in the "else" cases as well.

- lib/perl/Genome/Model/Build.pm
This heartbeat code is pretty ugly. It seems like it should be split out into its own module... but at least with this PR it works on builds run with PTero!
I'm definitely a novice at querying PTero; I'd be quite happy to learn of better ways to get the information.
> Support Heartbeat Check for PTero-based Builds.

- lib/perl/Genome/Utility/IO/SeparatedValueReader.pm
use Text::CSV to parse CSV lines rather than simple split.
> True CSV parsing support.

- lib/perl/Genome/Model/Tools/PooledBac/RunBlast.t
Fix the old path to the new fasta file path.
> fix the path.

- lib/perl/Genome/Model/ClinSeq/Command/TophatJunctionsAbsolute.pm
This fixes issues in ClinSeq where the path to the junctions file is currently incorrectly resolved.
> Use Genome::Utility

- lib/perl/Genome/Model/Build.pm
I'm not super interested in continuing to receive mail every time prod-builder starts or completes a build :smile:
> Don't send out build reports for any production users.

- lib/perl/Genome/Model/Tools/PooledBac/Run.t
> update the config file that uses sata420.

- lib/perl/Genome/Db/Ucsc/Command/Base.pm
- lib/perl/Genome/Db/Ucsc/Command/DbSnp.pm
- lib/perl/Genome/Db/Ucsc/Command/GapList.pm
- lib/perl/Genome/Db/Ucsc/Command/RepeatMasker.pm
- lib/perl/Genome/Db/Ucsc/Command/SegDup.pm
Add build38 options for downloading SV annotation files.
> Add build38 options for downloading SV annotation files.

- etc/genome/spec/lsf_resource_dv2_speedseq_sv.yaml
- lib/perl/Genome/Model/Tools/DetectVariants2/SpeedseqSv.pm
- lib/perl/Genome/Model/Tools/DetectVariants2/SpeedseqSv.t
A few changes to allow the SpeedseqSv DV2 module to run within a build.
> DV2 : Speedseq Sv

- lib/perl/Genome/Model/Tools/Manta.pm
- lib/perl/Genome/Model/Tools/Manta.t
- lib/perl/Genome/Model/Tools/Manta/Base.pm
- lib/perl/Genome/Model/Tools/Manta/Base.t
- lib/perl/Genome/Model/Tools/Manta/Config.pm
- lib/perl/Genome/Model/Tools/Manta/Config.t
- lib/perl/Genome/Model/Tools/Manta/Run.pm
- lib/perl/Genome/Model/Tools/Manta/Run.t
Initial revision of new tool tree and commands to run the Manta SV caller.
> New GMT : Manta structural variant caller

- lib/perl/Genome/Model/SmallRna.pm
- lib/perl/Genome/Model/SmallRna/Command/ParallelWorkflow.pm
- lib/perl/Genome/Model/SmallRna/Command/SmallRnaWorkflow.pm
This pipeline hasn't been run in awhile and the workflow modules themselves have been mostly neglected since 2012, but I heartell it's not on the list for removal.  So, here's a minimal change to make it use `WorkflowBuilder` instead of `Workflow` (and convert tabs to spaces!  Use `?w=1` for easier diff viewing).
> SmallRna uses WorkflowBuilder

- lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML
- lib/perl/Genome/Model/ClinSeq.pm
- lib/perl/Genome/Model/ClinSeq/Command/Converge/SnvIndelReport.pm
- lib/perl/Genome/Model/ClinSeq/Command/Converge/SnvIndelReport.t
- lib/perl/Genome/Model/ClinSeq/Command/CreateMutationDiagrams.pm
- lib/perl/Genome/Model/ClinSeq/Command/MakeCircosPlot.pm
I made this a WIP because this PR results in changes to the ClinSeq build outputs so a new blessed build is needed. The diffs have been documented here: https://jira.gsc.wustl.edu/browse/CI-99. Once I get the ok for the diffs, a new blessed build will become part of this PR.
For the time being I wanted to open up the code review discussion.
This PR closes #1363.
> WIP: Refactor ClinSeq workflow to use SnvIndelReport instead of ImportSnvsIndels

- lib/perl/Genome/Model/GenotypeMicroarray.t
This should've been part of #1337, but it was missed then.
> Remove unused include in GenotypeMicroarray.t

- lib/perl/Genome/Model/ClinSeq/Command/SummarizeCnvs.t
Here's another test affected by the deletion of abandoned data.
> ClinSeq SummarizeCnvs uses test data for its test.

- lib/perl/Genome/Model/Tools/CopyNumber/CnView-fast.t
- lib/perl/Genome/Model/Tools/CopyNumber/CnView-slow.t
These tests are still ugly, but these changes minimally update them to work again.
> CopyNumber CnView: Use test CNV data.

- lib/perl/Genome/Db/Ensembl/Command/Run/Base.pm
Add dog reference as a valid value.
> VEP for dog genome.

- lib/perl/Genome/Model/ClinSeq/Command/SummarizeModels.t
- lib/perl/Genome/Model/ClinSeq/TestData.pm
Here's another test that has newly fallen victim to the deletion of old production data.
> ClinSeq ModelSummary test uses Test Data

- lib/perl/Genome/Model/Tools/DetectVariants2/Polymutt.pm
- lib/perl/Genome/Model/Tools/DetectVariants2/Polymutt.t
This replaces the test as well, since the old one depended on deleted production data and was never really run in practice.
> DV2 Polymutt uses WorkflowBuilder

- etc/genome/spec/lsf_resource_review_variants.yaml
- lib/perl/Genome/Model/SomaticValidation/Command/ReviewVariants.pm
Make the review variants lsf resource configurable.
> Review Variants LSF Resource

- lib/perl/Genome/Ptero/Wrapper.pm
- lib/perl/Genome/WorkflowBuilder/Command.pm
This was being set inside the bsubbed `genome ptero wrapper` command.  Now it will instead be set in the environment for when that `genome ptero wrapper` command is bsubbed.
> LSB_SUB_ADDITIONAL needs to be set sooner.

- lib/perl/Genome/Model/Tools/Joinx/SafeVcfMerge.pm
These should have been removed as part of #1358.
> Remove unused includes in SafeVcfMerge.

- lib/perl/Genome/Model/Tools/Speedseq/Base.pm
- lib/perl/Genome/Model/Tools/Speedseq/Base.t
Otherwise just pass an empty string
> Only pass through boolean tool argument if true

- lib/perl/Genome/Model/Build.pm
- lib/perl/Genome/Model/Build/Command/DetermineError.pm
- lib/perl/Genome/Model/Build/Command/DetermineError/PteroHelper.pm
- lib/perl/Genome/Model/Build/Command/DetermineError/WorkflowHelper.pm
- lib/perl/Genome/Ptero/Utils.pm
This is one of the primary means for users to self-diagnose failures these days, so it'd be nice if it works should they run their builds wtih PTero!
> DetermineError Handles PTero Builds

- lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML
This should be the last change to make before enabling the SSG automated model test.
> Add a blessed SSG test build.

- lib/perl/Genome/Model/RnaSeq/DetectFusionsResult/Chimerascan/FixedReadLength/Index.t
- lib/perl/Genome/Model/Tools/Annotate/Sv/Combine.t
I accidentally deleted a few annotation build directories that were in use by these tests.  This updates the test to use others that still exist. 😄 
I'm not keen on the hard-coded path, but this maintains the status quo.
> Update annotation builds to some that exist.

- lib/perl/Genome/Model/Tools/Sx/Split/ByNs.pm
- lib/perl/Genome/Model/Tools/Sx/Split/ByNs.t
use iterator style to get split seqs
change method for finding Ns to accomodate the max allowed characters in a regex
return gap info if requested
> SX Split By Ns UPDATE

- lib/perl/Genome/Model/Build/DeNovoAssembly/Abyss.t
- lib/perl/Genome/Model/Build/DeNovoAssembly/Allpaths.t
- lib/perl/Genome/Model/Build/DeNovoAssembly/Newbler.t
- lib/perl/Genome/Model/Build/DeNovoAssembly/Soap.t
- lib/perl/Genome/Model/Build/DeNovoAssembly/Velvet.t
- lib/perl/Genome/ProcessingProfile/DeNovoAssembly.pm
- lib/perl/Genome/ProcessingProfile/DeNovoAssembly.t
I haven't heard it's okay to remove this pipeline, so here's an update to use WorkflowBuilder!
> DeNovoAssembly pipeline uses WorkflowBuilder.

- lib/perl/Genome/Model/Tools/Hgmi/DumpProtein.pm
- lib/perl/Genome/Model/Tools/Hgmi/SendToPap.pm
It's my understanding that these tools are still in active use for the next few months, so here's a PR to update them to `WorkflowBuilder`!
> `gmt hgmi` uses WorkflowBuilder

- lib/perl/Genome/Model/Tools/Annotate/ReferenceGenome.pm
This is somehow a part of ImportedAnnotation builds.  I'm not sure if it's really still needed, but converting it to `WorkflowBuilder` was faster than figuring that out 😄
> `gmt annotate reference-genome` uses WorkflowBuilder.

- lib/perl/Genome/Model/Build/SomaticInterface.pm
- lib/perl/Genome/Model/Build/SomaticValidation.pm
- lib/perl/Genome/Model/Build/SomaticVariation.pm
- lib/perl/Genome/Model/ClinSeq/Command/DumpIgvXml.pm
> Use tumor_bam and normal_bam subroutines instead of RefAlign builds

- lib/perl/Genome/Model/ProteinAnnotation.pm
- lib/perl/Genome/Model/Tools/Predictor/Ber.pm
- lib/perl/Genome/Model/Tools/Predictor/FastaChunker.pm
- lib/perl/Genome/Model/Tools/Predictor/WorkflowGenerator.pm
- lib/perl/Genome/Model/Tools/Predictor/WorkflowGenerator.t
I believe these are the last places in `Genome` using `Workflow::Simple` aside from our build start logic (and other open PRs).
> BER/Prediction Workflow uses WorkflowBuilder

- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Helpers.pm
This was converted to WorkflowBuilder in #1135.
> Remove unused Workflow helpers in InstrumentData Import.

- lib/perl/Genome/SoftwareResult/Command/DiskUsage.pm
- lib/perl/Genome/SoftwareResult/Command/DiskUsage.t
This is a slightly polished-up version of a script from past meetings.
> Command to summarize disk usage of SoftwareResults by Sponsor.

- lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/Align.pm
This error message came up today, and it would've been helpful to see why without having to reconstruct the situation!
While we're here, update the `die $self->error_message()` to use `$self->fatal_message()` instead.
> Add error to instantiation failure message.

- lib/perl/Genome/Model/MetagenomicComposition16s.pm
Another WorkflowBuilder conversion!
> Convert MC16s workflow generation to WorkflowBuilder.

- lib/perl/Genome/VariantReporting/plan_files/cle_indels_report.yaml
- lib/perl/Genome/VariantReporting/plan_files/cle_snvs_report.yaml
- lib/perl/Genome/VariantReporting/plan_files/cle_somatic_indels_report.yaml
- lib/perl/Genome/VariantReporting/plan_files/cle_somatic_snvs_report.yaml
Add n-callers and vaf-cutoff filters to cle snvs plan files and annotation-category filter to cle indels plan file.
> Update CLE plan files with new filters

- lib/perl/Genome/VariantReporting/Suite/BamReadcount/VafFilter.pm
Provide more info to vcf_description of vaf-cutoff filter
> Update vcf description with more info

- lib/perl/Genome/Site/TGI/CleTest.pm.yaml
- lib/perl/Genome/Site/TGI/CleTest.t
This is an update to the CLE regression test. Medical Director of the CLE, Dave Spencer, approved this.
> Update blessed process for CLE regression test

- lib/perl/Genome/Config/AnalysisProject/SubjectMapping/Command.pm
The lister is less friendly but more powerful than the view command.
> Institute a delete command and lister for subject mappings.

- lib/perl/Genome/Model/SmallRna/Command/ClusterCoverage.pm
- lib/perl/Genome/Model/Tools/Analysis/MutationSpectrumByStrand.pm
- lib/perl/Genome/Model/Tools/Analysis/MutationSpectrumSequenceContext.pm
- lib/perl/Genome/Model/Tools/Analysis/MutationSpectrumSequenceContextPvalue.pm
- lib/perl/Genome/Model/Tools/Analysis/PlotMultiMutationSpectrum.pm
- lib/perl/Genome/Model/Tools/Analysis/SummarizeMutationSpectrum.pm
- lib/perl/Genome/Model/Tools/Analysis/TelomereLength.pm
- lib/perl/Genome/Model/Tools/Assembly/VerifyAceFileIntegrity.pm
- lib/perl/Genome/Model/Tools/Crossmatch/Run.pm
- lib/perl/Genome/Model/Tools/EpitopePrediction/FrameShift.pm
- lib/perl/Genome/Model/Tools/EpitopePrediction/GenerateVariantSeq21merPanKey.pm
- lib/perl/Genome/Model/Tools/EpitopePrediction/GenerateVariantSequences.pm
- lib/perl/Genome/Model/Tools/EpitopePrediction/GetWildtype.pm
- lib/perl/Genome/Model/Tools/Fasta/Chunker.pm
- lib/perl/Genome/Model/Tools/Fasta/Deduplicator.pm
- lib/perl/Genome/Model/Tools/Fasta/FilterById.pm
- lib/perl/Genome/Model/Tools/Fasta/RemoveN.pm
- lib/perl/Genome/Model/Tools/Fasta/Synch.pm
- lib/perl/Genome/Model/Tools/Fastq/RemoveN.pm
- lib/perl/Genome/Model/Tools/Fastq/RemoveNPairwise.pm
- lib/perl/Genome/Model/Tools/Predictor/Ber/RunBlastp.pm
- lib/perl/Genome/Model/Tools/Sam/Deduplicator.pm
- lib/perl/Genome/Model/Tools/Sam/RemovePairedEnds.pm
- lib/perl/Genome/Model/Tools/Sam/ResurrectDuplicates.pm
- lib/perl/Genome/Model/Tools/Snp/Filters/Dtr3e.pm
- lib/perl/Genome/Model/Tools/Snp/Filters/GenerateFigure3Files.pm
- lib/perl/Genome/Model/Tools/Snp/Filters/ScaledBinomialTest.pm
- lib/perl/Genome/Model/Tools/Tcga/MergePerLaneSamFilesWorker.pm
This is the easy part of #1525. :smile:
> Remove "use Workflow;" from modules that didn't really use it.

- lib/perl/Genome/Model/RnaSeq.pm
This fixes an issue introduced in #1482.
> RNASeq: Create the operation before adding it.

- lib/perl/Genome/Model/Tools/Ensembl/Base.pm
> Use config to get DB connection details.

- lib/perl/Genome/Model/DifferentialExpression.pm
Not sure why this one wasn't already converted.
> Convert DifferentialExpression to WorkflowBuilder.

- lib/perl/Genome/Site/TGI/CleTest.pm.yaml
- lib/perl/Genome/Site/TGI/CleTest.t
This is an update to the CLE Test and must be approved by the Medical Director of the CLE. It needs early merge.
> Update blessed process for CLE test

- lib/perl/Genome/Model/Command/Admin/PurgeSoftwareResultsFromAnalysisProject.pm
add AnP name to the report summary.
> Purge Report with AnP Name

- lib/perl/Genome/Model/Tools/Vcf/Convert/Indel/GatkSomaticIndel.pm
I was persuaded by @brummett's comments in #1561.  This isn't likely to matter--in practice this runs once and isn't multi-threaded or re-entrant (and the header is parsed for each new file, obtaining the new values)--but it doesn't hurt anything!
> Use object properties instead of global variables to store positions.

- lib/perl/Genome/Model/DeNovoAssembly/Command/ExportAsGscProject.pm
- lib/perl/Genome/Model/DeNovoAssembly/Command/ExportAsGscProject.t
This was a home directory comand. I have converted and updated it to live in Genome. The command takes a work order (Genome::Proejct) and export finishing style projects.
> Export DeNovoAssembly Builds

- lib/perl/Genome/Model/Build/ReferenceSequence.pm
Set config to empty string or non-existent location to disable cache.  (This will fall back to original location if cache is temporarily unavailable as well.)
> Make it possible to disable local filesystem caching.

- lib/perl/Genome/Config/AnalysisProject/Command/View.pm
> Add separate flag to control display of inactive configs.

- lib/perl/Genome/InstrumentData/Solexa.t
One fewer file referencing `techd` volumes!
> Use test input for adapter file instead of hardcoded path.

- lib/perl/Genome/Config/AnalysisProject/Command/AddInstrumentData.pm
Allow the assignment of all instrument data to analysis projects regardless of class.
> Remove imported restriction to assiging instrument data.

- lib/perl/Genome/Model/Tools/Annotate/Sv/Combine.t
`/gsc/` is being cleaned up, and the other versions of these files are gone!
> Use Genome DB instead of hardcoded /gsc/ path.

- lib/perl/Genome/Model/Tools/Analysis/DumpIgvXmlMulti.pm
- lib/perl/Genome/Model/Tools/Validation/ProcessSomaticValidation.pm
Add hg38 and mm10 as example values for IGV references.
> Update IGV ref name example values.

- lib/perl/Genome/Site/TGI/CleTest.pm.yaml
- lib/perl/Genome/Site/TGI/CleTest.t
This needs early merge to make Jenkins cle_regression_test pass.
> update the blessed build for germline model

- etc/genome/spec/lsf_resource_dv2_strelka.yaml
- lib/perl/Genome/Model/Tools/DetectVariants2/Strelka.pm
This should match the number of jobs specified for `make` [in the detector](https://github.com/genome/genome/blob/3dec8bf28dbfe9f74e6006c2604b01d1237f0dc4/lib/perl/Genome/Model/Tools/DetectVariants2/Strelka.pm#L107).
> Specify four CPUs in Strelka request.

- lib/perl/Genome/Config/AnalysisProject/Command/DiskUsage.pm
Initial revision of command to report disk usage. WIP.
> AnP Disk Usage

- lib/perl/Genome/Model/SmallRna/Command/AnnotateCluster.t
The test files were deleted from the hardcoded paths in this test.  This updates the test to use files in the test data directory.
> Use files in test data directory.

- lib/perl/Genome/Model/ClinSeq/Command/CufflinksDifferentialExpression.t
- lib/perl/Genome/Model/ClinSeq/Command/CufflinksExpressionAbsolute.t
- lib/perl/Genome/Model/ClinSeq/Command/GetBamReadCounts.t
- lib/perl/Genome/Model/ClinSeq/Command/GetBamReadCountsMatrix.t
- lib/perl/Genome/Model/ClinSeq/Command/GetVariantSources.t
- lib/perl/Genome/Model/ClinSeq/Command/SummarizeBuilds.t
- lib/perl/Genome/Model/ClinSeq/Command/TophatJunctionsAbsolute.t
- lib/perl/Genome/Model/Tools/DetectVariants2/Combine/UnionSv.t
Writing tests using production data finally haunts all these tests!
> Disable tests that relied on now-deleted production data.

- lib/perl/Genome/Db/Ensembl/AnnotationStructures.pm
- lib/perl/Genome/InstrumentData/AlignmentResult_regenerate.t
I ran `genome-prove` from a Xenial VM, and these were a few compilation issues it found.
> Fix perl 5.22 compile errors

- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder/Bam.downsample.t
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder/Bam.t
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder/Fastq.t
- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Builder/Sra.t
- lib/perl/Genome/Model/RnaSeq.t.d/workflow.xml
- lib/perl/Genome/ProcessingProfile/DeNovoAssembly.t
- lib/perl/Genome/VariantReporting/Framework/TestHelpers.pm
- lib/perl/Genome/WorkflowBuilder/Detail/Operation.pm
- lib/perl/Genome/WorkflowBuilder/Test/Command.t
- lib/perl/Genome/WorkflowBuilder/Test/DAG.t
- lib/perl/Genome/WorkflowBuilder/Test/Event.t
Otherwise the order may vary, making the tests subject to failure depending on the environment.
> Sort attribute keys for Operation XML.

- lib/perl/Genome/Model/RnaSeq.pm
Removing the `u` from `given`.
> Spelling: s/guiven/given/.

- lib/perl/Genome/SoftwareResult/Command/SetTestName.pm
Option to abandon builds when setting software result test name.
> SR Test Name : Abandon Builds

- etc/genome/spec/lsf_resource_htseq_count.yaml
- lib/perl/Genome/Model/RnaSeq.t.d/workflow.xml
- lib/perl/Genome/Model/Tools/Htseq/Count.pm
initial revision of lsf_resource_htseq_count environment variable
> LSF Resource for HTSeq Count

- lib/perl/Genome/Model/RnaSeq/Command/ErccSpikeInQc.pm
- lib/perl/Genome/Model/Tools/BioSamtools/RepeatContent.pm
- lib/perl/Genome/Model/Tools/Manta/Base.pm
- lib/perl/Genome/Model/Tools/Manta/Base.t
- lib/perl/Genome/Model/Tools/Manta/Config.t
- lib/perl/Genome/Model/Tools/Transcriptome/ErccMapUnaligned.t
There are better ways to fix these I'm sure. I'm open to suggestions.
I currently have both locations gc13001 and gc2764 accessible until this PR makes it live.
> Update internal paths.

- lib/perl/Genome/InstrumentData/AlignmentResult.pm
Reduce the check for available disk from 20x the allocation to 2x
> Alignment Disk Check

- lib/perl/Genome/Model/ReferenceAlignment/Report/Summary.t
This report is still tested in the model test.
> Skip test that is dependent on live data.

- lib/perl/Genome/Model/Tools/DetectVariants2/Filter/VarscanHighConfidence.t
Not sure what this was supposed to be doing, but it hasn't been doing it since June 2011. 😄
> Remove commented-out code.

- lib/perl/Genome/Model/Tools/Speedseq/Base.pm
- lib/perl/Genome/Model/Tools/Speedseq/Base.t
- lib/perl/Genome/Test/Data.pm.d/HCC1395/create_bams.sh
The old location will be retired soon.
> Update speedseq path to newer disk array.

- lib/perl/Genome/Disk/Detail/Allocation/Mover.pm
- lib/perl/Genome/Model/Build/Command/MoveAllocations.pm
- lib/perl/Genome/Model/Build/ReferenceAlignment.pm
- lib/perl/Genome/Model/Build/RnaSeq.pm
- lib/perl/Genome/Model/Build/RunsDV2.pm
- lib/perl/Genome/Model/Build/SomaticValidation.pm
- lib/perl/Genome/Model/Build/SomaticVariation.pm
It might work for SSG builds... other types probably require more tweaks to their classes first.
This is an adaptation of #1698.
> Command to move "all" allocations for a build.

- lib/perl/Genome/Config/AnalysisProject/Command/UnarchiveInstrumentData.pm
- lib/perl/Genome/InstrumentData/Command/Unarchive.pm
- lib/perl/Genome/Model/Command/UnarchiveInstrumentData.pm
- lib/perl/Genome/Site/TGI/Extension/UnarchiveInstrumentData.pm
- lib/perl/Genome/Site/TGI/Observers.pm
intital revision of model command to unarchive instrument data.
> Unarchive Instrument Data 

- lib/perl/Genome/Model/Tools/ViromeEvent/Assignment/Report.pm
- lib/perl/Genome/Sys.pm
> Typo fix: add "y" to "directory".

- lib/perl/Genome/Model/Build/Command/MoveAllocations.pm
> Better handling of disk groups in `gmb move-allocations`.

- lib/perl/Genome/Model/Build/Command/MoveAllocations.pm
@chrisamiller this should resolve: https://jira.gsc.wustl.edu/browse/CIS-54
> Only attempt to move allocations that are still active.

- lib/perl/Genome/Model/SingleSampleGenotype/Command/CreateVcfTar.pm
- lib/perl/Genome/Model/SingleSampleGenotype/Command/CreateVcfTar.t
This adds a `manifest.md5` file to the archive that looks something like:
```
1.g.vcf.gz	90975a2dd157bc3c63e6ef17741b8521
2.g.vcf.gz	ca213ce5e3fe98ee221fc070378818e5
```
> Add a MD5 manifest file to the SSG VCF TAR file.

- lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML
More model test data has been reconstituted, so these new builds should help get more tests passing again.
> More test "blessed build" updates

- lib/perl/Genome/InstrumentData/Command/AlignmentResult/Convert/Base.pm
This version has been tested on converting a real BAM to CRAM, so it has a higher chance of working :smile:
> A few fixes to BAM <=> CRAM conversion

- lib/perl/Genome/Site/TGI/Synchronize/Classes/LimsProject.pm
- lib/perl/Genome/Site/TGI/Synchronize/Classes/LimsProjectInstrumentData.pm
- lib/perl/Genome/Site/TGI/Synchronize/Classes/LimsProjectSample.pm
The "project"-related classes still had a few issues left over--they haven't been encountered yet in production due to other outstanding issues with the synch process.
> More Postgres fixes for Synchronization classes

- lib/perl/Genome/Model/Build/SomaticValidation.pm
Add classes to move speedseq and qc results.
> Somval speedseq qc move

- lib/perl/Genome/Site/TGI/Command/SyncLimsAndGenome.t
- lib/perl/Genome/Site/TGI/Synchronize/Classes/Dictionary.t
The changes in #1766 caused a few tests to break.  These are the test changes that should've been included in that PR.
> Test Fixes for #1766.

- lib/perl/Genome/Model/Command/Rename.pm
This command was relevant to a ticket, so just a bit of code cleanup. :smile:
> Cleanup `genome model rename`.

- lib/perl/Genome/DataSource/Dwrac.pm
- lib/perl/Genome/DataSource/Oltp.pm
This fixes the error committing changes to misc_update.
> Set Dwrac and Oltp datasources to lowercase names.

- lib/perl/Genome/Model/Tools/Fasta/RemoveN.t
We don't really use it in this test, anyway, but at least this location exists!
> Point to test inputs for test FASTA file.

- lib/perl/Genome/Model/CwlPipeline.pm
- lib/perl/Genome/Model/CwlPipeline.t
The motivation here is to be able to use database objects as inputs instead of hardcoding file paths.
> Add a mechanism for specifying arbitrary object inputs in CwlPipeline.

- lib/perl/Genome/Model/CwlPipeline/Command/PrepForTransfer.pm
initial revision of CwlPipeline tool for prepping data transfer.
> CwlPipeline PrepForTransfer

- lib/perl/Genome/Model/Tools/Picard/ConcatenateMetricsFiles.pm
initial revision of ConcatenateMetricsFiles.pm
> Picard ConcatenateMetricsFiles

- lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Helpers.pm
Use the GMT to run samtools to ensure a standard version is used.
> GMS Import use GMT samtools for flagstat

- lib/perl/Genome/Config/AnalysisProject/Command/DiskGroupUsage.pm
- lib/perl/Genome/Disk/Group.pm
initial revision. Performance and user interface suggestions are welcome.
Main use case, is CIS-241.
> AnP Disk Group Usage

- lib/perl/Genome/Disk/Detail/Allocation/Mover.pm
Remove existing new path if confirmed redundant with original path.
> Fix Allocation Move with Existing Path

- lib/perl/Genome/Model/Build/DeNovoAssembly.pm
- lib/perl/Genome/Model/Build/DeNovoAssembly.t
> DeNovoAssembly

- lib/perl/Genome/Model/Build.pm
> Don't consider purging results without allocations.

- lib/perl/Genome/Model/CwlPipeline/Command/PrepForTransfer.pm
- lib/perl/Genome/Model/CwlPipeline/Command/PrepForTransfer.t
- lib/perl/Genome/Model/CwlPipeline/Command/PrepForTransfer.t.d/MANIFEST
> Add build ID and completion time to the PrepForTransfer MANIFEST.

- lib/perl/Genome/Model/CwlPipeline.pm
Hot on the heals of #1829 we have another location that needed fixing.
> Another place where we need "defined".

- lib/perl/Genome/Site/TGI/Extension/UnarchiveInstrumentData.pm
> Add experimental support for instrument data with tar.gz of FASTQs.

- lib/perl/Genome/Model/Tools/Htseq/Count-many.t
(The other two have been added to the test AnP.)
> Only two results for this test now... one was purged.

- lib/perl/Genome/Site/TGI/Synchronize/Classes/IndexIllumina.pm
It's no longer stored in a single place in the database, so we'll call their logic that examines the multiple choices.
> Ask the LIMS system where the BAM file is.

- lib/perl/Genome/Config/Profile.pm
- lib/perl/Genome/Config/Profile_input_data.t
If this is approved, we'll then need an interface for allowing a user to add the requisite subject mappings to the project.
> Allow a config to request subject mappings for input_data.

- lib/perl/Genome/Config/AnalysisProject/SubjectMapping/Command/Import/Base.pm
For best results, pass along the variable we want to use 😄
> Pass the label along correctly.

- lib/perl/Genome/InstrumentData/AlignmentResult/Bowtie.t
- lib/perl/Genome/InstrumentData/AlignmentResult/Bowtie_Novocraft_RtgMap/TestBase.pm
- lib/perl/Genome/InstrumentData/AlignmentResult/Bsmap.t
- lib/perl/Genome/InstrumentData/AlignmentResult/Clc.t
- lib/perl/Genome/InstrumentData/AlignmentResult/Crossmatch.t
- lib/perl/Genome/InstrumentData/AlignmentResult/MultiAligner.t
- lib/perl/Genome/InstrumentData/AlignmentResult/Novocraft.t
- lib/perl/Genome/InstrumentData/AlignmentResult/RtgMap.t
- lib/perl/Genome/InstrumentData/AlignmentResult/RtgMapx.t
- lib/perl/Genome/InstrumentData/AlignmentResult/Smalt.t
- lib/perl/Genome/InstrumentData/AlignmentResult/Ssaha2.t
These tests were storing their expected data outside of an allocation on sata828.  That's not going to work anymore, so use an official test data location.
> Use test data dir for AlignmentResult tests

- lib/perl/Genome/Model/Tools/ChimeraSlayer.pm
- lib/perl/Genome/Model/Tools/Nastier.pm
These data are in an allocation but not related to anything for now... so update their paths.  Should revisit later... (by removing the code entirely?).
> Update hardcoded paths in low-effort attempt to make tests pass.

- lib/perl/Genome/Model/Tools/Htseq/Count-many.t
> Typo: s/to/two/.

- lib/perl/Genome/Qc/Tool/TestHelpers.t.d/reference.fasta
This isn't really the best way to refer to this... but this is an expedient solution to fix a handful of tests for now.
> Update symlink to point to a different hardcoded path.

- lib/perl/Genome/Info/UCSCConservation.pm
I wanted to make these lookups, but compile-time database access is not okay.
> Lamely hardcode new paths for UCSC information for the Annotator.

- lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
This will make running with Cromwell go more smoothly :smile:
> Use a literal `$` and not a variable named `$"`.

- lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
The previous version only worked if everything was a `File` output and not, say, a `File[]` output.
> Handle array outputs and non-file outputs when staging results.

- lib/perl/Genome/Site/TGI/Command/ImportDataFromLims.pm
Now we can import FASTQ directories too!  Nothing in the system knows how to use them yet, but they're there.  For now, can reach the FASTQ directory using something like:
```perl
my $dir = $instrument_data->disk_allocation->absolute_path;
```
It's then up to the script to decide how to find/use the files it wants.  The existing `Genome::InstrumentData::Solexa` fastq methods don't know what to do with the newer-style directories yet.
> Support importing LIMS data that may or may not be BAMs.

- lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
- lib/perl/Genome/Model/CwlPipeline/Command/Run.t
This is one way to address genome/analysis-workflows#546.
To satisfy that issue, an AnP config would have something like this included:
```yaml
instrument_data_properties:
input_data:
output_prefix: sample_name
```
> Allow for an optional prefix when staging cromwell outputs.

- lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
It does't seem to like combining strings and numbers any more.
> Updates to the Cromwell Config to hopefully support version 37.

- lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
This change seems simple, but it'd be good to run a few test pipelines through it to make sure nothing was depending on the old behavior.
> Get a clean environment for cromwell jobs.

- lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
When requesting multiple cores, we'd really like them to be on the same host!
> Add "span[hosts=1]" to our LSF requests.

- lib/perl/Genome/Process.pm
- lib/perl/Genome/WorkflowBuilder/DAG.pm
* The bsub module expects "log_file" not "out_file".
* The DAG should process a simple workflow like an inline one.
> A few fixes for the "simple" backend.

- lib/perl/Genome/Command/CromwellWorkflowMixin.pm
- lib/perl/Genome/Cromwell.pm
- lib/perl/Genome/Model/Build/Command/View.pm
For CWL, this will be a lot more informative than the Ptero workflow (if one even exists)!
> Display Cromwell workflows in `genome model build view`.

- lib/perl/Genome/Model/Build/Command/AbandonPriorBuildsWithStatus.pm
They're already taken care of!
> Exclude "Abandoned" status from choices for builds to abandon.

- lib/perl/Genome/Library.pm
An attempt to handle the surprising variation in similarly named protocols!
> Convert protocol lists to regexes to account for lack of LIMS normalization.

- lib/perl/Genome/Config/AnalysisProject/Command/AddInstrumentData.pm
This seems like a useful "heads up" message  (that would have gotten my builds rolling a few hours sooner today 😄)
> add useful message about AnP hold state

- lib/perl/Genome/Model/Build/Command/Export.pm
Repeat of #1960 to apply to restored master branch.
> Clone of PR#1960

- lib/perl/Genome/Disk/Volume.pm
We don't have any sequence generators, anyway 😄
> Use UUIDs for new disk volumes.

- etc/genome/spec/lsf_user_group.yaml
This is where having a CwlPipeline model test would be a good idea.  It would've caught this...  I've monkey-patched this file into the current snapshot 😄
> Add missing lsf_user_group config spec file.

- lib/perl/Genome/Model/CwlPipeline/Command/ListDockerImages.pm
- lib/perl/Genome/Model/CwlPipeline/Command/ListDockerImages.t
- lib/perl/Genome/ProcessingProfile/Command/Describe.pm
Someone was asking me what versions of things ran in a given model, and it seemed like there should be an easier way to answer this question!
> New command to list docker images for a CWL pipeline build.

- lib/perl/Genome/Disk/Allocation-move.t
- lib/perl/Genome/Disk/Allocation.pm
Guess it's good I didn't make the new snapshot yet 🙃
> Fix typo: s/split_path/splitpath/.

- lib/perl/Genome/Site/TGI/Command/ImportDataFromLims.pm
Add some very site specific hard-coded stuff to help make imports from LIMS easier.
> Auto-connect production imports to remote volumes.

- lib/perl/Genome/Config/AnalysisProject/Command/PossibleVolumes.pm
I missed adding this to #1989.  It was sitting in my local copy but wasn't included in the commit... so here it is now!
> Add true value to end of module.

- lib/perl/Genome/FeatureList/Command/Merge.pm
This assumes that the two existing track names are the ones that exist for multi-tracked files. "Weird" tracks will still not work properly.
(Addresses BGAS-761.)
> Need to liftOver each track individually.

- lib/perl/Genome/Config/AnalysisProject/Command/Create.pm
- lib/perl/Genome/Config/AnalysisProject/Command/Create.t
Here's an alternative proposal to address #2000 that adds a prompt and a bit more text about interacting with the chooser.
> AnP Create: Now with More Interactivity!

- lib/perl/Genome/Config/AnalysisProject/Command/ConfigForInstrumentData.pm
Might be useful for testing new configs before adding them 🙂
> Optionally check instrument data against a supplied config file.

- lib/perl/Genome/Site/TGI/Command/ImportDataForWorkOrder.pm
This has been a minor annoyance for awhile.
> The help text claims it assigns all data, so let's do it.

- lib/perl/Genome/Disk/Command/Group/Create.pm
- lib/perl/Genome/Disk/Command/Volume/Create.pm
These UUIDs sure look like numbers to me, anyway 🙂
> Avoid warnings about numeric comparisons.

- lib/perl/Genome/Site/TGI/Command/ImportDataForWorkOrder.pm
This goes along with the just-merged #2022... Everything still mostly works without this tweak--it's just noisier than it needs to be 😄
> Only try to assign existing data when there is some.

- lib/perl/Genome/Model/Command/Services/ListBuildQueue.pm
This way a single project won't monopolize the queues when it has a job group configured that causes its builds to PEND even when slots are available for other builds to run.
The existing version was being particularly careful with its DB queries, so we'll want to keep an eye on performance to make sure calling `$model->analysis_project->id` isn't slowing stuff down too much.
> Add a per-AnP limit for scheduled builds.

- lib/perl/Genome/Site/TGI/Command/ImportDataFromLims.pm
The motivation behind this is so that CQID will decline to process data that fails to import.
> Only return true if we succeeded to process all instrument data.

- lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
> updating cloudize-workflow image

- lib/perl/Genome/Model/CwlPipeline/Command/Run.pm
Basically if a cloud VM already exists for our build then we'll treat it as our own and monitor it the usual way rather than start from scratch.
This is an incremental improvement, but it'd be good to also handle the case where the cloud VM has already completed before we restarted and we need to resume with pulling down the artifacts and outputs.
> Support restarting if our local build fails but the cloud VM is still running.

- lib/perl/Genome/Disk/Command/Allocation/Archive.t
- lib/perl/Genome/Disk/Detail/Allocation/Archiver.pm
We shouldn't try to clean up if we're erroring out before attempting the archive-especially if the data was already archived!
This is another PR that's easier to read with the `?w=1` URL parameter 🙂
> Only cleanup if we started to try to do work.
