lib/perl/Genome/Disk/Allocation.pm, lib/perl/Genome/Disk/Allocation.t
Otherwise we end up with summaries for whatever arbitrary directory we happened to be in.
=> Don't generate file summaries if we can't reach the target directory.

lib/perl/Genome/Model/Build/ReferenceAlignment.pm, lib/perl/Genome/ProcessingProfile/ReferenceAlignment.pm
These were replaced by the calculated+immutable version in 35a703b98545aca94785442a997a95fc2b9178ae (from before the redaction).
=> Remove old subclassification methods from ReferenceAlignment.

lib/perl/Genome/Model/Build/ReferenceAlignment.pm
The other method handles segment information, so it should work in more situations.
=> get_alignments() defers to existing method to get each alignment.

lib/perl/Genome/Model/Event/Build/ReferenceAlignment/AlignReads.pm, lib/perl/Genome/Model/Event/Build/ReferenceAlignment/AnnotateTranscriptVariants.pm, lib/perl/Genome/Model/Event/Build/ReferenceAlignment/DetectVariants.pm, lib/perl/Genome/Model/Event/Build/ReferenceAlignment/PrepareReferenceSequenceIndex.pm, lib/perl/Genome/Model/Event/Build/ReferenceAlignment/RunReports.pm
The model inputs might have changed from what's recorded on the build as we progress.  The builds then cannot be trusted.
=> Query reference alignment build directly for inputs.

lib/perl/Genome/Model/Build/Command/DetermineError.pm, lib/perl/Genome/Model/Build/Command/DetermineError.t, lib/perl/Genome/Sys.pm, lib/perl/Genome/Sys.t
Add iterate_file_lines() to Genome::Sys.  This method is an abstraction to work through a file one line at a time.
Convert Genome::Model::Build::Command::DetermineError to use it.
There are probably other places it could be used.
=> iterate_file_lines() 

lib/perl/Genome/InstrumentData/AlignmentResult/Bsmap.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Bsmap.t, lib/perl/Genome/Model/Event/Build/ReferenceAlignment/BamQc.pm, lib/perl/Genome/Model/Event/Build/ReferenceAlignment/BamQc.t
We were having trouble running `fillmd` on `bsmap` alignments. This disables `fillmd` and BamQc when the aligner is set to `bsmap`.
Would like input from @jasonwalker80 before merging.
=> Disable fillmd/BamQc for bsmap

lib/perl/Genome/Db/Cosmic/Command/Import.pm
As part of the ongoing SoftwareResult project `WithSavedResults` must be changed.  Since this importer is non-functional (`execute()` ends in `die()`), I propose to remove its inheritance instead of updating it to the new interface.
[My preferred course of action would be to merge PR #207, thus removing this module completely.]
=> Remove WithSavedResults from Genome::Db::Cosmic::Command::Import

lib/perl/Genome/Model/ClinSeq.pm
control the mapping quality and base quality parameters for
bam-readcounting for DOCM sites. We need to be as sensitive as possible
so set these to the absolute minimum.
=> add baseq, mapq parameters for docm bamrc.

lib/perl/Genome/Command/DelegatesToResult.pm, lib/perl/Genome/Model/Tools/Htseq/Count.pm, lib/perl/Genome/VariantReporting/Framework/MergeReports.pm
As suggested in #375, use the new implementation of `input_hash` from `Genome::Model::Tools::Htseq::Count` as the default for all `Genome::Command::DelegatesToResult`.
=> A default implementation of G:C:DelegatesToResult->input_hash()

lib/perl/Genome/Model/Build/Command/DetermineError.pm, lib/perl/Genome/Model/Build/Command/DetermineError.t
*We're after the very last `die()`-ish message in the log file.
*Use `above` so we test the current directory instead of stable.
=> Tweaks to DetermineError

lib/perl/Genome/FeatureList/Command/Import.pm, lib/perl/Genome/FeatureList/Command/Merge.pm, lib/perl/Genome/Model/Build/ReferenceSequence.pm, lib/perl/Genome/Model/Build/ReferenceSequence/Converter.pm
* Pass BED "track", "browser", etc. lines unmodified.
* A reference can now indicate it is a combination of multiple other references.
* Remove redundant print in `genome feature-list merge` since it will be printed by the import command.
=> Reference-Sequence Conversion Improvements for Merging

lib/perl/Genome/VariantReporting/Command/Wrappers/ModelPair.t, lib/perl/Genome/VariantReporting/Command/Wrappers/Trio.t, lib/perl/Genome/VariantReporting/Framework/Component/Base.pm, lib/perl/Genome/VariantReporting/Framework/Component/WithManyLibraryNames.pm, lib/perl/Genome/VariantReporting/Framework/Component/WithManySampleNames.pm, lib/perl/Genome/VariantReporting/Report/DocmReport.pm, lib/perl/Genome/VariantReporting/Report/FullReport.pm, lib/perl/Genome/VariantReporting/Suite/BamReadcount/ManySamplesVafInterpreter.pm, lib/perl/Genome/VariantReporting/Suite/BamReadcount/MaxVafObservedInterpreter.pm, lib/perl/Genome/VariantReporting/Suite/BamReadcount/MinCoverageObservedInterpreter.pm, lib/perl/Genome/VariantReporting/Suite/BamReadcount/VafInterpreter.t
Some care has to be taken for the SoftwareResult subclasses (reports)
since they have to be listed as 'input' or 'param' or the SoftwareResult
infrastructure will yell about ambiguous properties.
=> Make library_names and sample_names manditory inputs

lib/perl/Genome/Model/Build/ReferenceAlignment.pm, lib/perl/Genome/Model/Tools/CopyNumber/Cnmops.pm, lib/perl/Genome/Sys.pm
This is trying to correct the problem that region_of_interest_set_bed_file
writes to a build's data directory but is not run by the build.  This is a
common problem and this only covers when tiny occurence of it.
It also tries to address the fact that the failure left an empty file in place
and that this empty file was passed as an argument to downstream operations.
See [RT#103295][1] for full details.
/cc @jasonwalker80 @malachig 
[1]: https://rt.gsc.wustl.edu/Ticket/Display.html?id=103295
=> Proposed Fixes for RT#103295

lib/perl/Genome/Model/Tools/CopyCat/List.pm
The lister by default shows (and therefore "hints" at all the properties of the SoftwareResult, which triggers the giant non-performant query on SoftwareResult with joins on the Inputs and Params.  This change means more (but smaller) DB queries, which reduces the runtime of the command from several minutes to under three seconds.
=> Speedup CopyCat Annotation Lister

lib/perl/Genome/Process.pm, lib/perl/Genome/Process.t, lib/perl/Genome/Process.t.d/additional/file1, lib/perl/Genome/Process.t.d/additional/file2, lib/perl/Genome/Process.t.d/additional/file3, lib/perl/Genome/Process.t.d/changed/file1, lib/perl/Genome/Process.t.d/changed/file2, lib/perl/Genome/Process.t.d/cicular_symlink, lib/perl/Genome/Process.t.d/circular_symlink/file1, lib/perl/Genome/Process.t.d/circular_symlink/file2, lib/perl/Genome/Process.t.d/deep_symlink/file1, lib/perl/Genome/Process.t.d/deep_symlink/file2, lib/perl/Genome/Process.t.d/identical/file1, lib/perl/Genome/Process.t.d/identical/file2, lib/perl/Genome/Process.t.d/missing/file1, lib/perl/Genome/Process.t.d/original/file1, lib/perl/Genome/Process.t.d/original/file2, lib/perl/Genome/Process.t.d/symlink/file1, lib/perl/Genome/Process.t.d/symlink/file2, lib/perl/Genome/Process.t.d/symlink_to_symlink, lib/perl/Genome/VariantReporting/Command/CreateReport.t, lib/perl/Genome/VariantReporting/Command/CreateReport.t.d/expected_in_process/plan.yaml, lib/perl/Genome/VariantReporting/Command/CreateReport.t.d/other_input.vcf, lib/perl/Genome/VariantReporting/Command/CreateReport.t.d/plan.yaml, lib/perl/Genome/VariantReporting/Command/CreateReport.t.d/plan2.yaml, lib/perl/Genome/VariantReporting/Command/ShowDocs.t.expected-output/interpreters/__test__, lib/perl/Genome/VariantReporting/Framework/Test/Interpreter.pm, lib/perl/Genome/VariantReporting/Framework/Test/WithTranslationsRun.pm, lib/perl/Genome/VariantReporting/Framework/Test/WithTranslationsRunResult.pm
This PR supersedes https://github.com/genome/genome/pull/374.
This is a first step towards tackling https://jira.gsc.wustl.edu/browse/AT-680. This PR implements a compare_output subroutine for Genome::Process that would give a similar output to G::M::B::compare_output.
In this PR Genome::Process::_compare_output_files handles the comparison instead of being abstract and deferring the implementation to the child classes. It utilizes Genome::Process::symlink_results to symlink all the results of a process into one directory. Genome::Process::_compare_output_directories handles the actual comparison of those directories.
=> Add functionality to compare Genome::Process output files

lib/perl/Genome/InstrumentData/AlignmentResult/Command/RecreatePerLaneBam.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Command/RecreatePerLaneBam.t
Expect one line diff on duplicates between extracting bam flagstat and comparison flagstat. Expect no diff between reverting Markdup bam flagstat and comparison flagstat.The comparison flagstat is always from the original per lane bam that is not markdupped. The unit test is updated accordingly.
=> Fix a bug on comparing flagstat

lib/perl/Genome/VariantReporting/Command/ShowDocs.t.expected-output/interpreters/variant-callers, lib/perl/Genome/VariantReporting/Generic/VariantCallersInterpreter.pm, lib/perl/Genome/VariantReporting/Generic/VariantCallersInterpreter.t, lib/perl/Genome/VariantReporting/plan_files/cle_germline_report_indels.yaml, lib/perl/Genome/VariantReporting/plan_files/cle_germline_report_snvs.yaml, lib/perl/Genome/VariantReporting/plan_files/cle_indels_report.yaml, lib/perl/Genome/VariantReporting/plan_files/cle_snvs_report.yaml, lib/perl/Genome/VariantReporting/plan_files/gold_germline_report_indels.yaml, lib/perl/Genome/VariantReporting/plan_files/gold_germline_report_snvs.yaml, lib/perl/Genome/VariantReporting/plan_files/gold_somatic_report_indels.yaml, lib/perl/Genome/VariantReporting/plan_files/gold_somatic_report_snvs.yaml, lib/perl/Genome/VariantReporting/plan_files/somatic_indels_report.yaml, lib/perl/Genome/VariantReporting/plan_files/somatic_snvs_report.yaml
- List the valid_callers explicitly in the plan files instead of having a default
- Add GatkSomaticIndel and Pindel to the list of valid_callers in the indel plan files
=> Some minor changes to the variant caller interpreter

lib/perl/Genome/VariantReporting/Suite/BamReadcount/MaxVafObservedInterpreter.pm, lib/perl/Genome/VariantReporting/Suite/BamReadcount/MinCoverageObservedInterpreter.pm, lib/perl/Genome/VariantReporting/Suite/BamReadcount/VafInterpreter.pm
We use the VafInterpreter without library_names in the
MinCoverageObservedInterpreter and the MaxVafObservedInterpreter so it needs to be optional.
=> Make library_names optional for VafInterpreter

lib/perl/Genome/VariantReporting/Report/DocmReport.pm, lib/perl/Genome/VariantReporting/Report/FullReport.pm
HASH type properties cannot be persisted in the DB.  It would be nice to have these values persisted though because if they change, then the Report that gets generated may be different.
I'd like to use UR::Value::JSON for these, but it seems that doesn't "just work".  Perhaps a discussion with @brummett is in order...
=> Make sample/library name_labels transient

lib/perl/Genome/Config/AnalysisProject.pm
* Refuse to delete if models or instrument data are assigned.
* Cascade to delete any existing timeline events.
I tested this by deleting @chrisamiller's long-standing Analysis Project he's wanted deleted.  (There were previously other issues with deleting it that were resolved by earlier schema changes.)
=> Change cascading behavior of Analysis Project delete().

lib/perl/Genome/Model/Tools/Sx/Trim/Flexbar.pm, lib/perl/Genome/Model/Tools/Sx/Trim/Flexbar.t, lib/perl/Genome/Model/Tools/Sx/Trim/Flexbar/V2x4.pm
The parameter changed between the two flexbar versions.
It looks like some other parameters changed, too, which this command handled by having both and cautioning the user to use one or the other.  It seemed really confusing to me to end up with
```
--length-dist
--nolength-dist
--no-length-dist
--nono-length-dist
```
half of which work with one version and half with another, so I took a different approach here.  If that's against the spirit of SX, I could switch it to the above.
=> Flexbar --(no-)length-dist parameter

bin/genome-test
CHANGELOG: Run tests now by running `genome-test`.  `genome-test` is
basically an alias to `genome-test-env test-tracker prove` that will
default to using the `--lsf` and `--git` options if no options are
specified.
=> add genome-test

lib/perl/Genome/Model/SomaticValidation/Command/VerifyBam.pm
In the latest validation test this was taking just over 9000 megabytes of memory to run.
=> Set LSF memory request for SomVal's VerifyBam step.

lib/perl/Genome/Config/AnalysisProject/Command/AddModel.t, lib/perl/Genome/Config/AnalysisProject/Command/View.pm, lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.pm, lib/perl/Genome/Model.pm, lib/perl/Genome/Model/Build/Command/View.pm, lib/perl/Genome/Model/Command/Define/ImportedReferenceSequence.pm, lib/perl/Genome/Model/SomaticValidation/Command/ValidateLargeIndels/CreateAssembledContigReference.pm, lib/perl/Genome/Model/SomaticValidation/Command/ValidateSvs/CreateAssembledContigReference.pm
Models can only belong to one `AnalysisProject` so the `analysis_projects` property
should be singular.  When originally implemented this was believe to not be
supported by UR.  This adds `analysis_project` and deprecates `analysis_projects`.
=> make analysis_projects singular on models

lib/perl/Genome/InstrumentData/AlignmentResult/Bsmap.pm, lib/perl/Genome/Model/Event/Build/ReferenceAlignment/AlignReads.pm
* Pass along the params so we get the correct thread count.
* Specify a job group for each aligner so we can separately throttle them to avoid monopolizing the queues.  (This only applies to ReferenceAlignment for now.)
=> Correct Custom BSMap Resource Requirements

lib/perl/Genome/Model/Tools/Picard/MarkDuplicates.pm, lib/perl/Genome/Model/Tools/Sam/MarkDuplicates.pm, lib/perl/Genome/Model/Tools/Sam/MarkDuplicates.t
This new option is needed for the X10 data; see AT-732
As an added sanity check that this will work, I made a somatic validation build a637dfde0ba24bf8acc90bf02da71296 that uses the new parameter in its alignment strategy.  It correctly submitted the option to the MarkDuplicates command line, and picard ran without complaint.
=> New picard option

lib/perl/Genome/Sys.pm
This should fix the two tests hanging on Jenkins:
InstrumentData/Command/Import/Basic_sra.t
InstrumentData/Command/Import/WorkFlow/SraToBam.t
The problem is that Genome::InstrumentData::Command::Import::WorkFlow::SraToBam::do_shellcmd_with_stdout()
is reading from a file of saved STDERR of a child process run with
Genome::Sys::shellcmd() and printing it to its own STDERR.  However, the
current process' STDERR is also printing to that same file.  The tests hang
because do_shellcmd_with_stdout() never gets to the end of the file (it's
filling it as it's reading).
I'm not sure what the _actual_ bug is, but this seems to fix it, while
removing global filehandle variables.  The strange part is that the tests ran fine
when I added seemingly unrelated prints inside the guard closures, and also …
=> Properly scope the saved STDOUT and STDERR handles

lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/SraToBam.pm
the old code wasn't doing what it thought it was doing
=> Relay child process' STDERR as error_message()s

lib/perl/Genome/Disk/Allocation.pm, lib/perl/Genome/Disk/Command/Allocation/Reallocate.t, lib/perl/Genome/Disk/Command/Allocation/Unarchive.t, lib/perl/Genome/Test/Factory/DiskAllocation.pm
When a previously-archived allocation is purged it will have status `purged` but a mount path pointing to the disk archive.  This leads to trouble when someone or something tries to unarchive this purged allocation.
=> Trust an Allocation's Status When Deciding if Archived

lib/perl/Genome/VariantReporting/Suite/BamReadcount/PerLibraryVafInterpreter.pm, lib/perl/Genome/VariantReporting/Suite/BamReadcount/PerLibraryVafInterpreter.t
Instead of trying to check that the planned libraries match the libraries provided in the vcf, restrict the interpretations to the set of planned libraries.
=> Change how the PerLibraryvafInterpreter handles planned libraries

lib/perl/Genome/VariantReporting/Suite/BamReadcount/MaxVafObservedInterpreter.pm, lib/perl/Genome/VariantReporting/Suite/BamReadcount/MinCoverageObservedInterpreter.pm
We want to avoid creating throwaway vaf interpreter objects every time _interpret_entry is called. Instead this PR makes it so that the vaf interpreter(s) are made into transient optional parameters.
=> Make vaf interpreters transient optional parameters

lib/perl/Genome/Model/Build/PhenotypeCorrelation.pm, lib/perl/Genome/Model/Build/ReferenceAlignment.pm, lib/perl/Genome/Model/Build/ReferenceAlignment.t, lib/perl/Genome/Model/Build/ReferenceSequence/Converter.pm
These should have been changed as part of #429 but were not.
=> Only check that converter exists during ROI validation.

bin/genome-env-next
I let the option spec get out of sync again.  This fixes it for changes that
were previously made to the case statement:
- add the -m option
- remove the -v option
=> fix option spec

lib/perl/Genome/Model/Set/View/Coverage/Xml.pm
Here's an [example coverage report](https://imp-apipe.gsc.wustl.edu/view/genome/model-group/coverage.html?id=695ce2caba6442d2b9f824bd87f752de). Per RT [104057](https://rt.gsc.wustl.edu/Ticket/Display.html?id=104057#txn-1838158). :sheep:
=> Fix duplicate models on coverage report summary

lib/perl/Genome/Sys/Lock.pm
If you interrupted during first mid-`lock_resource` then locks would not be cleaned up because the cleanup handlers weren't installed yet.
=> need to install handlers before backends start locking

lib/perl/Genome/Command/DelegatesToResult.t, lib/perl/Genome/InstrumentData/Command/RefineReads/GatkBestPractices.t, lib/perl/Genome/SoftwareResult/User.pm, lib/perl/Genome/SoftwareResult/User.t, lib/perl/Genome/VariantReporting/Command/CreateReport.t, lib/perl/Genome/VariantReporting/Command/Wrappers/Trio.t
There was a race condition here where multiple processes thought they needed to create the sponsor relationship.  This adds locking around the user creation to avoid the duplicates.
The creation is delayed to a pre-commit hook to avoid needing to either commit the user relationship in a separate transaction or potentially hold the lock for a long time.
=> Defer SR user creation to commit time and lock to prevent duplicates.

lib/perl/Genome/FeatureList.pm, lib/perl/Genome/VariantReporting/Suite/Vep/RunResult.pm
Sometimes a feature list that is used for vep annotation in the variant reporting subsystem will contain special characters which might cause downstream tools to fail. E.g., semicolons cause errors for joinx vcf-merge if they aren't used to separate info fields. This change will check the feature lists supplied to the vep annotation and crash if it contains a special character.
Right now the only special character I'm aware of is semicolon but this code change allows for easy addition of other invalid characters.
=> Variant reporting: fail vep annotation early if feature list contains invalid characters

lib/perl/Genome/SoftwareResult/User.pm
If the result is deleted for any reason, we don't still want to try to add users.  (We know it's not coming back unless another pre-commit hook resurrects it...)
For example, `Genome::InstrumentData::WithIntermediateResults` gets the intermediate results (thus adding a callback) immediately before deleting them.
=> Don't try to add users to deleted results.

lib/perl/Genome/Model/Tools/Joinx/VcfReport.pm, lib/perl/Genome/Model/Tools/Joinx/VcfReport.t
it was using floating point comparisons for the 'minimum version' check.
the base class already had a "check_minimum_version" method that does
the right thing. added a test too.
=> update gmt joinx vcf-report to check versions properly

lib/perl/Genome/Model/Event/Build/ReferenceAlignment/RunReports.pm, lib/perl/Genome/ProcessingProfile/ReferenceAlignment.pm
It has been requested that we still run reports (particularly MapCheck) even if no variant detection is performed.
=> Relax requirements for scheduling reference alignment reports.

lib/perl/Genome/Taxon/View/Status/Html.t, lib/perl/Genome/Taxon/View/Status/Xml.t
Although "mouse" was a less poor choice than "human", this test will run much more quickly with only five individuals.
=> Use a Test Factory Taxon in View Tests

bin/genome-env-next
Updated from previous version to fix missing ClinSeq data.
```
$ bin/genome-env-next genome-fill-db prove -v lib/perl/Genome/Model/ClinSeq.t lib/perl/Genome/Model/ClinSeq/Command/Converge/DgidbCounts.t lib/perl/Genome/Model/ClinSeq/Command/Converge/DgidbGenes.t
...
Test DB Name: 4FA4513AB80511E48973DEB2A9DCD391
...
$ test-db template create $(git rev-parse --short HEAD) 4FA4513AB80511E48973DEB2A9DCD391
```
=> update default DB snapshot

lib/perl/Genome/Model/Tools/DetectVariants2/VarscanSomaticValidation.pm
This process was filling /tmp on one of our blades but other jobs would still be scheduled there.
=> Reserve tmp since our output is written there before being allocated.

lib/perl/Genome/Model/Tools/Htseq/Count/Result.pm, lib/perl/Genome/Model/Tools/Htseq/Count/Result_error_handling.t
The HTSeq::Count result saves the stderr of the command to a file within the result's directory.  If the command fails the result is not saved and so the log is lost.  To help debug failures, report the last 100 lines of that file as a debug message.
=> Save the End of the Log when htseq-count Fails

lib/perl/Genome/Command/Viewer.pm, lib/perl/Genome/Command/WorkflowMixin.pm
This fixes an issue I noticed when build tests time out or fail.  We get
these warnings:
```
00:34:47 Unable to get Terminal Size. The TIOCGWINSZ ioctl didn't work. The COLUMNS and LINES environment variables didn't work. The resize program didn't work. at /usr/lib/perl5/Term/ReadKey.pm line 362.
00:34:47 Use of uninitialized value $screen_width in subtraction (-) at /gscmnt/gc7008/info/jenkins/workspace/Genome-Long-Model-Tests/lib/perl/Genome/Command/WorkflowMixin.pm line 526.
00:34:47 Use of uninitialized value $screen_width in subtraction (-) at /gscmnt/gc7008/info/jenkins/workspace/Genome-Long-Model-Tests/lib/perl/Genome/Command/WorkflowMixin.pm line 527.
```
=> fix for when GetTerminalSize is not supported

lib/perl/Genome/Model/Build/ReferenceSequence/AlignerIndex.pm
AlignerIndices do a strange thing where they do work even in the `get()` case (where the usual `WithNestedResults` hash is not provided (since it's not "nested"!)).  We thus need to pass along the users explicitly in this case.
(Alternatively `WithNestedResults` could fill in the hash in all cases, but external callers should still not rely on its presence.)
=> Pass users to the "dependencies".

lib/perl/Genome/Config/AnalysisProject/Command/AddConfigFile.pm, lib/perl/Genome/Config/AnalysisProject/Command/AddMenuItem.pm, lib/perl/Genome/Config/AnalysisProject/Command/Reprocess.pm, lib/perl/Genome/Config/AnalysisProject/Command/Reprocess.t, lib/perl/Genome/Config/AnalysisProject/InstrumentDataBridge.pm
If a user forgets to use the `--reprocess-existing` option on one of the other commands (or they'd prefer to wait before reprocessing), this command can be used to the same effect.
=> A Command for Reprocessing an Analysis Project

genome-env-tests/basic.bats, genome-env-tests/test_helper.bash, genome-env-tests/testexec/D.sh, genome-env-tests/testexec/M.sh, genome-env-tests/testexec/U.sh, genome-env-tests/testexec/W.sh, genome-env-tests/testexec/default.sh, genome-env-tests/testexec/migration.sh
First two commits are to reduce the number of ephemeral databases that get
created when running these tests.  The remaining commits are refactors to
deduplicate the testexecs.
=> improvements to genome-env-tests

lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.pm
The current implementation, while it does a better job of restricting data than before, is too slow for large projects like FinnSeq and may not always do the correct thing (since it filters only on the "rules" section of the configuration and not also the "instrument_data_properties" section).
=> Disable auto_assign_inst_data as a feature for now.

lib/perl/Genome/SoftwareResult/User.pm
* Use the new `once => 1` for observers.
* Don't let lock names get too long by including the whole label.  (Another approach might be to `substr` the label instead.  That would preserve backwards compatibility with most existing locks, but it could lead to collisions that cause deadlocks.)
=> More SR User Locking Improvements

lib/perl/Genome/VariantReporting/Command/Wrappers/Trio.pm, lib/perl/Genome/VariantReporting/Command/Wrappers/Trio.t.d/expected.xml, lib/perl/Genome/VariantReporting/Framework/Component/Report/MergedReport.pm, lib/perl/Genome/VariantReporting/Framework/MergeReports.pm, lib/perl/Genome/VariantReporting/Framework/MergeReports.t
Now that MergeReports only support two report inputs and report sources has been split into base_report and supplemental_report we don't need entry_sources to be is_many anymore. Instead this PR splits it into a base_report_source and a supplemental_report_source. 
This is to finish up https://jira.gsc.wustl.edu/browse/AT-678.
=> Split entry_sources of MergeReports into base_report_source and supplemental_report_source

lib/perl/Genome/Config/AnalysisMenu/Command/Item/Create.pm, lib/perl/Genome/Config/AnalysisMenu/Command/Item/Create.t
AnalysisMenu::Item->create now requires a pull request for the menu item repo to be merged and the 'Update Analysis Menu Items' jenkins job to have run before this command can be used to create a menu item.  If the file being used for menu item creation has not be added this way, this command will fail.
=> Restrict AnalysisMenu Item Create

lib/perl/Genome/Model/RnaSeq.t, lib/perl/Genome/WorkflowBuilder/Test/Command.t, lib/perl/Genome/WorkflowBuilder/Test/DAG.t
These tests broke when we change apipe-tester's config to use the "pd" queues.
=> fixes for tests that broke when apipe-tester config changed

bin/genome-env
We've had these errors every once in awhile,
> Got error response 500: SSL read timeout:  at
> /usr/bin/test-db-database-create line 15
Previously we added the `--timeout` option but we didn't think it should be
necessary.  Now I am thinking it may be that the template locks while creating
the new database so contention is what is causing the timeouts. For now I am
just increasing the timeout as a workaround.  We'll need to see if this is
actually what's going on.
=> override default timeout when creating an ephemeral database

lib/perl/Genome/Command/Viewer.pm
I don't know of a way to test this easily so I don't know that this works. 
I'm trying to disable the warnings that shows up on apipe-ci logs,
> 13:40:44 Unable to get Terminal Size. The TIOCGWINSZ ioctl didn't
> work. The COLUMNS and LINES environment variables didn't work. The
> resize program didn't work. at /usr/lib/perl5/Term/ReadKey.pm line
> 362.
=> try to disable Term::ReadKey warning

lib/perl/Genome/Db/Ensembl/Command/Run/Base.pm
The process hasn't been committed yet, so shelling out for the
workflow steps will fail.  By setting NO_LSF, the workflow will
be run in the same context and the process will be accessible.
=> Process needs to be accessible by workflow step

lib/perl/Genome/SoftwareResult/User.pm
It was suggested that `_get_or_create_with_lock` was a confusing name for a thing that returns a lock.  Here's a perhaps better alternative.  It's also possible we could restructure this instead?
=> Tweak internals of SR User locking

lib/perl/Genome/Model/Command/Export/Metadata.pm
Annotation builds with status "Dummy" prevent builds being launched on the SGMS. This PR retains the build's current status.
=> Retain build-status in metadata if defined

lib/perl/Genome/SoftwareResult/User.pm
This reverts commit 1a8c5df57c9de933a8eb555867aa1fc8347a129e.  That
commit was pretty optimistic about length limits.  The exact limit is
not knowable in advance, so go back to the probably-fine level of 32 :)
A better solution would involve one or more of the following:
1) file locks knowing their own limits in general
2) switching to Nessy :)
3) not storing complex information in labels
[The commit being reverted was previously part of #514.  I remain under the impression that what it reverts to isn't anyone's first choice for what should happen, but I also believe it is more likely to work!]
=> Revert "Only hash the lock name if we're going to exceed the length limit."

lib/perl/Genome/Env/GENOME_LOCK_SCOPES.pm, lib/perl/Genome/Site/SGMS.pm, lib/perl/Genome/Site/SGMS.t, lib/perl/Genome/Sys/Lock.pm
add SGMS.pm which configures backends for scopes ("unknown", "site") which are required for builds to run in the SGMS. "tgisan" seems to be TGI specific and can be ignored. This addresses https://github.com/genome/gms/issues/162
=> configure a site module for the SGMS.

lib/perl/Genome/Config/AnalysisProject/Command/DefineTemplate.pm, lib/perl/Genome/Config/AnalysisProject/Command/DefineTemplate.t
Once upon a time we added support for Analysis Projects that were "templates".  They would let someone store a set of configurations in one place for easy copying using `genome analysis-project copy-config`.  However, there was no way to create one... until now!
=> New Command to Define an AnalysisProject Template.

lib/perl/Genome/Sys.pm, lib/perl/Genome/Sys.t
Writing to STDOUT more than once via Sys's write_file causes a crash. This is a PR has tests showing the failure. Should this be fixed?
@brummett please take a look.
=> Sys: Do not close the fh in write_file if writing to STDOUT

lib/perl/Genome/InstrumentData/Microarray/Result/Vcf.pm
`get_or_create()` will then try to `get()` one last time (if `create` detected
that the object was made already).  Crashing prevents this from working.
=> SUPER::create() may return undef--pass it along.

lib/perl/Genome/Model/Build/Command/Queue.pm
Now that "queueing" a build will run it as the run_as user, users can use this to queue their own builds.
=> No longer hide build queue in docs.

lib/perl/Genome/Model/ClinSeq/Command/UpdateAnalysis.pm
ClinSeq: update analysis now specifies cancer, misc, cosmic DBs in clin-seq model define commands when a non-default version is specified by the user.
`genome model clin-seq update-analysis` was correctly examining which version of the cosmic, cancer and misc databases were being used in candidate models.  If these parameters did not match those specified by the user (or default if the user did not say), then such clin-seq models were considered non matching.  When no clin-seq model matching all desired criteria was found, it advised the user to create one.  
The problem is, at this point it did not present the correct command to define a model with the correct cosmic, cancer, and misc databases when the user specified a non-default option.
This pull request modifies update-analysis so …
=> ClinSeq: update analysis now specifies cancer, misc, cosmic DBs

lib/perl/Genome/InstrumentData/AlignmentResult/Bwa.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Bwamem.pm, lib/perl/Genome/InstrumentData/AlignmentResult/BwamemStream.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Bwasw.pm
This is a quick patch to a problem in production due to an LSF configuration change.  It seems clear from the *four* places I had to edit that this code is suboptimal and should be further improved.
(No bwa reference alignment builds can be started in the current LSF configuration without this change.)
=> Strip priorities from host-group parsing.

lib/perl/Genome/FeatureList.pm, lib/perl/Genome/VariantReporting/Command/CreateMergedReports.t.d/snvs_plan.yaml, lib/perl/Genome/VariantReporting/Command/ShowDocs.t.expected-output/experts/vep, lib/perl/Genome/VariantReporting/Suite/Vep/Expert.t.d/plan.yaml, lib/perl/Genome/VariantReporting/Suite/Vep/Run.pm, lib/perl/Genome/VariantReporting/Suite/Vep/Run.t.d/plan.yaml, lib/perl/Genome/VariantReporting/Suite/Vep/RunResult.pm, lib/perl/Genome/VariantReporting/plan_files/cle_germline_report_indels.yaml, lib/perl/Genome/VariantReporting/plan_files/cle_germline_report_snvs.yaml, lib/perl/Genome/VariantReporting/plan_files/cle_indels_report.yaml, lib/perl/Genome/VariantReporting/plan_files/cle_snvs_report.yaml, lib/perl/Genome/VariantReporting/plan_files/example_snvs_plan.yaml, lib/perl/Genome/VariantReporting/plan_files/flanking_fasta_indels.yaml, lib/perl/Genome/VariantReporting/plan_files/flanking_fasta_snvs.yaml, lib/perl/Genome/VariantReporting/plan_files/gold_germline_report_indels.yaml, lib/perl/Genome/VariantReporting/plan_files/gold_germline_report_snvs.yaml, lib/perl/Genome/VariantReporting/plan_files/gold_somatic_report_indels.yaml, lib/perl/Genome/VariantReporting/plan_files/gold_somatic_report_snvs.yaml, lib/perl/Genome/VariantReporting/plan_files/rnaseq_variants_snvs.yaml, lib/perl/Genome/VariantReporting/plan_files/somatic_indels_report.yaml, lib/perl/Genome/VariantReporting/plan_files/somatic_snvs_report.yaml, lib/perl/Genome/VariantReporting/plan_files/tumor_only.yaml
Sometimes our feature lists contain special characters in the name column which makes joinx choke when it tries to run vcf-merge on a vep annotated vcf in the vep expert. This has previously been addressed here https://github.com/genome/genome/pull/471 by making the vep expert fail early with a helpful error message. In order to get the vep expert to run it would've been necessary to sanitize and reimport the feature list.
In RT https://rt.gsc.wustl.edu/Ticket/Display.html?id=104483 it has been requested that we find an option that doesn't require manual user intervention. This PR makes it so that the user can specify the short_name option in the vep expert which will result in the name column being replaced with region numbers. This works for all of our current reports because the …
=> Add option to vep expert to use use short_name instead of name column in feature list

lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.pm
Omitting `undef` from the `get()` queries may pull back non-matching
models, but including `undef` in `create()` calls may generate invalid
hangoff objects.
=> CQID: Only filter undef properties from model creation.

lib/perl/Genome/Disk/Allocation.pm
Builds were failing on Mar 13 between 2 and 3AM.
_default_archive_after_time() adds 1 year to the current time.  The 2016 DST
changeover will happen on Mar 13, so 13 Mar 2016 2:45:00 won't exist.  The
error would also occur for any allocations created on Feb 29th.
This change adds an equivalent number of seconds, which DateTime allows, and
automatically adjusts for time changes.
One downside is that when there's a Feb 29th between "now" and the calculated
date, you'll technically have 1 day less than a year before it's archived.
The alternative is to use DateTime's "floating" timezone
(https://metacpan.org/pod/DateTime#Making-Things-Simple) which allows the
calculation to produce an invalid date in the local timezone, but this seems
more hacky.
=> Fix DateTime calculation involving DST

lib/perl/Genome/Site/TGI/UsageLog.pm
The PostgreSQL error message can contain the server name in double quotes,
which messes up building the string to be eval-ed, which generates an error
about a runaway string.  This escapes those quotes.
=> Avoid an additional error when we can't connect to the logging DB

lib/perl/Genome/FeatureList/Command/Import.pm, lib/perl/Genome/FeatureList/Command/Import.t, lib/perl/Genome/FeatureList/Command/Import.t.d/X_capture_targets.bed, lib/perl/Genome/FeatureList/Command/Import.t.d/X_multitrack.bed, lib/perl/Genome/FeatureList/Command/Import.t.d/X_primary_targets.bed, lib/perl/Genome/Utility/Test.pm
Add support for importing Nimblegen capture_targets/primary_targets split
bed files.
This feature was requested in [RT#104532][1].
[1]: https://rt.gsc.wustl.edu/Ticket/Display.html?id=104532
=> support importing "new" Nimblegen capture/primary split bed files

lib/perl/Genome/InstrumentData/AlignmentResult.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm, lib/perl/Genome/Model/Tools/Htseq/Count/Result.pm
Currently the apipe-test-rnaseq build failure is caused by the bug that HTseq count fails to find the per lane bam that is removed after bam merge. This PR fixes the bug and also makes the change to give correct instrument_data_id to RecreatePerLaneBam.
=> Make Htseq count to revivify the per lane bam from merged bam

lib/perl/Genome/Model/Tools/Bsmap/MethylationRatio.pm, lib/perl/Genome/Model/Tools/Bsmap/MethylationRatio.t, lib/perl/Genome/Model/Tools/Bsmap/methylation_ratio.py
This pull request adds a replacement for mehRatio.py -- a script that calculates DNA methylation levels from bisulfite-treated, BSMAP-aligned data. The new script, methylation_ratio.py, avoids the exuberant memory requirements associated with the old script. Also new is the ability to multi-thread the wok.
=> Created methylation_ratio

lib/perl/Genome/Model/Build/DeNovoAssembly/Abyss.t
I previously disabled this test because I thought the production blades had a
problem running it but I've been unable to reproduce the problem locally.
[AR-953][]
[AR-953]: https://jira.gsc.wustl.edu/browse/AR-953
=> re-enable Abyss.t

lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalseIndel.pm
Running the "false-indel" filter on samtools output would require a lot of RAM (hence the 32GB request), but we no longer run this filter on samtools indels.
=> Lower false indel memory requests

lib/perl/Genome/Model/Event/Build/ReferenceAlignment/DetectVariants.pm, lib/perl/Genome/Model/SomaticValidation/Command/DetectVariants.pm, lib/perl/Genome/Model/SomaticVariation/Command/DetectVariants.pm
@jasonwalker80 has been looking at resource usage, and noticed that these dispatchers used the default 4 GB memory request but in reality used only about 400 MB.  This PR sets an upper bound of 600 MB.
This also adds a temp space request to the Somatic pipelines to match the RefAlign request, since they do use some.
=> Set tmp and mem requests for DV2 dispatchers

lib/perl/Genome/InstrumentData/AlignmentResult.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Maq.pm, lib/perl/Genome/InstrumentData/IntermediateAlignmentResult.pm, lib/perl/Genome/Model/Build/ReferenceSequence/AlignerIndex.pm, lib/perl/Genome/Model/Build/ReferenceSequence/AnnotationIndex.pm, lib/perl/Genome/Model/Tools/DetectVariants2/RtgSnp.pm, lib/perl/Genome/Model/Tools/DetectVariants2/Samtools.pm, lib/perl/Genome/Model/Tools/DetectVariants2/Varscan.pm, lib/perl/Genome/Model/Tools/DetectVariants2/VarscanSomatic.pm, lib/perl/Genome/Model/Tools/Sam/Pileup.pm, lib/perl/Genome/Model/Tools/Vcf/CreateCrossSampleVcf/Pileup.pm
Some bad requests were copy+pasted around over time... I found a copy of this `-M` limit in a version of the Samtools command from 2009.
=> Match -M to actual resource requests.

lib/perl/Genome/Model/Tools/Transcriptome/ErccMapUnaligned.R, lib/perl/Genome/Model/Tools/Transcriptome/ErccMapUnaligned.pm, lib/perl/Genome/Model/Tools/Transcriptome/ErccMapUnaligned.t
This is "Part 2" of a 2-part introduction of a RNASeq quality control tool to address a need mentioned in BIO-1345.  [Part 1][1] was focused on getting the tool infrastructure and plumbing setup.  Part 2 is focused on the analysis being done and what kind of inputs and outputs the end user will need to supply and observe respectively.
* A user must supply either a model ID, or a specific BAM file path, but not both.
* A number of required input parameters have been changed to optional and sensible default values have been placed for them.
* There are two specific files created by the tool that the end-user will notice: a PDF file containing analysis plots and a TSV file containing the raw data used to make the PDF file.  Both these file names are auto-generated by what the user supplied …
=> ERCC-based Quality Control Screening for RNASeq: Part 2

lib/perl/Genome/FeatureList/Command/Update.pm
Updating the reference would produce a message like:
```
setting reference to Genome::Model::Build::ImportedReferenceSequence=HASH(0x6e2ef40)
```
Now it will be like:
```
setting reference to human-build38 (a123b4567cd89e01f234a5b67cd89ef0)
```
=> Print the display name for blessed objects.

lib/perl/Genome/Model/ReferenceSequence.pm
Previously, the choice of FASTA in the `_list_bases_files` was the original input which may or may not have been indexed.  Now it will be called on the build's FASTA which should be indexed during the build process.  (Additionally, cache the result of whether or not to make bases files, so the choice of FASTA is less relevant.)
I don't believe that the `--skip-bases-files` flag to `genome model define imported-reference-sequence` is currently working as intended... but this change shouldn't affect that.
=> Don't Warn about Each Missing ".bases" File if We Didn't Make Any

lib/perl/Genome/Config/AnalysisProject/Command/AddMenuItem.pm, lib/perl/Genome/Config/AnalysisProject/Command/AddMenuItem.t
This feature already existed when creating a configuration from a file directly.  This makes the two commands more similar.  (If more features are added to these, they would probably benefit from a common base.)
=> Optionally add tag(s) when associating menu item(s) to the AnP.

lib/perl/Genome/InstrumentData/Composite.pm
This is to fix failing model tests.
Since per-lane alignments are now G::ID::AlignedBamResult they need to be explicitly filtered out.
=> Filter out G::ID::AlignmentResult

lib/perl/Genome/InstrumentData/AlignmentResult/Bwamem.t, lib/perl/Genome/Model/Tools/Picard.pm, lib/perl/Genome/Model/Tools/Picard/BamIndexStats.pm, lib/perl/Genome/Model/Tools/Picard/Base.pm, lib/perl/Genome/Model/Tools/Picard/BedToIntervalList.pm, lib/perl/Genome/Model/Tools/Picard/BuildBamIndex.pm, lib/perl/Genome/Model/Tools/Picard/CalculateHsMetrics.pm, lib/perl/Genome/Model/Tools/Picard/CleanSam.pm, lib/perl/Genome/Model/Tools/Picard/CollectAlignmentSummaryMetrics.pm, lib/perl/Genome/Model/Tools/Picard/CollectGcBiasMetrics.pm, lib/perl/Genome/Model/Tools/Picard/CollectInsertSizeMetrics.pm, lib/perl/Genome/Model/Tools/Picard/CollectMultipleMetrics.pm, lib/perl/Genome/Model/Tools/Picard/CompareSams.pm, lib/perl/Genome/Model/Tools/Picard/CreateSequenceDictionary.pm, lib/perl/Genome/Model/Tools/Picard/EstimateLibraryComplexity.pm, lib/perl/Genome/Model/Tools/Picard/SortSam.pm
**Background:** Early versions of Picard all of have Java class names starting with `net.sf`. This changed in release 1.114, when Picard moved to GitHub and they removed the `net.sf`.
These commits codify this change and remove old hacks. These commits also change how sub-classes return their Java class name. The method was renamed from `_java_class_name` to `_java_class`, and it now returns an array of "components" instead of a string. The `_java_class_name` method is now only on the Base class, and handles prepending `net.sf` (if necessary) and doing a `join '.', @class` for the command-line.
:dolphin: :ribbon:
=> Picard classnames

lib/perl/Genome/Model-build_requested.t, lib/perl/Genome/Model.pm
Issues this PR is attempting to address:
* Processes will sometimes acquire the lock and hold onto it for a long time even though they haven't attempted to modify the `build_requested` value.
* Processes spam the model notes with calls from `_reverse_all_changes`.
This short script demonstrates the existing behaviour:
```
$ genome-perl -M5.10.0 -MGenome -e 'my $m = Genome::Model->get(name => "apipe-test-reference-alignment"); say scalar(@{[$m->notes]}); UR::Context->rollback(); say scalar(@{[$m->notes]});'
13035
13036
Removing remaining resource lock: 'build_requested/2880887847' at /.../Genome/Sys/Lock/FileBackend.pm line 244.
```
Here's the behaviour with the changes:
```
$ genome-perl -M5.10.0 -e 'use above "Genome"; my $m = Genome::Model->get(name => "apipe-test-reference-alignment"); …
```
=> Don't log rollbacks on build requested

lib/perl/Genome/VariantReporting/Suite/BamReadcount/Adaptor.pm
I noticed this was being submitted every time as a separate lsf job.  There is no reason why this should ever need to run with lots of resources.
=> Add shortcut to adaptor class

lib/perl/Genome/WorkflowBuilder/StreamGraph.t
Use canonpath to normalize path as something in StreamGraph seemed to do the
same.  For example, `./WorkflowBuilder` becomes just
`WorkflowBuilder` which was breaking the full test suite.
=> use canonpath to normalize $test_dir

lib/perl/Genome/InstrumentData/AlignedBamResult/Merged.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Merged/CoverageStats.pm, lib/perl/Genome/InstrumentData/BamUtil/ClipOverlapResult.pm, lib/perl/Genome/InstrumentData/Command/RefineReads/ClipOverlap.pm, lib/perl/Genome/InstrumentData/Command/RefineReads/GatkBase.pm, lib/perl/Genome/InstrumentData/Composite.pm, lib/perl/Genome/InstrumentData/Gatk/Base.pm, lib/perl/Genome/InstrumentData/VerifyBamIdResult.pm, lib/perl/Genome/Model/Build/SomaticValidation.pm, lib/perl/Genome/Model/Build/SomaticValidation/IdentifyDnpResult.pm, lib/perl/Genome/Model/SomaticValidation/Command/IdentifyDnp.pm, lib/perl/Genome/VariantReporting/Suite/BamReadcount/RunResult.pm
This allows us to differentiate between per-lane and merged aligned bam results.
This replaces https://github.com/genome/genome/pull/594 and will fix model tests.
=> Make a class for merged AlignedBamResults and use it where appropriate

lib/perl/Genome/Model/Build.pm
This addresses the unclear error noticed in [RT#104836][],
> Could not start build, reason: Can't call method "__display_name__" on an undefined value at /gsc/scripts/opt/genome/snapshots/genome-3587/lib/perl/Genome/Model/Build.pm line 1221.
[RT#104836]: https://rt.gsc.wustl.edu/Ticket/Display.html?id=104836
=> handle use case where reference sequence is missing

lib/perl/Genome/FeatureList/Command/Merge.pm, lib/perl/Genome/FeatureList/Command/Merge.t
This makes merge more similar to import, both of which are being used by LIMS for similar purposes.
=> Make new_feature_list output available from merge.

lib/perl/Genome/Model/Tools/Picard.pm
This reverts commit fdbcd444d7ea17d24014c8d6af86525b749d6eae.
(For the second time in a week I have failed to use grep correctly, it would seem!)
This subroutine is still mostly duplicative, which is sad.
=> Revert "Remove incomplete disused "parse_file_into_histogram_hashref"."

lib/perl/Genome/FeatureList/Command/Merge.pm
If there are many candidates for conversion but exactly one is in our original query set, then use it rather than force the user to choose.
=> Narrow down choices of convertible references by preferring an input.

lib/perl/Genome/Model/Tools/Analysis/Coverage/AddReadcounts.pm
After talking to @malachig, we're convinced that filtering on VAF and depth shouldn't be allowed when feeding this tool multiple BAMs. I've added code to check this and updated the docs ever so slightly. 
@malachig,@obigriffith,@kkrysiak  - let me know if you think the doc updates look good.
=> Add readcount checks

lib/perl/Genome/Model/SomaticValidation/Command/IdentifyDnp.pm
Not only are they not used, they duplicate two other variables declared just above them!
=> Remove disused variables.

lib/perl/Genome/Model/SmallRna/Command/ClusterCoverage.pm, lib/perl/Genome/Model/SmallRna/Command/StatsGenerator.pm, lib/perl/Genome/Model/Tools/DetectVariants2/Polymutt.pm, lib/perl/Genome/Model/Tools/SmrtAnalysis/Consensus.pm, lib/perl/Genome/Model/Tools/SmrtAnalysis/ConsensusReports.pm, lib/perl/Genome/Model/Tools/SmrtAnalysis/Control.pm, lib/perl/Genome/Model/Tools/SmrtAnalysis/ControlReports.pm, lib/perl/Genome/Model/Tools/SmrtAnalysis/Filter.pm, lib/perl/Genome/Model/Tools/SmrtAnalysis/FilterReports.pm, lib/perl/Genome/Model/Tools/SmrtAnalysis/Mapping.pm, lib/perl/Genome/Model/Tools/SmrtAnalysis/MappingReports.pm, lib/perl/Genome/Model/Tools/SmrtAnalysis/Rccs.pm, lib/perl/Genome/Model/Tools/SmrtAnalysis/RccsReports.pm, lib/perl/Genome/Model/Tools/Somatic/LaunchPindel.pm, lib/perl/Genome/ModelGroup/Command/RunPindel.pm, lib/perl/Genome/Process/Command/Run.pm
This doesn't really solve the problem pointed out in RT#104979 but instead
probably just moves it to another queue.  A better solution should be possible
after the LSF queues are redesigned in a couple weeks.
=> only build workflows should go in build workflow queue

genome-webserver/solr/scripts/gcsearch_load_from_db.pl, genome-webserver/solr/scripts/gcsearch_load_from_mailman.pl, lib/perl/Genome/Sys.pm, lib/perl/Genome/Sys/LockMigrationProxy.t
I went looking for `lock_resource()` usage to migrate to `LockProxy` but there
wasn't much left after previously converting locations that used
`unlock_resource()`.
=> minimize use of Genome::Sys::Lock API

lib/perl/Genome/Model/ReferenceAlignment/Command/GenotypeMicroarrayConcordance.pm
(This is different from the name for TCGA samples, for example.)
=> Picard needs to know the name in the VCF.

lib/perl/Genome/Model/Command/Services/ListBuildQueue.pm
Ironically the pointer we're using is changing more frequently than the value it points to!
=> Fix BQM's ability to decide what column to use for "build_requested".

lib/perl/Genome/Model/Tools/Picard.pm
[As promised in #611,] This PR is a second attempt at cleaning up the duplicate subroutines for metrics processing.
One thing of note: this no longer silently skips rows where the number of headers and number of values don't match in the "histogram" case.
=> Deduplicate histogram and metrics processing subroutines.

lib/perl/Genome/VariantReporting/Suite/Vep/joinx_merge.strategy
Currently joinx fails during merging if two alternate alleles have different ON_TARGET annotations because we are using the enforce-equal merge strategy. 
Using the uniq-concat strategy will create a unique list of the ON_TARGET annotations for all alternate alleles. This will yield incorrect results in the downstream variant reports if one alternate allele is on target and the other isn't. However, in order to quickly move forward with CLE validation this option was chosen by Dave Larson. Ultimately we will probably want to make the ON_TARGET info field a per-allele field but this will require more development.
This is a CLE blocker so a fast turnaround would be appreciated.
=> Change ON_TARGET merge strategy to uniq-concat

lib/perl/Genome/Model/Tools/Picard/MarkDuplicates.pm, lib/perl/Genome/Model/Tools/Picard/MarkDuplicates.t
I wonder if a longer-term solution might be to add a minimum version attribute to Picard properties and have the base class handle this instead of it being a special case?
=> Allow spaces in comments again.

lib/perl/Genome/Model/SomaticVariation/Command/TierVariants.pm
The specific scenario motivating this PR is that the `copy-number-with-bam-window` detector runs two mini DV2s inside of itself.  The results generated by those detectors were previously not linked to the build, but the user-tracking system means that the build is now their `creator`.  Since all the official DV2 results should [have the `uses` label applied](https://github.com/genome/genome/blob/166fc8310843c2f73f34e887731b9fc2bbdd9a07/lib/perl/Genome/Model/SomaticVariation/Command/DetectVariants.pm#L87-L90), limit our search here to those results.
=> When Tiering in SomVar only Consider Results we "Use"

lib/perl/Genome/InstrumentData/Command/MergeAlignments.pm, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator.pm
The `BwamemStream` aligner uses a bedtools version.  This was wired up for `ReferenceAlignment` but also needs to be added to the `MergeAlignments` step used by the alignment dispatcher.
=> Pass bedtools version to merge

lib/perl/Genome/VariantReporting/Process/Trio.pm
The yaml is just metadata, not a real output of the process.
=> Exclude yaml from trio process diffs

lib/perl/Genome/InstrumentData/AlignmentResult.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Command/RecreatePerLaneBam.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Command/RecreatePerLaneBam.t
Most of our in-house bams do not include qc-failed reads, but some bams do include those, while currently recreate_bam command has include_qc_failed turned off. This bug causes unexpected bam flagstat diff and bam recreation failing. This PR is to fix the bug and recreate per lane bam to its original.
=> Include QC failed reads when recreating per lane bam from merged bam

lib/perl/Genome/InstrumentData/AlignmentResult.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm, lib/perl/Genome/InstrumentData/AlignmentResult_regenerate.t, lib/perl/Genome/Model/Tools/Htseq/Count/Result.pm
This PR allows `revivified_alignment_bam_file_paths` to handle its own temporary allocation to ease the burden on those who would call it.
Arguably we should refactor `revivified_alignment_bam_file_paths` and `alignment_bam_file_paths` into the same method with a `force` parameter but that is not yet included.
=> Refactor revivified_alignment_bam_file_paths to handle its own tempdir.

lib/perl/Genome/Model/ClinSeq/Command/MicroarrayCnv.pm
The MRS1 were failing due to reaching the default memory limit of 4 GB. As a
quick fix I increased memory to 16 GB and the models were run but only
consumed about 6.5 GB so for this change I've limited the reservation to 8 GB.
See [RT#105133][1] for additional context.
[1]: https://rt.gsc.wustl.edu/Ticket/Display.html?id=105133
=> reserve 8 GB memory for ClinSeq's MicroarrayCnv

lib/perl/Genome/Model/SomaticVariation/Command/DetectVariants.pm
```
$ perl -W -e 'my @x = 1,2;'
Useless use of a constant in void context at -e line 1.
```
=> Include the LQ results in the array so they get linked to the build

lib/perl/Genome/InstrumentData/AlignmentResult/Merged.t, lib/perl/Genome/Utility/Test.pm
We should disable diagnostics when using `compare_ok()` with binary files.
=> disable diagnostics when using compare_ok with binary files

lib/perl/Genome/Model/Tools/CopyNumber/CnView.pm.R
This PR adds a check for the empty segments case. Currently this errors out with 'replacement empty' error.
=> check for empty segments

bin/genome-env
@mcallaway discovered this bug when trying to use `genome-env` on a newer Bash
version,
$ genome-env -D ...
.../genome-env: line 279: SUBMODULES: unbound variable
=> fix bug exposed in newer Bash versions

lib/perl/Genome/Model/Build/ReferenceSequence.pm, lib/perl/Genome/Site/SGMS.pm, lib/perl/Genome/Site/TGI/Extension/Sys/Lock.pm, lib/perl/Genome/Sys/Lock.pm
Due to the maintenance window all snapshots prior to genome-3591 have been
archived which means it's safe to remove these lock scopes now.
=> remove 'unknown' and 'tgisan' lock scopes

lib/perl/Genome/Model/Tools/BamQc/Run.pm
Fixed a bug from PR#663. It is causing test ref-align build failure. It need to be merged ASAP.
=> Bug fix: bam_file, not get_bam_file

lib/perl/Genome/Model/Command/Report/List.pm, lib/perl/Genome/Model/Tools/Consed/TracesToConsed.pm, lib/perl/Genome/Model/Tools/DetectVariants2/Dispatcher.pm
These are other places in the system that spelled `quitting` and `available` similarly to #669.
(I'll resist going further down the rabbit-hole by cleaning up `gmt consed traces-to-consed`.)
=> Fix more typos.

lib/perl/Genome/Model/Tools/Vcf/EvaluateVcf.pm, lib/perl/Genome/Model/Tools/Vcf/EvaluateVcf.t, lib/perl/Genome/Model/Tools/Vcf/VcfCompare.pm, lib/perl/Genome/Model/Tools/Vcflib.pm
This is part 1 of a 2 to 3 part roll out to integrate the [VCF Evaluation scripts][1] within the genome codebase.  The aim of this pull request is to get [evaluate_vcf.pl][2] setup as a GMT.  [evaluate_vcf.pl][2] contains the core vcf comparison algorithm.  
Performance adjustments and [additional logic][3] that work on top of the core logic will be added in future pull requests.
This pull request introduces logic that has been created and/or modified by @ernfrid, @tabbott , and @indraniel .  With so many hands involved, there may be some style inconsistencies.  
[1]: https://github.com/genome/vcf-evaluation
[2]: https://github.com/genome/vcf-evaluation/blob/master/evaluate_vcf.pl
[3]: https://github.com/genome/vcf-evaluation/blob/master/evaluate_vcfs.pl
=> GMT Integration of VCF Evaluation (part 1)

lib/perl/Genome/Model/Build/ReferenceSequence.pm, lib/perl/Genome/Model/ReferenceSequence/Command/FindPotentialMatches.pm, lib/perl/Genome/Model/ReferenceSequence/Command/FindPotentialMatches.t, lib/perl/Genome/Model/ReferenceSequence/Command/FindPotentialMatches.t.d/1/seqdict/seqdict.sam, lib/perl/Genome/Model/ReferenceSequence/Command/FindPotentialMatches.t.d/2/seqdict/seqdict.sam, lib/perl/Genome/Model/ReferenceSequence/Command/FindPotentialMatches.t.d/3/seqdict/seqdict.sam, lib/perl/Genome/Model/ReferenceSequence/Command/FindPotentialMatches.t.d/4/seqdict/seqdict.sam, lib/perl/Genome/Model/ReferenceSequence/Command/FindPotentialMatches.t.d/5/seqdict/seqdict.sam
Sometimes one may have a BED (or other tab-delimited) file but be unsure what reference sequences were involved in its creation (e.g. human plus several viruses).  This tool helps narrow down the candidates.
=> New command to find references that have the same chromosome names as a query file.

lib/perl/Genome/Env/GENOME_DISK_GROUP_BENCHMARKING.pm, lib/perl/Genome/Env/GENOME_DISK_GROUP_READS.pm, lib/perl/Genome/Model/Build.pm
The current *from* address evaluates to something like "apipe@ip-XX-XX" on AWS where ip-XX-XX is the `hostname`. Addresses created this way fail validation in Genome::Report::Email which uses Email::Valid.
This PR proposes to use an environment variable for specifying the email address.
Note - This PR is based on the SGMS branch on not master. This is an SGMS specific change.
=> SGMS: configure email addresses for build reports.

lib/perl/Genome/Config/AnalysisProject/Command/AddConfigBase.pm, lib/perl/Genome/Config/AnalysisProject/Command/AddConfigFile.t, lib/perl/Genome/Config/AnalysisProject/Command/AddMenuItem.pm, lib/perl/Genome/Config/AnalysisProject/Command/AddMenuItem.t
It has been requested that this be `--tags` instead of `--tag`.
=> AnP Config Add: Pluralize tag-adding option.

lib/perl/Genome/Model/Build.pm, lib/perl/Genome/Model/Build.t
This is identical to #676 but this PR is based off of master.
Note - this will change the reply-to to `donotreply@genome.wustl.edu` instead of `noreply@genome.wustl.edu`
=> use ENV variables to configure build email

lib/perl/Genome/VariantReporting/Command/ShowDocs.t.expected-output/experts/__test__, lib/perl/Genome/VariantReporting/Framework/Component/Expert/Command.pm, lib/perl/Genome/VariantReporting/Framework/Component/Expert/Command.t, lib/perl/Genome/VariantReporting/Framework/Test/Run.pm, lib/perl/Genome/VariantReporting/Framework/Test/RunResult.pm
This fixes a bug where any optional expert parameter would fail validation if it wasn't in the plan file.
See https://rt.gsc.wustl.edu/Ticket/Display.html?id=105348
=> Don't fail optional expert parameters as required during validation

lib/perl/Genome/Ptero/workflow_tests/converge/inputs.json, lib/perl/Genome/Ptero/workflow_tests/converge/outputs.json, lib/perl/Genome/Ptero/workflow_tests/converge/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/converge/workflow.xml, lib/perl/Genome/WorkflowBuilder/Converge.pm, lib/perl/Genome/WorkflowBuilder/DAG.pm
PTero itself now has support for both Block and Converge operations, but I've just implemented support for Converge operations here in Genome.  WorkflowBuilder has no concept of Block operations, and maybe never will, so I didn't try to fix that now.
=> Support Converge Operations when using Ptero

lib/perl/Genome/InstrumentData/AlignmentResult.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Nucmer.pm
This should be the last of the fixes for build failures due to per-lane bam removal. Currently, builds may fail if their alignment results have not been 'backfilled' with the .header files.
=> Create bam headers on demand

lib/perl/Genome/Model/ClinSeq/Command/AnnotateGenesByDgidb.t, lib/perl/Genome/Utility/Test.pm
```
$ diff -r v2/ v3/
diff -r v2/all_interactions.tsv v3/all_interactions.tsv
6a7,15
> NR1H2 NR1H2   22R-HYDROXYCHOLESTEROL  n/a     GuideToPharmacologyInteractions nuclear receptor subfamily 1, group H, member 2
> NR1H2 NR1H2   24(S), 25-EPOXYCHOLESTEROL      n/a     GuideToPharmacologyInteractions nuclear receptor subfamily 1, group H, member 2
> NR1H2 NR1H2   24(S)-HYDROXYCHOLESTEROL        n/a     GuideToPharmacologyInteractions nuclear receptor subfamily 1, group H, member 2
> NR1H2 NR1H2   27-HYDROXYCHOLESTEROL   n/a     GuideToPharmacologyInteractions nuclear receptor subfamily 1, group H, member 2
> NR1H2 NR1H2   ACETYL-PODOCARPIC DIMER n/a     GuideToPharmacologyInteractions nuclear receptor subfamily 1, group H, member 2
> NR1H2 NR1H2   AZ12260493      n/a …
```
=> updated expected results for Genome/Model/ClinSeq/Command/AnnotateGenesByDgidb.t

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML
This is related to a new source, GuideToPharmacologyInteractions,
that was added to DGIdb. related to #690 
The Jenkins diffs are [here.](https://apipe-ci.gsc.wustl.edu/job/2-Genome-Model-Tests-2-Run-Models/TEST_SPEC=5.10-clinseq-wer/1558/console)
=> update clinseq blessed

lib/perl/Genome/Model/Tools/Picard.pm
Prior to version 1.124, Picard was made up as a set of jars, one for
each tool, installed under `/usr/share/java/picard-toolsV.VVV/`.
Additionally, a support jar would be installed as
`/usr/share/java/picard-V.VVV.jar`.
Picard versions 1.124 and later use a single jar, installed as
`/usr/share/java/picard-V.VVV.jar`, to provide all tools.
The Picard GMT was picking up both single- and multi-jar versions of
Picard, even though it could only handle the older multi-jar versions.
This commit should prevent the Picard GMT from picking up the single-jar
versions of Picard (1.124 and later) until single-jar support can be
added.
=> Stop picking up single jar versions of Picard.

lib/perl/Genome/WorkflowBuilder/DAG.pm
We were already doing this for steps within a workflow, but some
workflows take objects as inputs and return objects as outputs.  This
allows that to work.
=> Encode/Decode workflow inputs and outputs when using PTero

lib/perl/Genome/InstrumentData/AlignmentResult.pm
This bug is preventing per_lane_tophat and bsmap alignment results from setting bam_size metric.
=> Set bam_size regardless of _use_alignment_summary_cpp

lib/perl/Genome/InstrumentData/AlignmentResult.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm
This should fix issues where we will try to estimate the bam size during merging and the `bam_size` hasn't been set on a deleted per-lane bam.
=> Get bam size from get_bam_file  instead of from alignment_bam_file_paths

lib/perl/Genome/Model/SomaticValidation/Command/IdentifyDnp.pm
The "refinements" each produce separate merged BAMs, so picking the first one we run across is not guaranteed to get the final BAM.  Thankfully we already have an accessor for choosing the proper one.
=> Use the labelled merged result in SomaticValidation's Identify DNP

lib/perl/Genome/Model/Tools/Fastqc.pm
* This is still well inside the LSF memory request.
* 51a4d27df3d515bf5697032aad5a0584d229ac91 claims this value should scale with threads.  (I don't know that we're currently scaling our request, however.  The failure case I'm addressing was run with one thread.)
=> Bump FastQC's JVM memory request to 512 MB.

lib/perl/Genome/Model/Tools/BioSamtools/AlignmentSummaryV2.pm
AlignmentSummaryV2 splits the BED into one per chromosome. For the human reference, this isn't too many, but for other combined references this may exceed the maximum number of allowed filehandles.  This PR closes the previous ones if it would open a 101st and lets them be reopened as needed.
=> Open fewer simultaneous filehandles in AlignmentSummaryV2

bin/genome-env
If there is an error trying to use the module then this will show it.
=> show stderr when trying to load module for assert_module_found

lib/perl/Genome/ProcessingProfile/Command/Create.t, lib/perl/Genome/SoftwareResult.pm, lib/perl/Genome/Utility/Test.t/compare_ok.t
I misunderstood one of the issues with `$@` so am trying to cleanup a bit.  I
looked for all `local $@` because `$@` has to be scoped very narrowly to avoid
causing problems when using `local $@`.  See [Localizing silently masks errors][1].
[1]: https://metacpan.org/pod/Try::Tiny#Localizing-silently-masks-errors
=> remove `local $@`

lib/perl/Genome/InstrumentData/AlignmentResult/Command/RecreatePerLaneBam.pm
Currently build will fail at picard ReplaceSamHeader if sort orders are different between per lane and merge bams. This PR is to match per lane bam sort order to that of merge bam.
=> Match per lane bam sort order to merge bam sort order

lib/perl/Genome/InstrumentData/AlignmentResult.pm
Reallocation is needed since revivified bam or in-place bam copy will exist for a while during merge and the temp allocation could be over-allocated if bam_size is not set.
=> Reallocate temp allocation for revivified bam or in-place bam copy

lib/perl/Genome/Command/Crud.t, lib/perl/Genome/InstrumentData/Command/Import/Manager.t, lib/perl/Genome/Notable/Command/AddNote.t
These tests fails for genome/UR#75 because a later error message is sent that
differs from the one these are testing.  The ones they are testing are still
sent but are not the last `error_message`.  I've changed the tests to try to
avoid tight coupling with the last `error_message`.
=> avoid tight coupling to last error_message

lib/perl/Genome/Model/Tools/Vcf/EvaluateVcf.pm, lib/perl/Genome/Model/Tools/Vcf/EvaluateVcfs.pm, lib/perl/Genome/Model/Tools/Vcf/EvaluateVcfs.t
This is part 3 of a roll out to integrate the [VCF Evaluation scripts][1] within the genome codebase. The aim of this pull request is to address minor differences with recent changes to [evaluate_vcf.pl][2] and minor annoyances with the final summary report.
* use `NaN` instead of `0` for divde by zero cases
* use `has_transient_optional_output` instead of `has_output` for the transient output hash storing the statistical results
* store the statistical results to a JSON file
See internal jira issue [BIO-1387][3] for details.
[1]: https://github.com/genome/vcf-evaluation
[2]: https://github.com/genome/vcf-evaluation/blob/master/evaluate_vcf.pl
[3]: https://jira.gsc.wustl.edu/browse/BIO-1387
=> GMT Integration of VCF Evaluation (part 3)

lib/perl/Genome/InstrumentData/AlignmentResult.pm
Change LockMigrationProxy back to LockProxy since the migration of lock resource from G::I::AR::Merged to G::I::AR is done.
=> Replace LockMigrationProxy with LockProxy

lib/perl/Genome/Disk/Allocation.pm, lib/perl/Genome/Disk/Command/Allocation/Unarchive.t, lib/perl/Genome/Disk/Detail/Allocation/Archiver.pm, lib/perl/Genome/Disk/Detail/Allocation/Purger.pm, lib/perl/Genome/Disk/Detail/Allocation/Unarchiver.pm
I found 391 allocations that had their `status` still set to 'archived' but
their `mount_path` was not a `/gscarchive` path.  These changes are possible
fixes for what may be causing that inconsistency.
=> try to improve consistency of unarchiving

lib/perl/Genome/Model/Tools/BioSamtools/AlignmentSummary.pm
This uses a coarser coordinate index as the number of contigs (chromosomes) increases.  We were running out of memory on a reference with > 30k contigs.  With this change it succeeded with a runtime still under an hour.
(In general there might be better ways of going about this--that's why `AlignmentSummaryV2` exists!  But we run both of them, since they produce slightly different results.)
=> Reduce AlignmentSummary (V1) cache size based on contig count

lib/perl/Genome/Model/Tools/Validation/LongIndelsPartOne.pm, lib/perl/Genome/Model/Tools/Validation/SvManualReviewContigs.pm
This adds the `is_rederivable` flag to the references created in these GMTs, which makes them like the ones created in the SomaticValidation pipeline.  (The practical effect is that such references will not be stored in the location to which `Genome::Config::get('disk_group_references')` points.)
=> Set validation references as being rederivable.

lib/perl/Genome/Config/AnalysisProject/InstrumentDataBridge.pm
The backing column's type is an `integer` itself.
(CQID is currently failing because it's trying to set a fail_count of 10,000.)
=> Remove length restriction on fail_count.

lib/perl/Genome/Model/Tools/TigraSv.pm
This version only lived in a home directory, which has been removed.
Version 0.1 is the "default" specified [in `Genome::Model::Tools::DetectVariants2::Filter::TigraValidation`](https://github.com/genome/genome/blob/d50a74cd0998c9a1618c789609ff62502119b2b1/lib/perl/Genome/Model/Tools/DetectVariants2/Filter/TigraValidation.pm#L77).
=> Remove tigra-sv version 20110321

lib/perl/Genome/Model/Build.pm
* Spelling: `Stauts` => `Status`
* Change `is` to `has`, since the build might have a different literal status.
=> Spelling/grammar changes to Heartbeat Check

lib/perl/Genome/Sys/Log.pm
Can't require Genome::Model::Build at top of because it creates a circular
dependency Genome::Model::Build uses Genome which uses Genome::Sys::Log which
uses Genome::Model::Build.
=> fix circular dependency

lib/perl/Genome/Model/Tools/DetectVariants2/CopyCatSomaticWithBamWindow.pm, lib/perl/Genome/Model/Tools/DetectVariants2/CopyCatSomaticWithBamWindow.t
If there is no annotation data specific to our reference, try looking at references from which ours is derived.
=> Search base references for CopyCat annotation data

lib/perl/Genome/DataSource/CommonRDBMS.pm, lib/perl/Genome/InstrumentData/AlignmentResult.pm
An upcoming change to UR fixes a bug in the signal validation code that 
exposes cases where a class did not define `valid_signals` nor a
`validate_subscription` method.  This is one such example.
=> add valid_signals

lib/perl/Genome/Model/Build.pm
An instance without a parallel_index for parallel_by jobs doesn't point back to the operation the way the jobs with the parallel_index do.  It doesn't refer to a job that will be scheduled to LSF, so there's no need to investigate it further.
=> Heartbeat check only if operation_type exists.

lib/perl/Genome/Model/Build.pm
DV2 dispatchers and other jobs that spawn workers and wait on them will spuriously report no log updates in 48 hours under `Flow`.  Skip these steps instead and report on their children's status.
=> Don't report idle parents of running children in heartbeat check.

lib/perl/Genome/Sys.pm
The require is included inside the subroutine because we don't have the module installed for Perl 5.8.  (I generally believe that it is safe to stop supporting Perl 5.8, but there's no reason to force the issue here.)
=> Use String::QuoteShell to do quoting for shell.

lib/perl/Genome/Site/TGI/Extension/Sys/Lock.pm
This was not caught by testing on the PR because `GENOME_NESSY_SERVER` isn't
set on PR tests (yet).
=> fix `register_callback` call because subject is not valid for that API

lib/perl/Genome/Disk/Allocation-rollback.t, lib/perl/Genome/Disk/Allocation.pm
When an allocation is rolled back UR would, for example, run
`$a->archivable(0)` which since `archivable` is an overriden property would
have unintended side-effects.
=> avoid side effects if an allocation is rolled back

lib/perl/Genome/SoftwareResult/User.pm
We had a case where no sponsor was found for a build which caused a warning
about odd number of elements in the hash and then failed downstream.
=> validate values to hash

lib/perl/Genome/Site/TGI/Extension/Sys.t, lib/perl/Genome/Sys.pm, lib/perl/Genome/Sys.t
There have been several builds in rt 104974 crashing because a call to create_symlink() fails due to the link already existing, but the existing link already has the same target as is being requested, and I can't figure out where the link is being created from.
It seems safe to allow this condition to succeed.
=> Make Genome::Sys->create_symlink() idempotent

lib/perl/Genome/Disk/Command/Group/AvailableSpace.pm, lib/perl/Genome/Disk/Command/Group/AvailableSpace.t
I'm migrating this to a Jenkins task, so that will be responsible for alerting if trouble arises.
=> Remove alert from `genome disk group available-space` report

lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
* Count all builds when deciding if there are too many failures.  (We regularly abandon failures preceding previous successes, so these would usually all be "newer" than the last success.)
* Allow the maximum fail count to be specified.  (I currently believe 5 might be on the high side, but that could be mitigated by improving the `model_has_progressed` check.)
=> Model Summary: Allow specification of max fail count

lib/perl/Genome/Site/TGI/Synchronize/SyncLimsAndGenome.pm
We don't need to bother registering 100s of thousands of "unload" records as changes inside the transaction.  Since transactions only verify changed objects, this will save tons of unnecessary work.
=> Unload LIMS entities outside of the transaction.

lib/perl/Genome/Model/Build.pm, lib/perl/Genome/Model/Build/Command/Start.pm, lib/perl/Genome/Model/Build/Process.pm, lib/perl/Genome/Model/Command/Define/ImportedAnnotation.t, lib/perl/Genome/Model/SomaticValidation/Command/ValidateLargeIndels/CreateAssembledContigReference.pm, lib/perl/Genome/Process.pm, lib/perl/Genome/Process/Command/Run.pm
This makes it so that when server_dispatch != inline, the `Build` uses a `Genome::Process` to execute the workflow.  There should be no changes for server_dispatch == inline.  This is a necessary step towards full PTero integration, and should make it possible to run builds with PTero in the same way that you can run processes with Ptero.
Model tests that I ran by hand diffed clean (rnaseq, somatic-validation and somatic-variation).
One side-effect of this change is that every build will use Flow unless you explicitly set WF_USE_FLOW=0.  This is because the `Genome::Process` framework defaults to using Flow unless it is already set.
=> Builds use processes

lib/perl/Genome/Role/Logger.pm, lib/perl/Genome/Role/Logger.t
I'm trying to avoid just blindly using Genome which can trigger accidental
circular dependencies if packages such as this are used by any of the packages
that are loading during `use Genome`.
=> don't need to use Genome here

lib/perl/Genome/Sys/Command/Search/Index.pm
The property name was changed in 9a7b89d0ce79eb135d72df0586a9faf41d654dac.
=> Call renamed accessor in search index command.

lib/perl/Genome/Model/ClinSeq/Command/Converge/Base.pm, lib/perl/Genome/Model/ClinSeq/Command/UpdateAnalysis.pm
Two minor things being committed:
1.) Allow users to run converge tools on a set of clin-seq build that span across multiple individuals (but only if they use the `--force` option because this should only be done carefully)
2.) When searching for existing genotype microarray models, now do this two ways.  First, obtain all genotype microarray models that are using the default_genotype_data for a sample.  Second, obtain all genotype microarray models that are associated with the sample (may or not be using the default_genotype_data).  
This is needed because occasionally the default_genotype_data for a sample is actually generated using *another* sample.  But we can't always use the first method because sometimes we have generated new genotype microarray data (and models) that we want to …
=> minor update to clinseq to handle some edge cases

lib/perl/Genome/Sys-shellcmd.t, lib/perl/Genome/Sys.pm
This skips the `bash -c` and eliminates the need to worry about properly quoting arguments!  (The old way is still available for using commands that involve pipes and the like.)
* Should whether or not to use `bash -c` when supplying an array be a separate option?
=> Allow specifying the command as a list in Genome::Sys->shellcmd

lib/perl/Genome/Model/Build/Command/DetermineError.pm, lib/perl/Genome/Model/Command/Admin/FailedModelTickets.pm, lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
* Instead of doing its own workflow inspection, decide if it failed the same way twice by the error found by the `genome model build determine-error` command.
* Fix the `previous_build` finder to not find the first build instead!
=> ModelSummary uses DetermineError to decide build progress

lib/perl/Genome/Config.pm, lib/perl/Genome/Config.t, lib/perl/Genome/Config/Command/Validate.pm, lib/perl/Genome/ConfigSpec.pm
This add a `default_from` field to the configuration spec allowing the default
value to be found via the specificed key.
This could allow a specific tool to use defaults for a common parent, e.g. all
the `gmt picard` commands could share a default value while allow each specific
command to be overridden in configuration.
It could also be used to help migrate configuration variables names (keys)
while coupling the `default_value`.
=> add `default_from` to config

lib/perl/Genome/Model/SomaticVariation/Command/CreateReport.pm
A recent build failed because `/tmp` was full.  Since this step uses `/tmp`, request some!
=> Set a default tmp space request for SomaticVariation's CreateReport step

lib/perl/Genome/Model/SomaticVariation/Command/AnnotateAndUploadVariants.pm
Defining the request once ought to be enough!
=> Remove second lsf_resource property in AnnotateAndUploadVariants

lib/perl/Genome/Model/Tools/Speedseq/Base.pm, lib/perl/Genome/Model/Tools/Speedseq/Base.t
I made a local install of the gms branch of speedseq at `/gscmnt/sata849/info/speedseq_freeze/v1/speedseq/bin/speedseq`. This is a precursor to ultimately packaging speedseq. Right now we just wanted to stop pointing to the Hall lab version of speedseq and have a local version installed so that we aren't affected by changes in the Hall lab install. 
Right now /gscmnt/sata849/info/speedseq_freeze/v1/speedseq/bin/speedseq.config points to `PYTHON=/gscmnt/gc2719/halllab/bin/gemini_python` because `/usr/bin/python2.7 doesn't have pysam installed. This is being addressed by systems in https://jira.gsc.wustl.edu/browse/INFOSYS-16236. Once python has been updated I will update  the config file to point to our /usr/bin version, thus removing the last dependency on any local Hall lab installs.
=> Update speedseq test version to our frozen version

lib/perl/Genome/InstrumentData/AlignmentResult.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Speedseq.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Speedseq.t
Previously the AlignAndMerge step would create a merged alignment object (e.g. run Speedseq) and then use it to create the per-lane alignment objects. We would use revivification to create the per-lane bam so that we could create a .header and .flagstat file (and do some other per-lane alignment processing). As a result of having to revivifiy each per-lane bam for all the instrument data (in serial), the AlignAndMerge step would run extremely long.
This PR makes it so that the AlignAndMerge step will still run the aligner to create the merged alignment object but this step will only create the per-lane alignment objects without any further processing. .header and .flagstat file creation are postponed until the first call to get_bam_file. Calling this subroutine will run revivification …
=> AlignAndMerge only creates per-lane alignment objects without revivification

lib/perl/Genome/Model/Tools/Dindel/Base.pm, lib/perl/Genome/Model/Tools/Dindel/MakeDindelWindows.pm, lib/perl/Genome/Model/Tools/Dindel/VcfToDindel.pm
The volume it used to live on was removed.  This makes it use the packaged
version.
=> Get dindel working again

lib/perl/Genome/Model/Event/Build/ReferenceAlignment/AlignReads.pm, lib/perl/Genome/SoftwareResult/User.pm
This makes sure the user relationship is not created more than once.
I find the `linked alignment ... to the build` debug message to still be useful, but maybe we don't need to separately verify the user was created here?
=> Lock all SR User construction to enforce uniqueness.

lib/perl/Genome/SoftwareResult.pm
The message will now look like:
```
DEBUG: Cleaning up lock genome/Genome::Example/1234567890abcdef1234567890abcdef...
```
rather than:
```
DEBUG: Cleaning up lock Genome::Sys::LockProxy=HASH(0x6543210)...
```
=> Print the resource in the debug message, not the object hash.

lib/perl/Genome/Model/SmallRna.pm.xml, lib/perl/Genome/Model/SmallRna/Command/SmallRnaWorkflow.xml
WorkflowBuilder was failing to validate these workflows, because they strangely were mapping several things into the final `result`.  This deduplicates the ones in the outer workflow and simply removes them from the inner workflow.
(This is another case where `?w=1` comes in handy viewing the diffs!)
=> Remove Doubled-Up SmallRNA Workflow Links

lib/perl/Genome/Sys-shellcmd.t, lib/perl/Genome/Sys.pm
Only three modules are currently using `redirect_stdout`, two of which send it to `/dev/null`, and `Genome::InstrumentData::Command::Import::WorkFlow::SraToBam` which is using it while writing a BAM file.  Seems like an extra newline isn't desirable there.
This reverts commit ba557795fe0e72ca1d4a691230206d9e39e7e80e.  (Is there a reason to keep the extra newline that I'm missing?)
=> Only print an extra newline if output was not redirected.

lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
As promised, here's the next phase of ModelSummary revisions.  We now use sets and iterators to avoid loading most builds.
Some of the functionality has changed. Many places are more selective about which builds are considered.  (`Abandoned` builds are more consistently ignored; deciding whether a model "has progressed" now considers the previous failure (whether `Failed` or `Unstartable`)).
I'm not sure this works properly for builds with `Unknown` status...
=> Reduce Build Loading in ModelSummary

lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm
Looks like rollback() was blanking $_, making the error message not
helpful.
=> Ensure the exception message shows up in the error message.

lib/perl/Genome/InstrumentData/AlignmentResult/Merged/Speedseq.pm, lib/perl/Genome/InstrumentData/Composite/Workflow.t
Previously, we would specify `threads => 8` in the aligner params portion of the alignment strategy for speedseq. This would get passed into the speedseq wrapper and would set the `-t 8` parameter which would allow speedseq to run with 8 threads (or whatever number was specified in the alignment strategy). 
This PR makes it so that the number of threads are not being defined in the alignment strategy anymore. Instead the `-t` parameter is being set by calling `_available_cpu_count` which under the hood examines the LSF resources of the current job. 
This ensures that the `-t` parameter of speedseq is the same value as the number of cpus requested in LSF and it also makes it so that the number of threads aren't part of the lookup hash of the software result anymore. Speedseq software …
=> Update speedseq to not pass number threads along as an aligner_param

lib/perl/Genome/Model/GenotypeMicroarray.pm
Allow getting of dependent cron ref align models w/o reference first, then
filter by if the reference is compatible.
=> Genotype Microarray Dependent Cron RefAlign

lib/perl/Genome/Model/Command/Admin/FailedModelTicketBase.pm, lib/perl/Genome/Model/Command/Admin/FailedModelTicketStatus.pm, lib/perl/Genome/Model/Command/Admin/FailedModelTickets.pm
Conveniently examine existing tickets from the command-line.  Assuming that the ticket body was created with the model ID at the start of each line (as in the output format of `failed-model-tickets`) and that any additions are replies and not comments, this command will list the current status of the listed models.
(This is how I've been going through and closing tickets when rebuilds from `model-summary` were successful.)
=> New command: failed-model-ticket-status

lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Merged/Speedseq.pm, lib/perl/Genome/InstrumentData/Command/AlignAndMerge.pm, lib/perl/Genome/InstrumentData/Composite/Workflow.t, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/AlignAndMerge.pm
Previously, lsf resource usage for `AlignAndMerge` was hardcoded (and did not include gtmp). Now tmp usage will be calculated dynamically based on the size of the input instrument data.
Unfortunately, that necessitates the sort of kludgey approach taken here. The `lsf_resource` param on the command does not have access to the particular command instance of a given run, and thus cannot know how many instrument data are attached. Instead, we staple the lsf resource requirements in at workflow construction time (this is done in other places as well, so it isn't unprecedented in our codebase).
=> Dynamic resource requirements for AlignAndMerge (Speedseq)

lib/perl/Genome/Model/Command/Define/GenotypeMicroarray.pm, lib/perl/Genome/Model/GenotypeMicroarray.pm
I will remove the params params params from the DB once the PR is in a snapshot.
=> GenotypeMicroarray: remove unused import_format param

lib/perl/Genome/Model/ClinSeq/Command/UpdateAnalysis.pm
This pull request added 2 options to clin-seq update-analysis. 1) --validation-as-exome allows users to combine exome and validation instrument data when setting up reference alignments. 2) --my-trsn allows the user to specify which instrument data (validation or exome) to use for the target-set-region-name and region-of-interest options when using --validation-as-exome.
=> Add options to clinseq update-analysis to use validation data as exome data

lib/perl/Genome/Model/ReferenceSequence/Command/CreateAlignerIndex.pm
Annotation index is not required since annotation_build is optional. The bug is detected in RT#106815. CreateAlignerIndex.pm needs some refactoring that will be done by the future PR.
=> Making annotation index process optional

lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.pm
CQID tries to assign instrument data for models that were gotten or created by the configuration matching that instrument data.  It doesn't make sense to then not assign that instrument data to the model, so ensure the assignment always happens.
=> CQID: Trust the configuration to know what instrument data to assign.

lib/perl/Genome/Model/Build/SomaticValidation.pm
The design_set isn't used in the pipeline--it is the source of the target_region_set (whose reference we already ignore).
=> Don't worry about design_set reference in SomaticValidation

lib/perl/Genome/WorkflowBuilder/Block.pm, lib/perl/Genome/WorkflowBuilder/Detail/Operation.pm, lib/perl/Genome/WorkflowBuilder/Detail/TypeMap.pm
The "gene-prediction eukaryotic" pipeline was broken by the switchover to `WorkflowBuilder` for all build validation.  This is one step towards making it work again.
=> WorkflowBuilder class for Block operations.

lib/perl/Genome/Model/GenePrediction/Command/Eukaryotic/SplitFasta.pm, lib/perl/Genome/Model/GenePrediction/Eukaryotic.pm.xml
`WorkflowBuilder` cares about the difference between an `ARRAY` and an `is_many` property as the input to a `parallelBy` workflow.  (This is the second and hopefully final part of fixing gene-prediction eukaryotic.)
=> GP Eukaryotic: Make fasta_files is_many in SplitFasta

lib/perl/Genome/InstrumentData/Composite/Workflow.t, lib/perl/Genome/Qc/Result.pm, lib/perl/Genome/Qc/Tool.pm
This change is needed to support running verifyBamId on the merged alignment result. The QC framework continues to support running QC tools on the per-lane alignment results.
=> Allow QC framework to work on merged alignment results

lib/perl/Genome/Ptero/Wrapper.pm
The die message in the catch block was not being written to the log
file, instead it was only visible on the PTero Execution object.
=> Ensure reason for error is written to the log file

lib/perl/Genome/InstrumentData/AlignmentResult/PerLaneTophat.pm, lib/perl/Genome/InstrumentData/AlignmentResult/PerLaneTophat.t
* Remove some old `TODO`s left over from before the redaction.
* Add the letter `n` and subject-verb number agreement.
* Remove trailing whitespace.
=> Minor Cleanup of PerLaneTophat module

lib/perl/Genome/Process.t, lib/perl/Genome/SoftwareResult/User.pm, lib/perl/Genome/SoftwareResult/User.t, lib/perl/Genome/Utility/ObjectWithLockedConstruction.pm
This should be merged only after no running builds are on a snapshot prior to `genome-3607`.
=> Remove other locking now that SR::User is ObjectWithLockedConstruction.

lib/perl/Genome/Config/AnalysisProject.pm, lib/perl/Genome/Config/Profile/Item.pm, lib/perl/Genome/Model/GenotypeMicroarray-post_success.t, lib/perl/Genome/Model/GenotypeMicroarray.pm, lib/perl/Genome/Model/GenotypeMicroarray.t, lib/perl/Genome/Sample-add_default_genotype.t
This should eliminate the issue of new microarray data triggering rebuilds of old/outdated models.
=> Only schedule current dependent reference alignments.

lib/perl/Genome/Model/Command/Admin/PurgeSoftwareResultsFromAnalysisProject.pm
This adds a command for purging/expunging software results given one or more analysis projects.
It's based on jwalker's basic script, converted to a genome model command, and added locking around each anp to prevent multiple instances from stomping on each other.
=> Project purge command

lib/perl/Genome/Utility/Inputs.pm, lib/perl/Genome/Utility/Inputs.t
It now supports:
- Mixed element types in ARRAYs
- Nested ARRAYs
- Non-object HASHREFs
Error handling around object decoding has been improved.
=> Rewrite Genome::Utility::Inputs to support more

lib/perl/Genome/Sys.pm
Unmounted volumes will not return EEXIST from mkdir().  Checking for
directory existence triggers the automounter to ensure the volume is
mounted before trying to create it.
=> Also test for directory existence before trying to create it.

lib/perl/Genome/Disk/Volume.pm
The regex was failing to match /vol/aggr3/ which only contained one digit
=> It'll now work with aggrs containing any number of digits.

lib/perl/Genome/Config/AnalysisProject/Command/AddConfigFile.pm, lib/perl/Genome/Config/AnalysisProject/Command/AddModel.pm, lib/perl/Genome/Config/AnalysisProject/Command/AddModel.t, lib/perl/Genome/Config/AnalysisProject/Command/View.pm, lib/perl/Genome/Config/Profile.pm, lib/perl/Genome/Config/Profile/Item.pm
Add inactive status for analysis project config profile items.  The inactive status is used for the store-only option when adding config.
=> Inactive analysis project config profile item status

lib/perl/Genome/Command.pm, lib/perl/Genome/Command/PteroWorkflowMixin.pm, lib/perl/Genome/Ptero/workflow_tests/converge/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/converge/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json, lib/perl/Genome/Test/Command.pm, lib/perl/Genome/Test/Command/Echo.pm, lib/perl/Genome/Test/Command/RunSimpleProcess.pm, lib/perl/Genome/WorkflowBuilder/DAG.pm
The PTero system now understands links between tasks that are not data-flow related.  This PR updates the building of PTero workflows to utilize this new feature.
I've also added a couple of commands related to running a Genome::Process::Test::Process that are helpful for manually testing the ability to submit to Processes to PTero without using the more computationally intensive and complex trio variant-report.
Since libptero-perl 0.1.7 has been deployed before this PR, the unit-tests in Genome::Ptero will fail until this PR is merged.  That is because the libptero-perl library changed how it renders JSON representations of workflows to be compatible with the PTero workflow service.
=> PTero: Control flow feature

lib/perl/Genome/WorkflowBuilder/StreamGraph.pm
The motivation for this change is to make sure the database handle is disconnected before running.  Alternatively we could add an explicit disconnect before the call here.
=> Use shellcmd instead of IPC::Run.

lib/perl/Genome/Model/Tools/Varscan/LohSegments.pm
This pull-request removes individual LOH points from the plots which are a bit confusing and don't add a lot of information. The tumor VAF for these points are still plotted, along with the identified segments which should provide the information we need.
=> Remove unwanted points from LOH plot

lib/perl/Genome/Model/Build/ReferenceSequence/AlignerIndex.pm, lib/perl/Genome/Model/Build/ReferenceSequence/AnnotationIndex.pm, lib/perl/Genome/Model/Build/ReferenceSequence/IndexBase.pm
AnnotationIndex was copy+pasted from AlignerIndex and the two had started to drift.  This reconciles most of the differences and eliminates most of the duplication between them.
=> Deduplicate Aligner and Annotation Index Classes

lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalsePositiveVcfBase.pm, lib/perl/Genome/Sys/Lock.pm, lib/perl/Genome/WorkflowBuilder/DAG.pm
The specific motivation for this change: The database "pausing" feature will disconnect handles, but not if the pause is both set and cleared before the program has a chance to notice.  It may then be left holding a stale handle when it does return.
=> Disconnect Database Handles before potentially long-running actions

lib/perl/Genome/Model/Tools/Bedpe/EvaluateBedpe.pm, lib/perl/Genome/Model/Tools/Bedpe/EvaluateBedpe.t, lib/perl/Genome/Model/Tools/Bedpe/EvaluateBedpes.pm, lib/perl/Genome/Model/Tools/Bedpe/EvaluateBedpes.t
In some cases, we want to require more than one hit to count an sv as a 'true positive'.  We also want to save the actual svs in json for further processing.
=> Add the ability to specify a minimum number of hits required

lib/perl/Genome/Site/TGI/Command/SyncSysUserWithLdap.pm
* The tool has a threshold to avoid doing too much work, but it was failing to count deletes towards that limit.
* If the limit is exceeded it prints a message, but that message had no newline (so it would potentially be buffered for a long while).
=> LDAP Synch: Fix counting bug and cleanup

lib/perl/Genome/InstrumentData/AlignmentResult/Command/RecreatePerLaneBam.pm
Since the `$temp_flagstat` gets cleaned up on failure, this provides a way to see how it was different from expected.
=> Dump flagstat data when comparison fails.

lib/perl/Genome/Model/SomaticVariation/Command/Loh.pm
This lets a `SomaticVariation` build proceed even though the combination of inputs and processing profile doesn't work.  (This is similar to #891.)  I could see a stronger argument for this one leaning the `Unstartable` way.  On the other hand, we should stop using `SomaticVariation` altogether!
=> Don't try to run LOH without a normal to compare to.

lib/perl/Genome/Model/Build.pm
We have a use case for CLE regression testing where
we are making new models in a testdb and want to diff
the resulting builds with builds from old models.  They
should be equivalent, but not the same model.
I don't see any reason why this check adds to the
integrity of the diff
=> Don't require builds to be from the same model to diff

lib/perl/Genome/ProcessingProfile/ReferenceAlignment.pm
A common misconfiguration of a project seems to be to assign an annotation build input to a reference alignment that is not going to run variant detection.  This currently results in a build failure.
With this change, the build should succeed and not worry about the (then unused) annotation input.  (The alternative change would be to make such a build "Unstartable" so it fails fast.)
=> Only schedule annotation if we have variants to annotate.

lib/perl/Genome/Sys/Lock.pm
If we're not waiting this will return quickly and so we don't need to disconnect.
=> Don't disconnect if we're not going to wait on the lock.

lib/perl/Genome/Model/Command/Admin/PurgeSoftwareResultsFromAnalysisProject.pm
Without this change, the script might delete results that are also used by `inactive` config items.
=> Account for the existence of other non-disabled statuses.

lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
A monitoring tool is being developed to help track the progress of data through sequencing and analysis.  Right now it uses `$model->status`, but it would benefit from being able to grab the full summary (without needing to capture `STDOUT` and parsing it).
=> Allow Programmatic Access to ModelSummary information

lib/perl/Genome/SoftwareResult/User.pm
This fixes a bug where someone else with the reference was manipulating the hash between passing it and us using it, making our users disappear.
=> Save a copy of the users hash.

lib/perl/Genome/InstrumentData/AlignmentResult/Merged/Speedseq.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Speedseq.pm
Threads are overwritten inside the tool.  I heartell it should be safe to ignore the other two as well.
(Existing processing profile mostly have no parameters specified at all, so this shouldn't have much effect on results we already have.)
=> Filter out thread count, max memory, and verbosity from lookup hash.

lib/perl/Genome/Model/Tools/VerifyBamId.pm
For production QC we want to be able to run verifyBamId by read group.
=> verifyBamId: Make the --ignoreRG param optional

lib/perl/Genome/Site/TGI/CleTest.pm, lib/perl/Genome/Site/TGI/CleTest.pm.yaml, lib/perl/Genome/Site/TGI/CleTest.t, lib/perl/Genome/Site/TGI/CleTest/prime-db.pl
Some of the items from config are also needed in the prime db script
We might consider putting all of the items needed in the prime db script
in the config, but that might also be confusing, I'm not sure
=> Deduplicate between config and prime-db script

lib/perl/Genome/Model/Build/SomaticValidation.pm
The important strelka results will be diffed in the vcf files.
The remaining files in this directory are intermediate files
and contain a lot of non-diffable items like times and file
paths.
Our current model test for somatic validation doesn't run strelka, but the ones we want to use for the cle regression test do.
=> Ignore strelka subdirectory

lib/perl/Genome/Site/TGI/ReconcileSampleGenotypeData.pm
This avoids repeatedly searching through a list with tens of thousands of items!
=> Reconcile Genotype: Make a lookup hash for the attributes.

lib/perl/Genome/InstrumentData/AlignmentResult.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Speedseq.t, lib/perl/Genome/InstrumentData/AlignmentResult_regenerate.t
The original get_merged_bam_to_revivify_per_lane_bam will get smallest unarchived merged bam to revivify per lane bam. It will fail after we remove superseded merged bam. This rewrite will get whatever bam that is available.
=> Rewrite get_merged_bam_to_revivify_per_lane_bam method to meet the need of removing superseded merged bams

lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
We don't usually run this on unbuilt models, so this hasn't been a big issue so far.  But it's better to not queue models that will inevitably fail!
=> Don't try to queue "Buildless" models.

lib/perl/Genome/ProcessingProfile/Command/Create/Base.pm
I'm not sure this condition is ever met in production, anyway.
=> Fix typo in method call in PP help generation

lib/perl/Genome/Sys-sw.t
When GATK 3.4 was installed, this test needed to be updated to match it
=> Get test passing for new version of GATK

lib/perl/Genome/Qc/Command/BuildMetrics.pm
I heartell it may be useful to call this command from within Perl.  In that case it's more convenient to get the hashes back directly instead of printing and re-parsing the output.
=> Extract metrics_for_build subroutine for programmatic convenience.

lib/perl/Genome/Model/Build.pm
They will be mapped via `Genome::SoftwareResult::User` the way inputs are mapped via `Genome::Model::Input`.
This is intended to make it possible to simplify accessors like [this one](https://github.com/genome/genome/blob/045d09fa691caa7ff99f115485f98f978f5d24ac/lib/perl/Genome/Model/Build/SomaticValidation.pm#L94) and those immediately following it.
=> Lend functionality to "is_output" build properties.

lib/perl/Genome/Model/Build/Command/DetermineError.pm, lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
Without manual intervention these builds will eventually fail again, possibly after wasting hours or days of CPU.
=> Don't auto-retry MEMLIMIT errors and orphaned allocations.

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML
The merged bam of previous blessed build is removed during the removal of superseded merged bams.It is recreated in this new build. Build diff is checked ok (actually the previous one got wrong indel output). DiffBlessed.pm.YAML is updated to reflect the change. This PR need to be early merged to make apipe test build pass.
=> Update lane qc blessed build in DiffBlessed.pm.YAML

lib/perl/Genome/Model/Tools/Analysis/Coverage/BamReadcount.pm, lib/perl/Genome/Model/Tools/Sam/Readcount.pm, lib/perl/Genome/Model/Tools/Sam/Readcount.t
The bam_readcount insert_centric option was not introduced until version 0.5. This PR adds a check if the bam readcount version supports  the option before using it in the GMT Analysis Coverage BamReadcount class and asserts it is supported in the GMT Sam ReadCount command.
=> Handle insert_centric Option for Bam Readcount

bin/genome-env, lib/perl/Genome/Model/ClinSeq/Command/GetBamReadCountsMatrix.t
This test has been failing for several days. The failure is caused by the merged bams of normal/tumor ref-align builds of used som-var builds are both removed during the recent removal of superseded merged bam event. A new som-var build is used along with the new test data ouput directory. This PR need early merge to make jenkins test pass.
=> Update GetBamReadCountsMatrix.t with the new som-var build

lib/perl/Genome/Model/ClinSeq/Command/IdentifyLoh.pm
This PR modifies this module to write the results
to a temp dir and copy the results over at the end for
better performance.
=> ClinSeq::LOH - Write results to temp dir first.

lib/perl/Genome/InstrumentData/AlignmentResult/Speedseq.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Speedseq.t
SpeedSeq bundles its own version of BWA. This mapping identifies the version of BWA packaged with a particular version of SpeedSeq so that we can pass it along to other results. The 0.1.0 release of SpeedSeq is already out, but I missed updating this at the time.
=> Add entry for speedseq version to bwa version mapping

lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/AlignAndMerge.pm
36GB is not enough for some large instrument data. Ultimately this well get calculated based on the size of the instrument data once we have run more samples and have a better idea what the formula should be (similar to gtmp requested).
=> Increase speedseq LSF memory requested 

lib/perl/Genome/Model/ClinSeq/Command/AnnotateGenesByDgidb.t
There was a new DGIdb release recently, which caused this test to diff.  This adds updated expected data.
The changes can be viewed with:
```
diff $GENOME_TEST_INPUTS/Genome-Model-ClinSeq-Command-AnnotateGenesByDgidb/{v3,v4}/all_interactions.tsv
```
=> Update test to account for new DGIdb release.

lib/perl/Genome/Db/Ensembl/AnnotationStructures.pm, lib/perl/Genome/SoftwareResult.pm
* Subsequent commits of SoftwareResults generally don't need to unlock again, as the object already exists and was unlocked.
* `Genome::Db::Ensembl::AnnotationStructures` commits several times as it is working.  To avoid unlocking early, add an explicit unlock after the final commit.
* Minor fix for test names in the aforementioned class is included.
=> Only unlock SoftwareResults once.

lib/perl/Genome/Model/ReferenceAlignment/Command/GenotypeMicroarrayConcordance.pm, lib/perl/Genome/Model/Tools/BedTools.pm, lib/perl/Genome/Model/Tools/BedTools/Intersect.pm
Add options to over-ride the microarray data used.  
Limit the concordance for Exome analysis to the ROI. 
Utilize gzipped and indexed VCF whenever possible.
Add bedtools 2.24.0 as an available version.
Use the bedtools -header option when available.
=> Optional microarray build for Picard GenotypeConcordance

bin/genome-env
Before the test database is deleted, remove any allocations created during
this invocation of genome-env
=> Remove newly created disk allocations when exiting genome-env

lib/perl/Genome/Model/Build/ReferenceSequence.pm
This is a brutal proliferation of hard-coded paths to UCSC tiering files but necessary (I think) in the effort to get a new annotation build to succeed for mm10.
=> added new hard-coded path for mm10 tiering files

lib/perl/Genome/Site/TGI/Command/SyncSysUserWithLdap.pm, lib/perl/Genome/Site/TGI/Command/SyncSysUserWithLdap.t
Currently 1000 is used as response size limit for ldapsearch.  Modify this so more info can be obtained.
=> Iterate through ldapsearch output

lib/perl/Genome/Model/Tools/FastTier/MakeTierBitmasks.pm
This will work better if we use the key the code expects to see. :smile:
=> Use the correct key for passing users.

lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Merged.t
This new method will get superseding results for a given merged result. Refer to https://jira.gsc.wustl.edu/browse/APIPE-3231.
=> New method get_superseding_results added to Merged.pm

lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.pm, lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.t
In order to reduce the creation of builds that are nearly immediately superseded, this processes all available data for a sample in a single CQID run.
* This may run over the `limit` parameter, since otherwise it's possible to have a sample that will never be processed.  This version is pretty tolerant of going over, but it could be made more strict (e.g. only accepting a larger sample batch if nothing else is going to be processed) if that seems better.
* There's SQL added that is not covered by the `.t`.  It looked like it was working when I tried it manually, but it probably warrants extra attention in review!
=> CQID processes data batched by sample

lib/perl/Genome/Site/TGI/Synchronize/Classes/InstrumentDataAnalysisProjectBridge.pm
The "analysis ID" is only used to map to the Genome object for Illumina data.  Everywhere else the "seq ID" is used to refer to the object within the LIMS schema.
=> Return analysis ID but join on seq ID.

lib/perl/Genome/Model/Build/ImportedAnnotation.pm
First create command before executing.  Calling execute twice results fatal error.
=> Create Gtf::Cat command before executing.

lib/perl/Genome/Model/Command/Admin/ModelSummary.pm
(The rebuilds would fail to queue, anyway, since the models are disabled.)
=> ModelSummary: "abandon" action should not be overridden by "rebuild" action

lib/perl/Genome/Model/Build/ClinSeq.pm, lib/perl/Genome/Model/ClinSeq.pm, lib/perl/Genome/Model/ClinSeq.t, lib/perl/Genome/Test/Factory/ProcessingProfile/ClinSeq.pm
Sometimes it doesn't make a lot of sense to do copy-number calling for e.g when the data is from targeted capture of a handful of genes etc and we'd like to turn off this step. This pull-request uses a parameter in the clin-seq processing profile to handle this.
=> Add ability to skip exome CNV calling in ClinSeq.

lib/perl/Genome/Model/SomaticValidation.pm
A build without instrument data assigned for each sample on the model will fail, so report it as "Buildless" rather than "Build Needed". [Note that if there are older builds, it will report their status rather than "Buildless" or "Build Needed".]
This will have the effect of making CQID wait to launch builds until data for both samples is present.
We currently allow starting the build in this situation since it may be desired to expedite the alignments for one of the samples, but this is written to be used as-is for a start validation later if desired.
=> Defer reporting "Build Needed" if not enough instrument data assigned.

lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.pm, lib/perl/Genome/Disk/Allocation.pm, lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm, lib/perl/Genome/Model.pm, lib/perl/Genome/Process.pm, lib/perl/Genome/Process/Command/Run.pm, lib/perl/Genome/Site/TGI/CaptureSet/Command/Synchronize.pm, lib/perl/Genome/SoftwareResult.pm, lib/perl/Genome/Sys/CommitAction.pm, lib/perl/Genome/Sys/CommitAction.t, lib/perl/Genome/Utility/ObjectWithAllocations.pm, lib/perl/Genome/Utility/ObjectWithLockedConstruction.pm
This branch implements an alternative API for registering callbacks to run then the base Context commits or rolls-back intended to have fewer gotchas than using Context observers:
* They only ever fire when the base Process context is saving to data sources, never for software transactions
* They only ever fire once (except during a failure in sync_database - discussed in the docs)
* commit/rollback callbacks may by grouped together and only one of them will fire
=> Commit actions

lib/perl/Genome/Model/SomaticVariation/Command/IdentifyPreviouslyDiscoveredVariations.pm, lib/perl/Genome/Model/SomaticVariation/Command/Loh.pm
Currently $build->loh_version is used to decide whether loh runs or not, which is not accurate. This PR is to fix the bug.
=> Use should_skip_run from Loh.pm to decide whether loh runs or not

lib/perl/Genome/Model/Tools/Somatic/ProcessSomaticVariation.pm
This is useful when a build crashes in the late stages, preventing create reports from running. Gives us an easy way to at least pull out SNVs and indels without waiting for a rebuild.
=> add option to run on non-succeeded build

lib/perl/Genome/Model/ClinSeq/Command/MicroarrayCnv.pm
This variable is declared when it is initialized later (on line 409).
=> Remove early/duplicate variable declaration.

lib/perl/Genome/InstrumentData/AlignmentResult/Merged.pm
We encountered a situation wherein a BAM was superseded by another that was a combination of data for 16 samples.  This led to the per-sample BAMs being removed.
=> A superseding alignment's samples must match the samples of the alignment it supersedes.

lib/perl/Genome/Model/Tools/Vcf/EvaluateVcf.pm, lib/perl/Genome/Model/Tools/Vcf/EvaluateVcf.t, lib/perl/Genome/Model/Tools/Vcf/EvaluateVcfs.pm
This will make it easier to use the evaluation script outside of model/build paradigm
=> evaluate-vcf takes a file rather than a build

lib/perl/Genome/Model/Tools/BamQc/SummarizeAsText.pm, lib/perl/Genome/Model/Tools/Picard/CollectGcBiasMetrics.pm
This is a follow-up to changes in #998 to update a few cases that aren't covered by unit tests but were caught by the `ClinSeq` model test.
=> Fixes to Metric Parsing in ClinSeq SummarizeBuilds

lib/perl/Genome/Qc/Config.pm
- Adding the read group accumulation level drastically increases runtime
- Picard uses the RG PU field as the read group value which in our BAMs is not unique and, thus, not useful
- It's not needed for CCDG at this time
Once we have the config management system deployed this option can be turned on as needed.
=> Make read group accumulation level not the default at this time

lib/perl/Genome/Qc/Command/BuildMetrics.pm, lib/perl/Genome/Qc/Command/BuildMetrics.t, lib/perl/Genome/Qc/Command/BuildMetrics.t.d/expected_build_metrics.yml
Updates include:
Support merged QC results rather than per-lane
Use YAML output format to handle nested data structures (unflattened metrics hash).
=> Qc build metrics

lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/AlignAndMerge.pm
This is the only place left referring to this config instead of the regular one.  After this change is in all active snapshots we can remove the other variable from our deployed `config.yaml` and then from config altogether.
=> Use generic config variable for alignment queue.

lib/perl/Genome/Disk/Allocation.pm, lib/perl/Genome/Disk/Command/Allocation/Archive.pm, lib/perl/Genome/Disk/Command/Allocation/Archive.t, lib/perl/Genome/Disk/Command/Allocation/ArchiveExpired.t, lib/perl/Genome/Disk/Command/Allocation/DelayArchiving.pm, lib/perl/Genome/Disk/Command/Allocation/Unarchive.pm
The unarchive command already accepts paths; this makes them more symmetric.
=> Disk Allocation Archive command accepts paths

lib/perl/Genome/InstrumentData/AlignmentResult/WithIntermediateResults.pm, lib/perl/Genome/Model/Event/Build/ReferenceAlignment/AlignReads.pm
This fixes an issue where the IAR could not be deleted when custom users were supplied in the result user hash.  It also removes a spurious error about linking alignments to the build in ReferenceAlignment.
=> Better User Handling with IntermediateAlignmentResults

lib/perl/Genome/Model/Build/Command/Start.t
The integration (model) tests will try running a build all the way through.  This just needs to make sure Start works.  (This was testing the "inline" build process, anyway, which is not how builds are usually run in production.)
=> Don't really start builds in this test.

lib/perl/Genome/Site/TGI/UsageLog.pm
In my tests it reduces the runtime of "use Genome;" by about half a second–from ~1.2s to ~0.7s).
This potentially trades accuracy for speed, but, If we're using this as an audit log, we're going about it all wrong!
=> In the UsageLog, don't call getpwuid.

lib/perl/Genome/Model/ReferenceAlignment/Command/GenotypeMicroarrayConcordance.pm
The new snapshot slightly changes the way to call GMT::Picard's metric parsing logic.
=> Bugfix for RefAlign GenotypeMicroarray metric parsing

lib/perl/Genome/Disk/Command/Volume/List.pm
Disk Groups validate that their disk_group_name belongs to a short list
and dies otherwise to ensure Genome stuff only messes with analysis
allocations.  For a basic lister, we don't want want this safety net.
Getting the free space of an unmounted volume also throws an exception
if the volume is unmounted to avoid mounting tons of volumes.  For this
simple lister, we just print out "<unmounted>" for such volumes instead of
dying.
=> Make the volume lister work

lib/perl/Genome/Model/Tools/Gatk/HaplotypeCaller.pm
Once the HaplotypeCaller is added to the pipeline, we'll be using the buckets from #1044 to fill in the `intervals` parameter added here.
=> Add intervals parameter for GATK HaplotypeCaller

lib/perl/Genome/InstrumentData/Command/Import/Basic_archive.t, lib/perl/Genome/InstrumentData/Command/Import/Basic_bam.t, lib/perl/Genome/InstrumentData/Command/Import/Basic_bam_downsample.t, lib/perl/Genome/InstrumentData/Command/Import/Basic_bam_multi_groups.t, lib/perl/Genome/InstrumentData/Command/Import/Basic_fails.t, lib/perl/Genome/InstrumentData/Command/Import/Basic_fastq.t, lib/perl/Genome/InstrumentData/Command/Import/Basic_sra.t, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/ArchiveToFastqs.t, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/CreateInstrumentDataAndCopyBam.pm, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/CreateInstrumentDataAndCopyBam.t, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.pm, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.t, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Helpers.pm, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Helpers.t, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/RetrieveSourcePath.t, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/RetrieveSourcePathFromLocalDisk.t, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/RetrieveSourcePathFromRemoteUrl.t, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/SplitBamByReadGroup.pm, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/SplitBamByReadGroup.t
When processing files for import, generate a uuid for each read group and type (paired, singleton). Then use that red group id as the instrument data id.
=> Inst Data Import: use read group id as instdata id

lib/perl/Genome/Model/Build/Command/DiffBlessed.pm.YAML
#1012 switched to separatedvaluereader from an incorrect regex.
The updated blessed-build has the correct results.
=> Build with results from https://github.com/genome/genome/pull/1012

lib/perl/Genome/Model/Tools/Mutect.pm
When run in the pipeline it uses a hardcoded ROD that should already be indexed.  (See also
[this GATK forum thread](http://gatkforums.broadinstitute.org/discussion/1252/unifiedgenotyper-gets-hung-waiting-for-file-lock).)
=> Disable index creation in `gmt mutect`.

lib/perl/Genome/InstrumentData/Command/AlignAndMerge.pm, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/AlignAndMerge.pm
This change facilitates running the `AlignAndMerge` command outside of the alignment dispatcher.
=> Move AlignAndMerge LSF Resource generation to the command.

lib/perl/Genome/Model/Build/MetagenomicComposition16s/TestBuildFactory.pm
This way `Genome::SoftwareResult::User->user_hash_for_build` can find a sponsor.
(I don't understand how `Genome/Model/Build/MetagenomicComposition16s/ProcessAndMergeInstrumentData.t` has been passing before, but it currently fails for me even on the deployed snapshot.  This change fixes it.)
=> Add run_as to test factory model.

lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/Helpers.pm
This was failing on a BAM with parentheses in its name.
=> Use array form of shellcmd.

etc/genome/spec/db_skip_postgres.yaml
This variable could be used to skip writing to postgres.  Since support for writing to multiple databases is long gone, this is not useful.
=> Remove old db_skip_postgres configuration variable.

lib/perl/Genome/Model/Tools/Gatk/Base.pm, lib/perl/Genome/Model/Tools/Gatk/Base.t, lib/perl/Genome/Model/Tools/Gatk/HaplotypeCaller.t
The system default is currently at 1.6, but various tools in the "refine-reads" step have been segfaulting on 1.6, and using 1.7 resolves this.  Additionally newer versions of GATK require 1.7 or higher (such as for the `HaplotypeCaller`).
=> Make Java 1.7 the default for running GATK tools.

lib/perl/Genome/InstrumentData/Composite/Decorator.pm, lib/perl/Genome/InstrumentData/Composite/Decorator.t, lib/perl/Genome/InstrumentData/Composite/Decorator/AlignAndMergeQc.pm, lib/perl/Genome/InstrumentData/Composite/Decorator/Qc.pm, lib/perl/Genome/InstrumentData/Composite/Decorator/Qc.t, lib/perl/Genome/InstrumentData/Composite/Workflow-unit.t, lib/perl/Genome/InstrumentData/Composite/Workflow.pm, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator.pm, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/Align.pm, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/AlignAndMerge.pm, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/AlignerIndex.pm, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/Base.pm, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/Merge.pm, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/Refine.pm, lib/perl/Genome/WorkflowBuilder/DAG.pm
* A step on our quest to stop relying on `Workflow`!
* The old version had some UR optimizations built into it for the benefit of `PhenotypeCorrelation`.  I took those out in this conversion, but they could potentially be re-added if needed.
* This adds programmatic support for declaring an input `is_optional` in `Genome::WorkflowBuilder::DAG`s.  (The changes backing this were added in #906.)
=> Alignment Dispatcher uses WorkflowBuilder

lib/perl/Genome/Model/Build/ReferenceSequence.pm, lib/perl/Genome/Model/Build/ReferenceSequence/Buckets.pm, lib/perl/Genome/Model/Build/ReferenceSequence/Buckets.t, lib/perl/Genome/Model/ReferenceSequence/Command/CreateBuckets.pm, lib/perl/Genome/Model/ReferenceSequence/Command/CreateBuckets.t
This PR is part of adding the HaplotypeCaller to the pipeline.  The buckets will be used to parallelize the task into roughly equal-sized tasks rather than by chromosomes whose sizes vary significantly.
=> New SR to create "buckets" of chromosomes for a reference.

lib/perl/Genome/Model/Build/Command/Unarchive.pm, lib/perl/Genome/Site/TGI/Extension/Sys-lsf_api.t, lib/perl/Genome/Site/TGI/Extension/Sys.pm, lib/perl/Genome/Sys/LSF/bsub.pm
Adds a new method to Genome::Sys called bsub_and_wait_completion() that can schedule multiple LSF jobs in parallel, and wait on them without running bjobs over and over.  It sets a post-exec command for each job to send a message back to the waiter over a TCP socket.  The waiter knows all the jobs are done when it gets the message from all the jobs it's waiting on.
Then, Genome::Model::Build::Command::Unarchive is changed to use this new method.
=> More efficient unarchive wait for lsf jobs

lib/perl/Genome/Model/Tools/Tcga/Sdrf.pm
The reagent info of new target_region_set_name: agilent_sureselect_exome_version_2_broad_refseq_cds_only_hs37 is added to make create-submission-archive working on models with that target_region_set_name. Refer to https://rt.gsc.wustl.edu/Ticket/Display.html?id=108635
=> Add reagent info of new target_region_set_name to TCGA Sdrf.pm

lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json, lib/perl/Genome/Sys/LSF/ResourceParser.pm
This ensures that later, when we prepare to submit a workflow to PTero, that the JSON formatter treats some values as numbers instead of strings.
=> Add formatters to ResourceParser

bin/genome-env
This commit updates the test database template to a new version which contains the `config.qc` table. I believe that merging this in is a prerequisite to #846 passing tests!
=> New test-db snapshot

lib/perl/Genome/Model/ReferenceAlignment/Report/Summary.pm
The failing testcase in #1073 pointed out that we've been doing the work twice in this report.  This saves the result from the first time to use the second time.
=> Don't Generate RefAlign Summary Report Data Twice

lib/perl/Genome/Model/Build/Command/DetermineError.pm, lib/perl/Genome/Model/Build/Command/DetermineError.t
We now need to be able to find messages like these in the logs:
```
$ genome-perl -e 'use UR; UR::Object->fatal_message("Example!");'
FATAL: Example! at -e line 1
```
=> Look for output from new UR fatal_message().

lib/perl/Genome/Config/AnalysisMenu/Item.pm, lib/perl/Genome/Config/AnalysisProject/Command/AddMenuItem.pm, lib/perl/Genome/Config/AnalysisProject/Command/Create.pm
This helps reduce the list shown by default to the commonly used options.
The two statuses are `active` and `inactive` since in neither case does the menu item cease to function (i.e. `disabled`).
The changed commands won't work until the database is updated to add this column.
=> Add status to AnalysisMenu Items

lib/perl/Genome/Model/Build.pm
The changes introduced in #1061 mean that multiple processes could be trying to set the same metric for a build.  This change is to stop them from accidentally trying to commit multiple copies of the same metric.
This is similar to a `Genome::Utility::ObjectWithLockedConstruction`, but in this case the new value is kept rather than the old one.
=> Lock before setting build metrics.

lib/perl/Genome/Model/Tools/Tcga/Sdrf.pm
Adjacent normal is not tumor. Refer to https://rt.gsc.wustl.edu/Ticket/Display.html?id=108687. This PR needs early merge.
=> Add adjacent normal to the case of is_not_tumor

lib/perl/Genome/Process.pm, lib/perl/Genome/WorkflowBuilder/DAG.pm
Instead of setting the PTERO_WORKFLOW_SUBMIT_URL env variable.  This uses features made available here: https://github.com/genome/ptero-perl-sdk/pull/96
=> Use submit_url option when submitting PTero workflows

lib/perl/Genome/Process.pm
These results do not depend on any of the data being analyzed, and as such are not CLE-specific.
=> Exclude index results from CLE verification.

lib/perl/Genome/Model/SingleSampleGenotype.pm.xml, lib/perl/Genome/Model/SingleSampleGenotype/Command/HaplotypeCaller.pm, lib/perl/Genome/Model/SingleSampleGenotype/Command/HaplotypeCaller/BucketIterator.pm, lib/perl/Genome/Model/SingleSampleGenotype/Command/HaplotypeCaller/BucketIterator.t
It has been decided that it is preferable to produce per-chromosome GVCFs rather than have collections of chromosomes bundled together. In order to still have consistently-sized jobs (and avoid splitting hundreds of ways, which will pound the source BAM file), run the HaplotypeCaller on each entry in the bucket in turn.
=> Run the HaplotypeCaller serially on each contig in a bucket.

etc/genome/spec/lsf_resource_chimerascan.yaml, etc/genome/spec/lsf_resource_rnaseq_chimerascan.yaml, lib/perl/Genome/Model/RnaSeq/Command/DetectFusions/Chimerascan/DetectorBase.pm
So users do not need run builds with changed lsf limit from custom snapshot or checkout.
=> Use config to get lsf_resource for chimerascan

lib/perl/Genome/Site/TGI/Command/SyncSysUserWithLdap.pm
Use status_message instead of custom STDOUT redirect status to allow printing
of messages during cron runs.
=> Sync Users: use status_message

lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/FastqsToBam.pm, lib/perl/Genome/InstrumentData/Command/Import/WorkFlow/SortBam.pm
use arrayref shellcmd sanitize sample name before using it in  afile name
problems
=> InstData Import: Avoid shell errors associated with odd charcters

lib/perl/Genome/Model/SingleSampleGenotype/Command/QualityControl.pm
The values from `Genome::Qc::Run` weren't getting used since this pipeline bypasses the alignment dispatcher.
=> Add LSF queue and resource request to the SSG QC command.

lib/perl/Genome/Command/PteroWorkflowMixin.pm, lib/perl/Genome/Model/Build.pm, lib/perl/Genome/Model/Command/Services/Build/Scan.pm, lib/perl/Genome/Process.pm, lib/perl/Genome/Ptero/Utils.pm
Because PTero run builds don't have an LSF job related to the workflow, the build scan thinks they're bad.
=> Dont fail ptero builds

lib/perl/Genome/Model/SingleSampleGenotype/Result/HaplotypeCaller.pm, lib/perl/Genome/Model/SingleSampleGenotype/Result/HaplotypeCaller.t
* Include the name of the contig (if there's only one).
* Use `.gz` extension so the file is compressed.
* Add an accessor so the VCF files can be listed more easily.
=> Updates to HaplotypeCaller file naming in SSG

lib/perl/Genome/Model/SomaticValidation/Command/DetectVariants.pm, lib/perl/Genome/Model/SomaticValidation/Command/ReviewVariants.pm, lib/perl/Genome/Model/SomaticValidation/Command/ValidateLargeIndels/CreateAssembledContigReference.pm
I noticed several builds that were done save for PENDing jobs for things that weren't going to run.  This allows these two steps to shortcut so we don't wait for slots just to find there's nothing to do.
=> Shortcut Several Skipped SomVal Steps

lib/perl/Genome/Model/SomaticValidation/Command/AlignReads.pm
Some jobs scheduled by the dispatcher (e.g. the new QC framework job) will end up in the "alt" queue, so this job needs to be in the lower-priority queue.
(In our current configuration, the "alt" queue is `apipe` and the other is `long` (with corresponding `pd` queues for builder).)
=> Use primary queue to submit SomVal AlignReads job.

lib/perl/Genome/Model/Tools/Gatk/HaplotypeCaller.pm, lib/perl/Genome/Model/Tools/Gatk/HaplotypeCaller.t
We switched to requesting gzipped GVCF in #1115.  However, GATK 3.4 contains a bug that requires two additional (deprecated) parameters to be supplied when a gzipped file is requested.  (This is fixed in 3.4-46, but that version is not tagged in their public repository.)
=> Add extra parameters when gzipped GVCF requested in version 3.4 of HaplotypeCaller.

lib/perl/Genome/Process.pm, lib/perl/Genome/Process/Command/Run.pm
These changes are necessary for starting builds using PTero as the workflow backend.
=> Ptero submit after process committed

lib/perl/Genome/Model/Tools/BamQc/Run.pm
It is not used in the workflow and WorkflowBuilder, when launching a
PTero workflow disallows unused inputs.
=> Remove clean_bam from workflow inputs

lib/perl/Genome/Process/Command/View.pm
The clean_up_timestamp was throwing away everything after the first '.'
which isn't desired here.
=> Don't try to format body_text when displaying notes.

etc/genome/spec/lsf_resource_gatk_haplotype_caller.yaml, lib/perl/Genome/Model/SingleSampleGenotype/Command/HaplotypeCaller/BucketIterator.pm
Thus far the jobs have fit within the standard 4GB memory reservation.  The ones I looked at showed `/tmp` usage around 100-150MB; the reservation of 1 GB should ensure they don't land on a completely full blade.
This will then also be ready if some cases have stronger requirements.
=> Set a default resource request for the BucketIterator.

lib/perl/Genome/Disk/Command/Allocation/Unarchive.pm, lib/perl/Genome/Disk/Command/Allocation/Unarchive.t, lib/perl/Genome/Disk/Command/Allocation/UnarchiveBase.pm, lib/perl/Genome/Model/Build/Command/Unarchive.pm
Unarchiving now requires an analysis project to be specified instead of a lab.  This analysis project will be linked to any software results that are unarchived.  Additionaly, unarchiving a build now
requires that its model belong to an analysis project.
Arbitrary unarchives will be supported via the new export command in #1090.
=> Unarchiving now requires an AnP instead of a lab.

lib/perl/Genome/WorkflowBuilder/Command.pm
This commit makes getting lsf parameters for use with PTero work more like other cases by using the existing `operation_type_attributes()` method to decide whether the lsf resource string should come from the Genome command class or from `Genome::WorkflowBuilder::Command`.  It also gets the queue name and project name from the `operation_type_attributes()`.
Since the queue and project name could be specified in the resource string, the workflow builder command, and the genome command class, we should consider the order of precedence.  Clearly, the queue and project specified on the workflow builder command takes precedence over a value supplied on the Genome command class.  It is not clear to me whether a queue or project specified in the lsf resource string should take precedence over …
=> Set queue and projectName when getting ptero lsf params

etc/genome/spec/lsf_resource_dv2_dispatcher.yaml
Recently there are quite a few of som-var builds failed at Detect_Variants because memory usages are over 600 MB limit.
=> Increase memory limit of lsf_resource_dv2_dispatcher

etc/genome/spec/lsf_project_name.yaml, etc/genome/spec/ptero_lsf_polling_interval.yaml, lib/perl/Genome/Model/Build.pm, lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json, lib/perl/Genome/WorkflowBuilder/Command.pm
This PR enables you to configure the polling interval that the PTero lsf service uses to track jobs.  Additionally, this PR ensures that lsf jobs associated with a build run with PTero all have a projectName set.
=> PTero LSF Stuff

lib/perl/Genome/Qc/Tool/VerifyBamId.pm, lib/perl/Genome/Qc/Tool/VerifyBamId.t
This file would then be used if no qc_genotype_vcf_file is specified in the build
=> Add optional property to VerifyBamId QC tool to set default genotype vcf file

lib/perl/Genome/Model/Tools/Tcga/Sdrf.pm
For some TCGA builds, current cghub id retrieve ways do not work. For example, mount path of merged bam could be changed after unarchiving and build subject extraction_label do not always return proper TCGA names. This PR adds a lookup hash by searching for unique bam base_name and uses name_in_vcf to replace extraction_label. This PR needs early merge.
=> TCGA Priorities: Add alternative way to get cghub id

lib/perl/Genome/Config/AnalysisProject/Command/View.pm
Although the `view` command shows a warning banner when the project is pending or on hold (to notify the user they need to `release` it before processing begins), it didn't otherwise display the status of the project.  Now it does!
=> Include status in `genome analysis-project view` output

lib/perl/Genome/Model/Command/Admin/RemoveDiskAllocationsFromTestdb.pm
`delete local` did not only remove the key from the hash locally. Thus, when the allocation shelled out to perform the deletion, it connected to the production database and couldn't find the allocation.
Splitting this to two lines seems to have the intended effect of removing the localized version.
=> RemoveDiskAllocationsFromTestDb remembers which TestDB was used.

lib/perl/Genome/Model/Metric.pm, lib/perl/Genome/SoftwareResult/Metric.pm
While working with @susannasiebert today, we noticed that `Genome::Model::Metric`s and `Genome::SoftwareResult::Metric`s have different interfaces. One responds to `metric_{name,value}` and the other `{name,value}` which is frustrating :frowning: Ironically, their column names are consistent with each other, but the properties are named differently in the class definitions.
This PR makes it so both types of metrics respond to both interfaces. There are other small inconsistencies that this does not address (one has read-only properties, the other doesn't for instance). Eventually it seems like we should have one `Metric` class with `SoftwareResult` and `Model` metrics varying only in table name.
Thoughts?
=> Make name/value accessors consistent for differing metric types.

lib/perl/Genome/VariantReporting/Command/ShowDocs.t.expected-output/interpreters/variant-callers, lib/perl/Genome/VariantReporting/Generic/NCallersBase.pm, lib/perl/Genome/VariantReporting/Generic/NCallersFilter.pm, lib/perl/Genome/VariantReporting/Generic/NCallersFilter.t, lib/perl/Genome/VariantReporting/Generic/VariantCallersInterpreter.pm, lib/perl/Genome/VariantReporting/Generic/VariantCallersInterpreter.t
The reports were including variants that were filtered out upstream by one or more of the individual callers, but those callers were being counted toward the 'n-callers' filter cutoff, which is not desirable.  I also did a small refactor so that the n-callers filter and variant-callers interpreter now use the same bit of code to decide which filters to count/include
=> Ncallers fix

lib/perl/Genome/VariantReporting/Command/Wrappers/Trio.pm
This attempts to prevent overwriting of the IGV session labels to mistakenly indicate that the Followup Sample is the Discovery and vice versa.
=> Attempt to fix Trio Reporting IGV labels

lib/perl/Genome/Process/Command/DiffBlessed.pm.YAML
This should fix failing model tests.
=> update blessed process to account for new N-caller and VAF fixes

lib/perl/Genome/Model/Tools/Tcga/CreateSubmissionArchive.pm, lib/perl/Genome/Sample.pm, lib/perl/Genome/Sample.t
For some rare cases, LIMS does not store any TCGA name as external_name in sample attributes, but does store as sample extraction_label instead.
=> TCGA Priorities: make sample get_tcga_names return all possible tcga names

lib/perl/Genome/Model/Tools/DetectVariants2/Filter/VarscanHighConfidence.pm, lib/perl/Genome/Model/Tools/DetectVariants2/Filter/VarscanHighConfidenceIndel.pm
These don't spawn workflows, so with this change they'll use the default queue for workers specified in [DV2/Filter.pm](https://github.com/genome/genome/blob/2d2f91c10ed2187e5d8346400b61b4edcafb2e69/lib/perl/Genome/Model/Tools/DetectVariants2/Filter.pm#L160).
=> Remove LSF queue overrides in Varscan "high confidence" filters.

lib/perl/Genome/Disk/Command/Allocation/UnarchiveBase.pm
Currently, the command prints out this:
````
Unarchiving allocation(s) for Analysis Project Genome::Config::AnalysisProject=HASH(0x7c07088)
````
Now it would print out this:
````
Unarchiving allocation(s) for Analysis Project: My super sweet analysis project (id)
````
=> Use display_name for printing AnalysisProject when Unarchiving

etc/genome/spec/disk_group_trash.yaml, lib/perl/Genome/Disk/Allocation.pm, lib/perl/Genome/Disk/Command/Allocation/Purge.pm, lib/perl/Genome/Disk/Detail/Allocation/Purger.pm, lib/perl/Genome/Disk/Volume.pm, lib/perl/Genome/Site/TGI/SiteLib/Genome/Disk/Group/Validate/GenomeDiskGroups.pm
In practice the trash volumes were a waste of space as data was never reclaimed therefrom.  They're being retired, so now we can remove data directly when purging.
=> Remove trash folder support.  Delete purged data immediately.

etc/genome/spec/software_result_async_locking.yaml, etc/genome/spec/software_result_async_locking_exit_code.yaml, etc/genome/spec/software_result_async_locking_initial_interval.yaml, etc/genome/spec/software_result_async_locking_max_interval.yaml, etc/genome/spec/software_result_async_locking_num_attempts.yaml, etc/genome/spec/sys_lock_exit_code.yaml, lib/perl/Genome/Ptero/Wrapper.pm, lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json, lib/perl/Genome/SoftwareResult.pm, lib/perl/Genome/Sys/Lock/FileBackend.pm, lib/perl/Genome/WorkflowBuilder/Command.pm
Instead of sleeping and consuming a shell-command worker while waiting on locks, this PR allows you to configure Genome to exit with a particular exit-code when a lock cannot be obtained.  When submitting the workflow, 'retrySettings' are specified to the shell-command service that specify that when the job exits with that particular exit-code the service should retry the job.
This will allow us to scale up without increasing the number of shell-command workers.
=> Asynchronous Shortcutting when using PTero

lib/perl/Genome/Site/TGI/CleTest/prime-db.pl
We have a few instances of more than one converter for a given pair of reference sequences, but only one shouldn't have test name set. This alters the query to ensure we only pull those converters where test_name is not set and leaves in the check to make sure we only get back one.
=> Only load those converters that don't have test_name set

lib/perl/Genome/Model/Command/Services/ListBuildQueue.pm, lib/perl/Genome/Model/Command/Services/ListBuildQueue.t
As we move to PTero, we can't rely on the size of the workflow LSF queues to limit our build starts.  
It is not ideal that this hard-codes a multiplier for apipe-builder; several things about the build process seem to have this "feature".
=> Add running build limit in "list-build-queue"

lib/perl/Genome/Utility/File/Comparer.pm
We were already using `File::Compare::compare` explicitly in this module.
=> Don't import "compare" since we're defining our own.

lib/perl/Genome/SoftwareResult/StageableSimple.pm
I don't think this fails in practice, because it is far more common to call on either the specific subclass or on `Genome::SoftwareResult` itself.  Just in case, though :smile:
=> Let UR re-call with the correct subclass if StageableSimple called abstractly.

lib/perl/Genome/Model/Command/Admin/PurgeSoftwareResultsFromAnalysisProject.pm
This replaces the old --dry-run option with --report.  When --report is used, it prints a report about what would be removed without actually removing anything.  The report looks like this (some lines removed for clarity):
```
Genome::Model::Tools::DetectVariants2::Classify::Tier: 1.125 MB in 9 software results
4722238e6ade46989326d76f08b560d4 => 128 KB
a65b5fe4e1254e7390a0bbd31fbd90b3 => 128 KB
2ffc70827eee4822aa025869119d4933 => 128 KB
Genome::Model::Tools::DetectVariants2::Result: 5.938 MB in 23 software results
37166635e58a4867a100a1a5c239e7f0 => 384 KB
47f985e931ec4a50b09540a9dde1cfcb => 64 KB
62f19130ea9443e395ea8804b3c6b726 => 512 KB
2fb27568cfb64d1aaf9fe39f28b81bac => 320 KB
Genome::Model::Tools::DetectVariants2::Result::Filter: 100.812 MB in 728 software results …
```
=> PurgeSoftwareResultsFromAnalysisProject report

lib/perl/Genome/Sys/Lock/FileBackend.pm, lib/perl/Genome/Sys/Lock/NessyBackend.pm
Genome in the TGI environment uses these backends, so if they indirectly use Genome it causes a circular dependency with sometimes indeterminate effects.
This fixes the currently-failing testcase on `master` for me.
=> Now that Genome::Logger uses Genome, only require it to break cycle.

lib/perl/Genome/Role/CommandWithColor.pm
This was removed in the conversion to a role in c583791b93cc8ba669fa7730de9e4515f96b5039, but it is still being used in several places.
This fixes one of the issues exposed by the model tests (i.e., it restores the function of `genome model build view`).
=> Add back _status_color subroutine.

lib/perl/Genome/Model/Tools/Sam/Readcount.pm
This should take care of another class of jobs that was ending up in the default queue.
=> Add an LSF Queue specification to GMT: Sam::Readcount

lib/perl/Genome/Interfaces/Comparable/Command/Diff.pm, lib/perl/Genome/Interfaces/Comparable/Command/DiffBlessed.pm, lib/perl/Genome/Model/Build/Command/Diff.pm, lib/perl/Genome/Model/Build/Command/DiffBlessed.pm, lib/perl/Genome/Model/Build/Command/DiffBlessed.t, lib/perl/Genome/Process/Command/Diff.pm, lib/perl/Genome/Process/Command/DiffBlessed.pm, lib/perl/Genome/Process/Command/DiffBlessed.t
This reverts commit b251a2a9eed11c399251381776550e2aa6b6b2fa.
The error of not finding 'has_diffs' on genome process diff blessed causeed investigation into this issue. It was decided that having the diff as roles was not suitable, and they should remain commands that pass on behavior via inheritance.
A fix for this problem was proposed in #1180.
=> Revert "Convert Diff/DiffBlessed commands into UR Roles"

lib/perl/Genome/InstrumentData/AlignmentResult/PerLaneTophat.pm, lib/perl/Genome/InstrumentData/Composite/Workflow-unit.t, lib/perl/Genome/InstrumentData/Composite/Workflow.t, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator/Align.pm
This is a feature that RefAlign has but the AlignmentDispatcher did not.  ("AlignAndMerge" is using this same approach for SpeedSeq in SomaticValidation; this does the same thing for regular "Align".)
=> Calculate the LSF resource for Alignment based on the Instrument Data

lib/perl/Genome/Model/Command/Admin/FailedModelTicketBase.pm
The `failed-model-tickets` script was reporting a few models that were already in a ticket, because that ticket had been stalled.  This updates the search to include stalled tickets so they are not re-reported.  (Additionally, `failed-model-ticket-status` will also include stalled tickets in its default output.)
=> Include stalled tickets in failed-model-tickets scripts.

lib/perl/Genome/Model/Build.pm
Inline builds do not have processes created in [`Genome::Model::Build->_launch`](https://github.com/genome/genome/blob/981439e064d6042a3abb384ccc46bcd52bfa7787/lib/perl/Genome/Model/Build.pm#L1431).
=> Don't try to call ptero_workflow_proxy on an undefined value.

lib/perl/Genome/InstrumentData/Composite/Workflow.pm
This was updated to stop using Workflow in #924, but these straggling references were not changed.
=> Stop using Workflow since this is built with WorkflowBuilder.

lib/perl/Genome/InstrumentData/Command/AlignReads.pm
In #1182 the resource request generation for alignments was changed.
Because the fallback is now overridden, the queue information can be lost if the aligner-specific implementation doesn't reiterate it.  These parameters establish a default, so the job still goes to the alignment queues if not otherwise specified.
=> Specify a default LSF queue for aligners that don't list one explicitly.

lib/perl/Genome/Model.pm
In #1045, `Build` was updated to accept workflows from `WorkflowBuilder`.  This takes advantage of that for our one-step builds (like `ReferenceSequence`).
=> `_execute_build`-style builds use WorkflowBuilder

lib/perl/Genome/InstrumentData/Composite/Workflow-unit.t, lib/perl/Genome/InstrumentData/Composite/Workflow.pm, lib/perl/Genome/InstrumentData/Composite/Workflow/Generator.pm
In the beginning was `Workflow` and it accepted its inputs as a list, so this produced an `ARRAY` reference.  At some point this was changed to call `Genome::WorkflowBuilder::DAG`, which accepts a hash reference, and a comment was added questioning the reasonableness of the choice of an `ARRAY` reference.  In #924 it was suggested we should change it.
Here are a couple versions (either the first commit or both together) of how it might look to change it.  There's a third possibility where even more things get changed to hashes as well.
=> Return a HASH reference from Composite Workflow Generator

lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalsePositiveVcf.pm, lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalsePositiveVcf.t, lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalsePositiveVcfBase.pm, lib/perl/Genome/Model/Tools/DetectVariants2/Filter/FalsePositiveVcfDenovo.pm
Many of them will get loaded by the base class anyway, but they aren't used in these specific children.
=> Remove Unused Includes in FalsePositiveVcf Filters

etc/genome/spec/ptero_log_directory.yaml, lib/perl/Genome/Ptero/Wrapper.pm, lib/perl/Genome/WorkflowBuilder/DAG.pm
This is a proposed solution to the issue raised in #1186.  If it's acceptable, the open `WorkflowBuilder`-conversion PRs will be revised to use it.
=> Create a uniform way to get the parent log directory for a DAG.

lib/perl/Genome/Model/Tools/DetectVariants2/Dispatcher.pm
What's new:
* Switch to WorkflowBuilder to create the DV2 workflow.
Potential issue:
* This still does `use Workflow;` in order to set its log directory to that of the Workflow it happens to be running inside.
Future development:
* Split this module into one thing that makes the workflow, and another step that does the additional work after the workflow completes.
=> DV2 Dispatcher uses WorkflowBuilder

lib/perl/Genome/Config.pm, lib/perl/Genome/Config/AnalysisProject.pm, lib/perl/Genome/Config/AnalysisProject/Command/AddEnvironmentFile.pm, lib/perl/Genome/Config/AnalysisProject/Command/AddEnvironmentFile.t, lib/perl/Genome/Model/Build/Command/Start.pm
Have you ever wanted to have one Analysis Project run PTero without making them all do so?  Have you ever wished you could change the LSF resource request for an entire project at once rather than manually starting models?  This is the pull request for you!
Features:
* Adds a new location for `Genome::Config` to search for configuration that takes precedence over the home directory (but still lower precedence than manually set environment variables).
Caveats:
* Won't work unless we update our production users to use a `genome/config.yaml` instead of manually set environment variables.
=> Add support for AnP-based envrionmental configuration.

lib/perl/Genome/Model/Tools/DetectVariants2/BamToCna.pm
WorkflowBuilder is more stringent about validating its components than Workflow.  "params" needs to be declared as an input and output for the workflow that the DetectVariants2 Dispatcher creates to validate.  (The Dispatcher passes "params" to all DV2 detectors--the base Detector class declares "params" appropriately, but this class overrides that definition.)
=> BamToCna declares "params" as an Input and Output

lib/perl/Genome/Model/Tools/DetectVariants2/Filter/TigraValidation.pm
#1206 had a bug in it. This corrects the mistake.
=> Call recursively_set_log_dir on an object whose class implements it.

lib/perl/Genome/Model/RnaSeq/Command/PicardRnaSeqMetrics.pm, lib/perl/Genome/Model/RnaSeq/Command/PicardRnaSeqMetrics.t
This bug of RnaSeq build property name is from #1195 and causing jenkins rnaseq test build failures. It needs a early merge.
=> It is reference_sequence_build not reference_build

lib/perl/Genome/Model/Tools/Vcf/CreateCrossSampleVcf/CreateCrossSampleVcfBase.pm
This doesn't really use `Workflow` since it was converted to a Process as part of #429.
=> Remove unused CCSVCF includes.

etc/genome/spec/lsf_resource_rnaseq_cufflink.yaml, etc/genome/spec/lsf_resource_rnaseq_cufflinks.yaml, lib/perl/Genome/Model/RnaSeq/Command/Expression/Cufflinks.pm
So it is convenient to change lsf limit for cufflink run.
=> Add lsf_resource_rnaseq_cufflinks to genome config

lib/perl/Genome/Model/Build.pm, lib/perl/Genome/Process/Command/Run.pm
In Perl closures close over lexical (`my`) variables but not over `local`ized globals.
This change saves a copy of the environment before creating the submission closure.  This allows the environment to be customized the same way before either `submit`ting or `launch`ing a Process.
This addresses an issue using #1201 with PTero.
=> Submitting a Process Preserves Environment

lib/perl/Genome/Config/AnalysisProject/Command/ReplaceModel.pm, lib/perl/Genome/Config/AnalysisProject/Command/ReplaceModel.t
This command takes a model and new config item and copies the model,
replacing the model params as directed be the config.The model is added
to the AnP and queued to build.
=> AnP: Replace Model Command

lib/perl/Genome/Model/Tools/Gatk/Base.pm, lib/perl/Genome/Model/Tools/Mutect.pm, lib/perl/Genome/Model/Tools/Somatic/PlotCircos.pm, lib/perl/Genome/Sys/LSF/ResourceParser.pm, lib/perl/Genome/Sys/LSF/ResourceParser.t, lib/perl/PAP/Command/BlastP.pm
The Genome codebase contained some strings meant to represent lsf resources that were neither valid resource requirement strings or bsub command options.  This PR fixes those problems.
=> Lsf resource parsing

lib/perl/Genome/Model.pm, lib/perl/Genome/Model/Build/Command/Start.pm, lib/perl/Genome/Model/RnaSeq/Command/CoverageMetrics.pm, lib/perl/Genome/Model/RnaSeq/Command/RnaSeqMetrics.pm, lib/perl/Genome/Model/RnaSeq/Command/SpliceJunctionMetrics.pm, lib/perl/Genome/ModelDeprecated.pm
This completes a few long-standing TODOs by removing redundant methods.
(It seems like the `${status}_builds` methods in `ModelDeprecated` are also ripe for removal.  Some of them are still used at the moment.)
=> Remove some redundant methods from Model.pm

lib/perl/Genome/Ptero/ToJSON.t, lib/perl/Genome/Ptero/ToJSONForProcess.t, lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/jagged-parallel-models/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/n-shaped/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/nested-parallel-models/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties-unspecified/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/optional-input-properties/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/parallel-cmd/ptero_workflow_for_process.json, lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow.json, lib/perl/Genome/Ptero/workflow_tests/parallel-model/ptero_workflow_for_process.json, lib/perl/Genome/WorkflowBuilder/Command.pm
This should not be merged before:
https://github.com/genome/ptero-perl-sdk/pull/109 is packaged and deployed via genome-snapshot-deps.
and
https://github.com/genome/ptero-lsf/pull/110 is deployed to production.
=> Use pre/post-exec scripts for ptero LSF jobs

lib/perl/Genome/Model/SingleSampleGenotype/Command/HaplotypeCaller/BucketIterator.pm
Since each interval is an independent run, we can save the results for those intervals even if a subsequent one does not succeed.
(This would probably be better with genome/UR#62.)
I didn't go with the shell-out approach that some things (like `IntermediateAlignmentResult`) use, but that is a possible alternative if calling `commit` mid-way seems suboptimal.
=> Commit after each interval of the HaplotypeCaller runs.

lib/perl/Genome/Model/SingleSampleGenotype.pm, lib/perl/Genome/Model/SomaticValidation.pm
The generated version points at the bridge table and so does not require the manually-generated `add_` methods either.
=> Remove explicit _id properties that Model.pm will generate for us.

lib/perl/Genome/Model/Build/Command/Export.pm
The path_for_allocation might be a parent of the file or directory being symlinked.  We were getting infinite recursion when the allocation resolved to a parent of the current allocation's directory.  This
solution ignores that the symlink might be in an allocation and happily copies the contents.
=> Don't copy entire allocations in place of symlinks.

bin/genome-env
Looks like UR_DBI_NO_COMMIT was still true when the allocation removal ran, so
calling delete() on allocations did not remove the files.
=> Ensure allocations are cleaned up when genome-test-env exits

lib/perl/Genome/ProcessingProfile/ReferenceAlignment.pm, lib/perl/Genome/processing_profile_subclassing.t
We'll need to wait for old snapshots to fall out of use before editing the class of existing profiles and removing the subclasses altogether.
=> Stop subclassing ReferenceAlignment ProcessingProfiles on sequencing_platform.

lib/perl/Genome/Sys.pm
This partially reverts 0a28189020054af452b08c8d496234b1734bf403 from PR #809.  The initial check does not seem to be sufficient to ensure the volume is mounted.
=> Check for directory existence each time before calling mkdir.

lib/perl/Genome/Model/ReferenceAlignment.pm, lib/perl/Genome/ProcessingProfile/ReferenceAlignment.pm
They're hold-overs from `maq` or early versions of the pipeline.
=> Remove Obsolete RefAlign ProcessingProfile Parameters

lib/perl/Genome/Model/ReferenceAlignment/Report/Summary.pm
This quiets this warning:
```
Use of inherited AUTOLOAD for non-method Genome::Model::Tools::Joinx::SnvConcordanceByQuality::parse_results_file() is deprecated at .../Genome/Model/ReferenceAlignment/Report/Summary.pm line 220.
```
=> Use GMT:Joinx::SnvConcordanceByQuality in RefAlign Summary Report.

lib/perl/Genome/Model/SomaticVariation/Command/CreateReport.pm, lib/perl/Genome/Model/SomaticVariation/Command/TestHelpers.pm
The implementation in the build class is designed to handle both `RnaSeq` and `ReferenceAlignment` builds.
=> SomVar CreateReport uses Build Accessors for BAMs and Reference

lib/perl/Genome/Model/Build/ReferenceAlignment.pm, lib/perl/Genome/Model/Build/RnaSeq.pm, lib/perl/Genome/Model/ReferenceAlignment.pm
An abridged history of `sub libraries` (from 176611fdfd9e3818d5c51e827f17cee6c6a58580):
> The "temp hack" was added in bd502ac71a8a613e95af57f429d98b1d948abc76
on 14 July 2008 to the original `Genome::Model`.  It was then migrated to
`Genome::Model::ShortRead` before moving to its most recent location here
in `Genome::Model::ReferenceAlignment`.
As a bonus, this PR also removes one method from `Genome::Model::Build::RnaSeq`.
=> Remove Old Alignment Accessors

lib/perl/Genome/Model/SomaticValidation.pm
`known_sites` is an `is_many` property, and the automatic generation of the id property is not set to happen for is_many inputs.
=> Restore the known_sites Magic to SomaticValidation

lib/perl/Genome/Model/SomaticValidation.pm
This change is of little consequence for the moment (since `Build` converts this back into XML regardless), but it is a step on the path to removing `Workflow`!
=> SomaticValidation Workflow is Instantiated with WorkflowBuilder.

lib/perl/Genome/Model.pm, lib/perl/Genome/Model/Event/Build/ReferenceAlignment/AnnotateTranscriptVariants.pm, lib/perl/Genome/Model/ReferenceAlignment.pm, lib/perl/Genome/ProcessingProfile/ReferenceAlignment.pm
`ReferenceAlignment` was the last laggard still using this feature.
=> Remove Delegation of `_initialize_build` to ProcessingProfiles.

lib/perl/Genome/InstrumentData/Solexa.pm, lib/perl/Genome/Model/SomaticValidation.pm, lib/perl/Genome/Model/SomaticValidation/Command/DefineModels.pm, lib/perl/Genome/Model/SomaticValidation/Command/DefineModels.t, lib/perl/Genome/Model/SomaticValidation/Command/DefineValidationModel.pm, lib/perl/Genome/Model/SomaticValidation/Command/DefineValidationModel.t, lib/perl/Genome/ProcessingProfile/ReferenceAlignment.pm
These defaults are not up-to-date, and we now use the `ConfigureQueuedInstrumentData` command to decide what profiles to use in most cases.
=> Remove Old "Default Profile"s

lib/perl/Genome/Config/AnalysisProject/Command/View.pm
This provides notice if `genome analysis-project add-environment-file` has been used for a given AnalysisProject.
=> AnalysisProject View: Display Environment Config if One Exists.

lib/perl/Genome/Model/ReferenceAlignment.pm
The build would've been a more appropriate place for many of these, but we're about to remove the events, anyway!
=> Remove disused event accessors from ReferenceAlignment Model.

lib/perl/Genome/Model/Build/ReferenceAlignment.pm, lib/perl/Genome/Model/Command/InstrumentData/AlignmentBams.t
This is far more direct than assembling all the aligner params and querying!
=> ReferenceAlignment: Use user relationships to find alignments.

lib/perl/Genome/Sys.pm
This is intended to allow for easier inspection and debugging of in-progress workflow steps.
=> Configure permissions on tempdir when using LSF location.
